<?php

return [
    'validation' => [
        'success' => 'admin_layout.json の検証が正常に完了しました。',
        'schema_failed' => 'JSON スキーマ検証に失敗しました: :errors',
        'unexpected_error' => '予期しないエラーが発生しました: :message',
        'schema_not_found' => 'JSON スキーマファイルが見つかりません: :path',
        'schema_parse_error' => 'JSON スキーマファイルのパースエラー: :error',
        'file_not_found' => 'ファイルが見つかりません: :path',
        'json_parse_error' => 'JSON パースエラー (:file): :error',
        'version_unknown' => '不明なバージョン',
        'version_error' => 'バージョン情報を取得できません',
        'module_required' => 'モジュール名は必須です',
        'module_string' => 'モジュール名は文字列である必要があります',
        'module_format' => 'モジュール名は英文字で始まり、英文字、数字、アンダースコア、ハイフンのみを含むことができます',
        'module_max_length' => 'モジュール名は50文字を超えることはできません',
        'log' => [
            'success' => 'admin_layout.json 検証成功',
            'failed' => 'admin_layout.json 検証失敗',
            'exception' => 'admin_layout.json 検証中に例外が発生しました',
            'version_error' => 'スキーマバージョン情報の取得に失敗しました',
        ],
    ],
    'loader' => [
        'validation_failed' => 'モジュール :module のレイアウト検証に失敗しました: :errors',
        'file_not_found' => 'レイアウトファイルが見つかりません: :path',
        'json_parse_error' => 'JSON パースエラー (:file): :error',
        'file_load_error' => 'ファイル読み込み中にエラーが発生しました (:path): :error',
        'log' => [
            'cache_hit' => 'キャッシュからレイアウトデータを読み込みました',
            'cache_invalidated' => 'キャッシュが無効化されました',
            'loaded' => 'レイアウトファイル読み込み完了',
            'cached' => 'レイアウトデータをキャッシュに保存しました',
            'cache_manually_invalidated' => 'キャッシュを手動で無効化しました',
            'all_cache_invalidated' => 'すべてのキャッシュを無効化しました',
            'file_load_error' => 'ファイル読み込みエラー',
        ],
    ],
    'command' => [
        'starting' => 'admin_layout.json ファイルの検証を開始します',
        'validating_module' => 'モジュール :module を検証中...',
        'validating_all_modules' => ':count 個のモジュール検証を開始します',
        'module_layout_not_found' => 'モジュール :module の admin_layout.json ファイルが見つかりません',
        'module_valid' => 'モジュール :module の検証成功',
        'module_invalid' => 'モジュール :module の検証失敗: :error',
        'unexpected_error' => 'モジュール :module で予期しないエラーが発生しました: :error',
        'modules_directory_not_found' => 'modules ディレクトリが見つかりません',
        'no_modules_found' => '検証するモジュールがありません',
        'module_summary' => 'モジュール :module の概要',
        'menu_name' => 'メニュー名',
        'menu_route' => 'ルート',
        'data_sources_count' => 'データソース数',
        'layout_type' => 'レイアウトタイプ',
        'validation_summary' => '検証結果の概要',
        'valid_modules_count' => '有効なモジュール',
        'invalid_modules_count' => '無効なモジュール',
        'missing_layouts_count' => 'レイアウトファイルなし',
        'invalid_modules_details' => '無効なモジュールの詳細:',
        'missing_layouts_details' => 'レイアウトファイルがないモジュール:',
        'cache_stats' => 'キャッシュ統計',
        'total_cached_modules' => 'キャッシュされたモジュール数',
        'cache_expiration' => 'キャッシュ有効期限',
        'cached_modules_details' => 'キャッシュされたモジュールの詳細:',
        'clearing_cache' => 'キャッシュを無効化中...',
        'cache_cleared' => 'キャッシュが無効化されました',
    ],
    'success' => [
        'loaded' => 'admin_layout.json の読み込みに成功しました',
        'cached' => 'レイアウトデータがキャッシュに保存されました',
    ],
    'error' => [
        'module_not_found' => '要求されたモジュールが見つかりません',
        'json_parse_error' => 'JSON パース中にエラーが発生しました',
        'file_not_readable' => 'ファイルを読めません',
        'json_parse_failed' => 'JSON パースに失敗しました',
        'validation_failed' => 'レイアウト検証に失敗しました',
        'server_error' => 'サーバー内部エラーが発生しました',
    ],
    'log' => [
        'cache_hit' => 'キャッシュからレイアウトデータを取得しました',
        'cache_updated' => 'キャッシュが更新されました',
        'layout_loaded' => 'レイアウトが正常に読み込まれました',
        'validation_completed' => 'レイアウト検証が完了しました',
        'layout_load_error' => 'レイアウト読み込み中にエラーが発生しました',
        'validation_error' => 'レイアウト検証中にエラーが発生しました',
        'service_cache_invalidated' => 'サービスでキャッシュを無効化しました',
        'service_all_cache_invalidated' => 'サービスですべてのキャッシュを無効化しました',
        'cache_invalidated' => 'キャッシュが無効化されました',
        'all_cache_invalidated' => 'すべてのキャッシュが無効化されました',
        'file_read_error' => 'ファイル読み取り中にエラーが発生しました',
    ],
];
