<?php

return [
    'source_type' => [
        'core' => 'コア',
        'module' => 'モジュール',
        'plugin' => 'プラグイン',
    ],
    'permission_type' => [
        'read' => '閲覧/ダウンロード',
        'update' => '編集',
        'delete' => '削除',
    ],
    'default_policy' => [
        'public' => '公開 (すべての認証ユーザー)',
        'owner_only' => 'アップローダー/管理者のみ',
        'read_only' => '読み取り専用',
    ],
    'validation' => [
        'file_required' => 'ファイルを選択してください。',
        'file_invalid' => '有効なファイルではありません。',
        'file_max' => 'ファイルサイズは :maxMB を超えることはできません。',
        'files_required' => 'ファイルを選択してください。',
        'files_array' => 'ファイル形式が正しくありません。',
        'files_min' => '最低1つ以上のファイルを選択してください。',
        'type_invalid' => '添付対象タイプが正しくありません。',
        'id_invalid' => '添付対象IDが正しくありません。',
        'role_ids_required' => 'ロールを選択してください。',
        'role_ids_invalid' => 'ロール形式が正しくありません。',
        'role_id_integer' => 'ロールIDは整数である必要があります。',
        'role_id_exists' => '存在しないロールです。',
        'order_required' => '順序データが必要です。',
        'order_array' => '順序データ形式が正しくありません。',
        'order_id_required' => '添付ファイルIDが必要です。',
        'order_id_exists' => '存在しない添付ファイルです。',
        'order_value_required' => '順序値が必要です。',
        'order_value_integer' => '順序値は整数である必要があります。',
        'permissions_required' => '権限情報が必要です。',
        'permissions_invalid' => '権限形式が正しくありません。',
        'permission_roles_invalid' => '権限別ロール形式が正しくありません。',
    ],
    'upload_success' => 'ファイルがアップロードされました。',
    'upload_batch_success' => 'ファイルが一括アップロードされました。',
    'upload_failed' => 'ファイルアップロードに失敗しました。',
    'delete_success' => 'ファイルが削除されました。',
    'delete_failed' => 'ファイル削除に失敗しました。',
    'reorder_success' => 'ファイル順序が変更されました。',
    'reorder_failed' => 'ファイル順序の変更に失敗しました。',
    'sync_roles_success' => 'ロールが同期されました。',
    'sync_roles_failed' => 'ロール同期に失敗しました。',
    'sync_permissions_success' => '権限が同期されました。',
    'sync_permissions_failed' => '権限同期に失敗しました。',
    'not_found' => '添付ファイルが見つかりません。',
    'access_denied' => 'この添付ファイルへのアクセス権限がありません。',
    'update_denied' => 'この添付ファイルの編集権限がありません。',
    'delete_denied' => 'この添付ファイルの削除権限がありません。',
];
