<?php

return [
    'login_success' => 'ログインに成功しました。',
    'login_failed' => '認証に失敗しました。',
    'register_success' => '会員登録に成功しました。',
    'register_failed' => '会員登録に失敗しました。',
    'logout_success' => 'ログアウトに成功しました。',
    'logout_all_devices_success' => 'すべてのデバイスからログアウトされました。',
    'password_reset_success' => 'パスワードが正常にリセットされました。',
    'password_reset_failed' => 'パスワードのリセットに失敗しました。',
    'invalid_credentials' => '無効な認証情報です。',
    'admin_login_success' => '管理者ログインに成功しました。',
    'admin_required' => '管理者権限が必要です。',
    'unauthenticated' => '認証が必要です。',
    'permission_denied' => '該当する権限がありません。',
    'layout_permission_denied' => 'レイアウトへのアクセス権限がありません。(必要な権限: :required_permissions)',
    'layout_guest_permission_denied' => 'ログインが必要なレイアウトです。(必要な権限: :required_permissions)',
    'invalid_permission_type' => '無効な権限タイプです。',
    'role_denied' => '該当するロールがありません。',
    'email_not_registered' => '登録されていないメールアドレスです。',
    'guest_permission_denied' => '非会員はこの操作を実行できません。ログインが必要です。',
    'scope_denied' => 'このリソースへのアクセス権限がありません。',
    'scope_type_all' => 'すべて',
    'scope_type_self' => '本人のみ',
    'scope_type_role' => '所有者ロール',
    'invalid_token' => '無効な認証トークンです。',
    'token_expired' => '認証トークンが期限切れです。もう一度ログインしてください。',
    'user_not_found' => 'ユーザーが見つかりません。',
    'account_inactive' => '無効化されたアカウントです。管理者にお問い合わせください。',
    'account_blocked' => 'ブロックされたアカウントです。管理者にお問い合わせください。',
    'account_withdrawn' => '退会済みのアカウントです。',
    'account_pending_verification' => '本人確認が完了していないアカウントです。メール認証を完了してください。',
    'reset_token_invalid' => '無効なパスワードリセットトークンです。',
    'reset_token_expired' => 'パスワードリセットトークンが期限切れです。再度リクエストしてください。',
    'password_reset_email_sent' => 'パスワードリセットメールが送信されました。',
    'email_send_failed' => 'メール送信に失敗しました。しばらく後にもう一度お試しください。',
    'account_locked' => 'ログイン試行回数の超過によりアカウントがロックされました。:minutes分後に再度お試しください。',
];
