<?php

return [
    'login_success' => 'ログインが成功しました。',
    'login_failed' => '認証に失敗しました。',
    'two_factor_required' => '認証番号を送信しました。受け取った番号を入力してログインを完了してください。',
    'two_factor_failed' => '認証番号が正しくないか、有効期限が過ぎています。',
    'two_factor_invalid_challenge' => '認証リクエストが見つかりません。最初からログインし直してください。',
    'register_success' => '会員登録が成功しました。',
    'register_failed' => '会員登録に失敗しました。',
    'logout_success' => 'ログアウトが成功しました。',
    'logout_all_devices_success' => 'すべてのデバイスからログアウトされました。',
    'password_reset_success' => 'パスワードが正常にリセットされました。',
    'password_reset_failed' => 'パスワードのリセットに失敗しました。',
    'invalid_credentials' => '無効な認証情報です。',
    'admin_login_success' => '管理者ログインが成功しました。',
    'admin_required' => '管理者権限が必要です。',
    'unauthenticated' => '認証が必要です。',
    'permission_denied' => '該当する権限がありません。',
    'layout_permission_denied' => 'レイアウトへのアクセス権限がありません。(必要な権限: :required_permissions)',
    'layout_guest_permission_denied' => 'ログインが必要なレイアウトです。(必要な権限: :required_permissions)',
    'invalid_permission_type' => '無効な権限タイプです。',
    'role_denied' => '該当するロールがありません。',
    'email_not_registered' => '登録されていないメールアドレスです。',
    'guest_permission_denied' => '非会員はこの操作を実行できません。ログインが必要です。',
    'scope_denied' => 'このリソースへのアクセス権限がありません。',
    'scope_type_all' => 'すべて',
    'scope_type_self' => '本人のみ',
    'scope_type_role' => '所有ロール',
    'invalid_token' => '無効な認証トークンです。',
    'token_expired' => '認証トークンが有効期限切れです。再度ログインしてください。',
    'user_not_found' => 'ユーザーが見つかりません。',
    'account_inactive' => '無効化されたアカウントです。管理者にお問い合わせください。',
    'account_blocked' => 'ブロックされたアカウントです。管理者にお問い合わせください。',
    'account_withdrawn' => '退会したアカウントです。',
    'account_pending_verification' => '本人認証が完了していないアカウントです。メール認証を完了してください。',
    'account_locked' => 'ログイン試行回数の超過によりアカウントがロックされました。:minutes分後に再度お試しください。',
    'account_locked_permanently' => 'ログイン試行回数の超過によりアカウントがロックされました。管理者にお問い合わせください。',
    'too_many_attempts' => 'リクエストが多すぎます。:seconds秒後にもう一度お試しください。',
    'account_unlocked' => 'アカウントのロックを解除しました。',
    'reset_token_invalid' => '無効なパスワードリセットトークンです。',
    'reset_token_expired' => 'パスワードリセットトークンが有効期限切れです。再度リクエストしてください。',
    'password_reset_email_sent' => 'パスワードリセットメールが送信されました。',
    'email_send_failed' => 'メール送信に失敗しました。しばらく後に再度お試しください。',
    'two_factor_delivery_failed' => '認証番号を送信できませんでした。管理者にお問い合わせください。',
];
