<?php

return [
    'cannot_delete_super_admin' => 'スーパー管理者は削除できません。',
    'circular_reference' => 'レイアウト循環参照を検出しました: :trace',
    'max_depth_exceeded' => 'レイアウトのネスト深度が最大許容深度(:max)を超えています。',
    'template_file_copy_failed' => 'テンプレートファイルのコピーに失敗しました: :source → :destination',
    'template_build_directory_creation_failed' => 'テンプレートビルドディレクトリの作成に失敗しました: :path',
    'template_dist_directory_not_found' => 'テンプレートdistディレクトリが見つかりません: :path',
    'template_not_found' => 'テンプレートが見つかりません: :identifier',
    'template_not_active' => 'テンプレートが有効化されていません: :identifier (ステータス: :status)',
    'layout' => [
        'duplicate_data_source_id' => 'data_sources IDが重複しています: :id',
        'duplicate_data_source_id_in_file' => 'レイアウトファイル内のdata_sources IDが重複しています: :ids (ファイル: :file)',
        'duplicate_data_source_id_extends' => 'extends継承関係でdata_sources IDが重複しています: :ids (子: :child, 親: :parent)',
        'not_found' => 'レイアウトが見つかりません: :name',
        'parent_not_found' => '親レイアウトが見つかりません: :parent (リクエストレイアウト: :child)',
        'include_file_not_found' => 'includeファイルが見つかりません: :path (解決されたパス: :resolved)',
        'invalid_include_json' => 'includeファイルのJSON形式が正しくありません: :path (エラー: :error)',
        'circular_include' => 'include循環参照が検出されました: :trace',
        'max_include_depth_exceeded' => 'includeの最大深度を超えています (最大: :max段階)',
        'include_outside_directory' => 'includeパスが許可されたディレクトリ外です: :path (許可: :allowed_dir)',
    ],
    'layout_version' => [
        'save_failed_after_retries' => 'レイアウトバージョンの保存に失敗しました。:attempts回の再試行後も失敗しました。',
        'save_failed_unexpected' => 'レイアウトバージョン保存中に予期しないエラーが発生しました。',
    ],
    'settings' => [
        'backup_creation_failed' => '設定バックアップファイルの作成に失敗しました。',
        'restore_failed' => '設定の復元に失敗しました。',
        'category_not_found' => '設定カテゴリが見つかりません: :category',
        'save_failed' => '設定の保存に失敗しました: :category',
        'json_parse_failed' => 'JSON ファイルのパースに失敗しました: :path (:error)',
        'add_category_module_only' => 'addCategory はモジュールでのみ使用できます。',
    ],
    'core_update' => [
        'handoff' => 'アップグレードハンドオフ: :after_version まで完了 — :reason (再実行: :resume_command)',
    ],
    'vendor' => [
        'composer_not_available' => 'Composerを実行できない環境です。バンドルモードを使用してください。',
        'composer_not_available_for_build' => 'vendor-bundleビルドはComposer実行が必要です。開発環境でComposerをインストール·設定した後、もう一度お試しください。',
        'bundle_build_composer_failed' => 'vendor-bundleビルド中にcomposer installの実行に失敗しました (exit :exit): :message',
        'composer_execution_failed' => 'Composerの実行に失敗しました: :message',
        'bundle_zip_missing' => 'vendor-bundle.zipファイルが見つかりません: :path',
        'bundle_manifest_missing' => 'vendor-bundle.jsonファイルが見つかりません: :path',
        'bundle_manifest_invalid' => 'vendor-bundle.jsonファイルの読み込みに失敗しました: :error',
        'bundle_integrity_failed' => 'バンドルファイルの整合性検証に失敗しました: :details',
        'bundle_schema_unsupported' => 'サポートされていないvendor-bundle.jsonスキーマバージョンです: :version',
        'zip_archive_not_available' => 'PHP ZipArchive拡張がインストールされていません。',
        'zip_hash_mismatch' => 'vendor-bundle.zipのハッシュが一致しません (期待値: :expected, 実際: :actual)。',
        'composer_json_sha_mismatch' => 'composer.jsonがバンドルビルド時点以降に変更されました。vendor-bundle:buildで再ビルドしてください。',
        'composer_lock_sha_mismatch' => 'composer.lockがバンドルビルド時点以降に変更されました。vendor-bundle:buildで再ビルドしてください。',
        'bundle_contains_unsafe_path' => 'バンドルzipに安全でないファイルパスが含まれています: :path',
        'extraction_failed' => 'バンドルzipの抽出に失敗しました: :message',
        'no_vendor_strategy_available' => 'バンドルのインストール戦略を決定できません。Composerとバンドルzipの両方が利用不可です。',
        'source_dir_not_found' => 'インストールソースディレクトリが見つかりません: :path',
        'target_not_writable' => '対象ディレクトリに書き込み権限がありません: :path',
        'target_not_writable_owner_hint' => '実行ユーザー(:current_user)とディレクトリ所有者(:owner)が異なります。\'chown -R :current_user_name :path\'を実行後に再試行するか、所有者(:owner_name)でSSHログイン後に実行してください。',
        'composer_json_not_found' => 'composer.jsonファイルが見つかりません: :path',
        'no_composer_lock' => 'composer.lockファイルが必要です。まずcomposer installを実行してください: :path',
        'vendor_dir_not_found' => 'vendor/ディレクトリが存在しません。まずcomposer installを実行してください: :path',
        'composer_binary_not_found' => 'Composerバイナリが見つかりません。COMPOSER_BINARY環境変数を設定するか、composerをPATHに追加してください。',
    ],
];
