<?php

return [
    'fetch_success' => '言語パックリストを取得しました。',
    'fetch_failed' => '言語パックリストを読み込めませんでした。',
    'not_found' => '言語パックが見つかりません。',
    'install_success' => '言語パックをインストールしました。',
    'install_failed' => '言語パックのインストールに失敗しました。',
    'activate_success' => '言語パックを有効化しました。',
    'activate_failed' => '言語パックの有効化に失敗しました。',
    'deactivate_success' => '言語パックを無効化しました。',
    'deactivate_failed' => '言語パックの無効化に失敗しました。',
    'uninstall_success' => '言語パックを削除しました。',
    'uninstall_failed' => '言語パックの削除に失敗しました。',
    'manifest_invalid' => 'language-pack.json の検証に失敗しました。',
    'check_updates_success' => 'アップデート確認を完了しました。',
    'check_updates_failed' => 'アップデート確認に失敗しました。',
    'update_success' => '言語パックをアップデートしました。',
    'update_failed' => '言語パックのアップデートに失敗しました。',
    'refresh_cache_success' => '言語パックキャッシュを更新しました。',
    'refresh_cache_failed' => '言語パックキャッシュの更新に失敗しました。',
    'preview_success' => 'manifestプレビューを完了しました。',
    'preview_failed' => 'manifestプレビューに失敗しました。',
    'errors' => [
        'manifest_not_found' => 'ZIP内でlanguage-pack.jsonファイルが見つかりません。',
        'manifest_invalid_json' => 'language-pack.json のJSON形式が正しくありません。',
        'php_outside_backend' => 'backend/ディレクトリ外にPHPファイルが含まれています (:file)。',
        'unsafe_php_pattern' => 'PHPファイルに許可されていないコードパターンが含まれています (:file)。',
        'core_locale_missing' => 'コア言語パック(:locale)を先に有効化する必要があります。',
        'target_not_installed' => '対象:scope (:target)がインストールされていません。',
        'target_inactive' => '対象:scope (:target)が無効状態です。先に有効化してください。',
        'target_version_too_old' => '対象:scope (:target)バージョンが要件(:constraint)を満たしていません。',
        'downgrade_blocked' => 'ダウングレードがブロックされました (:from → :to)。',
        'protected_pack' => '保護された言語パックは無効化·削除できません。',
        'download_failed' => 'URL(:url)から言語パックをダウンロードできませんでした。',
        'checksum_mismatch' => 'チェックサムが一致しません。',
        'update_no_source' => 'アップデートソース情報がありません (GitHubソース言語パックのみアップデート可能)。',
        'update_already_latest' => 'すでに最新バージョンです。',
        'preview_invalid_manifest' => 'manifestファイルが無効なためプレビューに失敗しました。',
        'operation_in_progress' => '言語パック(:identifier)で別の処理が進行中です。完了後に再試行してください。',
        'bundled_not_found' => 'バンドルディレクトリ(lang-packs/_bundled/:identifier)が存在しません。',
        'slot_conflict' => '同じスロットにすでにアクティブな言語パック(:current)があります。(:target)に置き換えるには確認が必要です。',
        'directory_not_writable' => '言語パックインストールディレクトリ(:path)への書き込み権限がありません。Webサーバーユーザー(例: www-data)に書き込み権限を付与してください。(例: sudo chgrp www-data :path && sudo chmod g+w :path)',
        'identifier_not_found' => '言語パックが見つかりません (:identifier)。',
        'unsupported_source' => 'サポートされていないソース(:source) — bundled、github、urlのいずれかを使用してください。',
    ],
    'validation' => [
        'file_required' => '言語パックZIPファイルをアップロードしてください。',
        'file_invalid' => 'アップロードされたファイルが有効ではありません。',
        'file_too_large' => 'ファイルサイズは10MBを超えることはできません。',
        'file_not_zip' => 'ZIP形式のファイルのみアップロードできます。',
        'github_url_required' => 'GitHubURLを入力してください。',
        'github_url_invalid' => '正しいURLを入力してください。',
        'github_url_format' => 'GitHubリポジトリURL形式である必要があります (例: https://github.com/owner/repo)。',
        'url_required' => 'ダウンロードURLを入力してください。',
        'url_invalid' => '正しいURLを入力してください。',
        'checksum_invalid' => 'SHA-256チェックサムは64文字の16進数である必要があります。',
        'identifier_required' => '言語パック識別子を入力してください。',
        'identifier_invalid' => '識別子は英数字·ピリオド·アンダースコア·ハイフンのみ許可されます。',
    ],
];
