<?php

return [
    'fetch_success' => 'メニューを正常に取得しました。',
    'fetch_failed' => 'メニューの取得に失敗しました。',
    'active_fetch_failed' => '有効化されたメニューの取得に失敗しました。',
    'create_success' => 'メニューが正常に作成されました。',
    'create_failed' => 'メニューの作成に失敗しました。',
    'create_error' => 'メニュー作成中にエラーが発生しました。',
    'update_success' => 'メニューが正常にアップデートされました。',
    'update_failed' => 'メニューのアップデートに失敗しました。',
    'update_error' => 'メニューアップデート中にエラーが発生しました。',
    'delete_success' => 'メニューが正常に削除されました。',
    'delete_failed' => 'メニューの削除に失敗しました。',
    'delete_error' => 'メニュー削除中にエラーが発生しました。',
    'order_update_success' => 'メニュー順序が正常にアップデートされました。',
    'order_update_failed' => 'メニュー順序のアップデートに失敗しました。',
    'slug_already_exists' => '既に使用中のスラッグです。',
    'parent_menu_not_found' => '存在しない親メニューです。',
    'cannot_set_self_as_parent' => '自分自身を親として設定することはできません。',
    'cannot_delete_menu_with_children' => '子メニューがあるメニューは削除できません。',
    'validation' => [
        'is_active_boolean' => '有効化ステータスはtrue/false値である必要があります。',
        'sort_by_invalid' => '並べ替え基準が有効ではありません。',
        'sort_order_invalid' => '並べ替え順序が有効ではありません。',
        'filters_array' => 'フィルターは配列形式である必要があります。',
        'filters_max' => 'フィルターは最大10個まで指定できます。',
        'filter_field_required' => 'フィルターフィールドは必須です。',
        'filter_field_invalid' => '無効なフィルターフィールドです。',
        'filter_value_required' => 'フィルター値は必須です。',
        'filter_value_max' => 'フィルター値は最大255文字まで入力できます。',
        'filter_operator_invalid' => '無効なフィルター演算子です。',
    ],
];
