<?php

return [
    'not_found' => 'モジュール ":module" が見つかりません。',
    'dependency_not_active' => '依存モジュール ":dependency" がインストールされていないか、無効化されています。',
    'status' => [
        'active' => '有効化',
        'inactive' => '無効化',
        'updating' => 'アップデート中',
    ],
    'commands' => [
        'list' => [
            'headers' => [
                'identifier' => '識別子',
                'name' => '名前',
                'vendor' => 'ベンダー',
                'version' => 'バージョン',
                'status' => 'ステータス',
            ],
            'status' => [
                'active' => '有効化',
                'inactive' => '無効化',
                'uninstalled' => '未インストール',
            ],
            'no_modules' => 'モジュールがありません。',
            'summary' => '合計 :total 個のモジュール (インストール済み: :installed、有効化: :active)',
            'invalid_status' => '無効なステータスです。(installed、uninstalled、active、inactive)',
        ],
        'install' => [
            'success' => 'モジュール ":module" のインストールが完了しました',
            'vendor' => 'ベンダー: :vendor',
            'version' => 'バージョン: :version',
            'roles_created' => ':count 個のロールが作成されました',
            'permissions_created' => ':count 個の権限が作成されました',
            'menus_created' => ':count 個のメニューが作成されました',
            'already_installed' => 'モジュール ":module" は既にインストールされています。',
            'force_reinstall' => 'モジュール ":module" を強制的に再インストールします (アクティブディレクトリを上書き)...',
        ],
        'activate' => [
            'success' => 'モジュール ":module" の有効化が完了しました',
            'not_installed' => 'モジュール ":module" がインストールされていません。',
            'already_active' => 'モジュール ":module" は既に有効化されています。',
            'layouts_registered' => ':count 個のレイアウトが登録されました',
        ],
        'deactivate' => [
            'success' => 'モジュール ":module" の無効化が完了しました',
            'not_installed' => 'モジュール ":module" がインストールされていません。',
            'not_active' => 'モジュール ":module" は有効化されていません。',
            'warning' => 'モジュールのルートと機能が無効化されました。',
            'layouts_deleted' => ':count 個のレイアウトが削除されました',
        ],
        'uninstall' => [
            'success' => 'モジュール ":module" の削除が完了しました',
            'roles_deleted' => ':count 個のロールが削除されました',
            'permissions_deleted' => ':count 個の権限が削除されました',
            'menus_deleted' => ':count 個のメニューが削除されました',
            'layouts_deleted' => ':count 個のレイアウトが削除されました',
            'confirm_prompt' => 'モジュール ":module" を削除してもよろしいですか?',
            'confirm_details' => [
                'roles' => '- :count 個のロールが削除されます。',
                'permissions' => '- :count 個の権限が削除されます。',
                'menus' => '- :count 個のメニューが削除されます。',
                'layouts' => '- :count 個のレイアウトが削除されます。',
                'data' => '- すべてのモジュールデータが削除されます。',
            ],
            'confirm_question' => '本当に削除してもよろしいですか?',
            'aborted' => 'モジュールの削除がキャンセルされました。',
            'not_installed' => 'モジュール ":module" がインストールされていません。',
            'custom_preserved' => '運営者ファイル(:directory)を :archive に保管しました。',
        ],
        'cache_clear' => [
            'clearing_all' => 'すべてのモジュールキャッシュを削除します...',
            'clearing_single' => 'モジュール ":module" のキャッシュを削除します...',
            'success_all' => 'モジュールキャッシュの削除が完了しました (:count 個の項目)',
            'success_single' => 'モジュール ":module" のキャッシュ削除が完了しました (:count 個の項目)',
        ],
        'check_updates' => [
            'not_installed' => 'モジュール ":module" がインストールされていません。',
            'no_installed' => 'インストール済みモジュールがありません。',
            'update_available' => 'アップデート可能',
            'up_to_date' => '最新',
            'headers' => [
                'identifier' => '識別子',
                'current_version' => '現在のバージョン',
                'latest_version' => '最新バージョン',
                'source' => 'ソース',
                'status' => 'ステータス',
            ],
            'summary' => '合計 :total 個を確認 (アップデート可能: :updates 個)',
            'single_up_to_date' => 'モジュール ":module" は最新バージョンです。(v:version)',
            'single_update_available' => 'モジュール ":module" はアップデート可能です: v:current → v:latest (:source)',
        ],
        'update' => [
            'success' => 'モジュール ":module" のアップデートが完了しました',
            'version_change' => 'v:from → v:to',
            'no_update' => 'モジュール ":module" に利用可能なアップデートはありません。',
            'not_installed' => 'モジュール ":module" がインストールされていません。',
            'current_version' => '現在のバージョン: :version',
            'latest_version' => '最新バージョン: :version',
            'update_source' => 'アップデートソース: :source',
            'confirm_question' => 'アップデートを進めてもよろしいですか?',
            'aborted' => 'アップデートがキャンセルされました。',
            'backup_restored' => 'バックアップから以前のバージョンが復元されました。',
            'force_mode' => '強制アップデートモード: バージョン比較をスキップして再インストールします。',
            'layout_strategy' => 'レイアウト戦略: :strategy',
            'modified_extensions_warning' => '管理者が編集したレイアウト拡張 :count 件が上書きされます。',
            'modified_extension_item' => '  - :target (ソース: :source)',
        ],
    ],
    'composer_install' => [
        'start' => 'モジュール ":module" の Composer 依存関係をインストールします...',
        'success' => 'モジュール ":module" の Composer 依存関係のインストールが完了しました',
        'no_dependencies' => 'モジュール ":module" にインストールする Composer 依存関係はありません。',
        'failed' => 'モジュール ":module" の Composer 依存関係のインストールに失敗しました。',
        'summary' => '📊 結果: 成功 :success個、スキップ :skip個、失敗 :fail個',
    ],
    'update_success' => 'モジュール ":module"が :version バージョンにアップデートされました。',
    'update_failed' => 'モジュールのアップデートに失敗しました: :error',
    'update_hook_failed' => 'モジュールアップデートフック実行に失敗しました: :error',
    'no_update_available' => 'アップデートする内容がありません。',
    'check_updates_success' => 'アップデート確認が完了しました。',
    'check_updates_failed' => 'アップデート確認に失敗しました: :error',
    'check_modified_layouts_success' => '変更されたレイアウト確認が完了しました。',
    'check_modified_layouts_failed' => '変更されたレイアウト確認に失敗しました: :error',
    'not_installed' => 'モジュール ":module"はインストールされていません。',
    'pending_not_found' => 'インストール待機リストでモジュール ":module"が見つかりません。',
    'already_exists' => 'モジュール ":module"は既に存在します。',
    'move_failed' => 'モジュール ":module"の移動に失敗しました: :error',
    'deactivate_warning' => 'このモジュールに依存するアクティブなテンプレートがあります。',
    'installation_failed' => 'モジュールのインストールに失敗しました: :error',
    'activation_failed' => 'モジュールの有効化に失敗しました: :error',
    'deactivation_failed' => 'モジュールの無効化に失敗しました: :error',
    'uninstallation_failed' => 'モジュールの削除に失敗しました: :error',
    'refresh_layouts_failed' => 'レイアウト更新に失敗しました: :error',
    'warnings' => [
        'has_dependent_templates' => 'このモジュールに依存する有効化されたテンプレートがあります。無効化するには強制オプションを使用してください。',
        'has_dependents' => 'このモジュールに依存する有効化された拡張があります。',
        'deactivation_warning' => '無効化すると、次のテンプレートが影響を受けます:',
        'confirm_deactivation' => 'それでも無効化しますか?',
        'missing_dependencies' => 'このモジュールを有効化するには、次の依存関係が必要です。',
    ],
    'activate_warning' => 'モジュール有効化に必要な依存関係が満たされていません。',
    'deactivate_warning_extended' => 'このモジュールに依存する有効化された拡張 (テンプレート、モジュール、プラグイン) があります。',
    'errors' => [
        'force_update_no_source' => ':module を強制アップデートするソースが見つかりません。バンドルと GitHub URL の両方がありません。',
        'downgrade_blocked' => 'ダウングレードがブロックされました (:from → :to)。意図的なダウングレードは --force オプションを使用してください。',
        'zip_open_failed' => 'ZIP ファイルを開くことができません: :error',
        'module_json_not_found' => 'module.json ファイルが見つかりません。',
        'module_json_invalid' => 'module.json ファイル形式が正しくありません。',
        'identifier_missing' => 'モジュール識別子がありません。',
        'already_installed' => '既にインストールされているモジュールです。',
        'install_failed' => 'モジュールのインストールに失敗しました: :error',
        'github_url_invalid' => '無効な GitHub URL 形式です。',
        'github_download_failed' => 'GitHub からのダウンロードに失敗しました: :error',
        'github_repo_not_found' => 'GitHub リポジトリが見つかりません。',
        'module_not_found' => 'モジュール :name が見つかりません。',
        'module_not_active' => 'モジュール :name は有効化されていません。',
        'not_found' => 'モジュール :module が見つかりません。',
        'file_not_found' => 'ファイルが見つかりません。',
        'file_type_not_allowed' => '許可されていないファイル形式です。',
        'unknown_error' => '不明なエラーが発生しました。',
        'invalid_permission_structure' => 'モジュール ":identifier"の権限構造が正しくありません: :reason',
        'invalid_translation_path' => 'モジュール ":identifier"の言語ファイルパスが正しくありません。":wrong_path" の代わりに ":correct_path"を使用する必要があります。',
        'seo_variable_conflict' => 'モジュール ":identifier"の SEO 変数名が既存の拡張と競合しています: :reason',
        'layout_validation_json_error' => 'レイアウトファイル :file の JSON パースに失敗しました: :error',
        'layout_validation_missing_name' => 'レイアウトファイル :file に layout_name がありません。',
        'layout_validation_partial_error' => 'レイアウトファイル :file の partial 処理に失敗しました: :error (partial: :partial)',
        'layout_validation_validation_failed' => 'モジュール :identifier のレイアウト検証に失敗しました。:count 個のエラーが見つかりました: :error',
        'operation_in_progress' => 'モジュール ":name"は現在 :status 状態です。処理が完了するまでお待ちください。',
        'github_api_failed' => 'GitHub API 呼び出しに失敗しました: :error',
        'invalid_github_url' => '無効な GitHub URL です。',
        'zip_url_not_found' => 'ZIP ダウンロード URL が見つかりません。',
        'download_failed' => 'モジュール ":module" :version バージョンのダウンロードに失敗しました: :error',
        'zip_extract_failed' => 'ZIP 解凍に失敗しました: :error',
        'extracted_dir_not_found' => '解凍されたディレクトリが見つかりません。',
        'reload_failed' => 'モジュールの再読み込みに失敗しました: :error',
        'delete_directory_failed' => 'モジュールディレクトリの削除に失敗しました: :error',
        'update_failed' => 'モジュール ":module"のアップデートに失敗しました: :error',
        'invalid_layout_strategy' => '無効なレイアウト戦略です。(overwrite または keep のみ許可)',
        'invalid_vendor_mode' => '無効な Vendor インストールモードです。(auto、composer、bundled のみ許可)',
    ],
    'validation' => [
        'name_required' => 'モジュール名は必須です。',
        'name_string' => 'モジュール名は文字列である必要があります。',
        'name_max' => 'モジュール名は 255 文字を超えることができません。',
        'search_max' => '検索語は 255 文字を超えることができません。',
        'filters_max' => '検索条件は最大 10 個までのみ指定できます。',
        'filter_field_required' => '検索フィールドは必須です。',
        'filter_field_invalid' => '無効な検索フィールドです。',
        'filter_value_required' => '検索値は必須です。',
        'filter_value_max' => '検索値は 255 文字を超えることができません。',
        'filter_operator_invalid' => '無効な検索演算子です。',
        'status_invalid' => '無効な状態です。',
        'per_page_min' => '1 ページあたりの項目数は最小 1 個です。',
        'per_page_max' => '1 ページあたりの項目数は最大 100 個です。',
        'page_min' => 'ページ番号は最小 1 です。',
        'file_required' => 'モジュールファイルは必須です。',
        'file_invalid' => '有効なファイルではありません。',
        'file_must_be_zip' => 'モジュールファイルは ZIP 形式である必要があります。',
        'file_max_size' => 'モジュールファイルサイズは :sizeMB を超えることができません。',
        'github_url_required' => 'GitHub URLは必須です。',
        'github_url_invalid' => '有効なURL形式ではありません。',
        'github_url_format' => 'GitHub リポジトリURL形式が正しくありません。',
        'with_max' => 'with パラメータは最大10個まで指定できます。',
        'with_invalid' => '有効でないwith 関係です。',
    ],
];
