<?php

return [
    'not_found' => 'モジュール ":module" が見つかりません。',
    'dependency_not_active' => '依存モジュール ":dependency" がインストールされていないか、無効化されています。',
    'status' => [
        'active' => '有効化',
        'inactive' => '無効化',
        'updating' => 'アップデート中',
    ],
    'commands' => [
        'list' => [
            'headers' => [
                'identifier' => '識別子',
                'name' => '名前',
                'vendor' => 'ベンダー',
                'version' => 'バージョン',
                'status' => 'ステータス',
            ],
            'status' => [
                'active' => '有効化',
                'inactive' => '無効化',
                'uninstalled' => '未インストール',
            ],
            'no_modules' => 'モジュールがありません。',
            'summary' => '合計 :total個 モジュール (インストール済み: :installed、有効化: :active)',
            'invalid_status' => '無効なステータスです。(installed、uninstalled、active、inactive)',
        ],
        'install' => [
            'success' => 'モジュール ":module" インストール完了',
            'vendor' => 'ベンダー: :vendor',
            'version' => 'バージョン: :version',
            'roles_created' => ':count個 ロール 作成されました',
            'permissions_created' => ':count個 権限 作成されました',
            'menus_created' => ':count個 メニュー 作成されました',
            'already_installed' => 'モジュール ":module" は既にインストールされています。',
            'force_reinstall' => 'モジュール ":module" を強制的に再インストールします (アクティブディレクトリを上書き)...',
        ],
        'activate' => [
            'success' => 'モジュール ":module" 有効化完了',
            'not_installed' => 'モジュール ":module" はインストールされていません。',
            'already_active' => 'モジュール ":module" は既に有効化されています。',
            'layouts_registered' => ':count個 レイアウト 登録されました',
        ],
        'deactivate' => [
            'success' => 'モジュール ":module" 無効化完了',
            'not_installed' => 'モジュール ":module" はインストールされていません。',
            'not_active' => 'モジュール ":module" は有効化されていません。',
            'warning' => 'モジュールのルートと機能が無効化されました。',
            'layouts_deleted' => ':count個 レイアウト 削除されました',
        ],
        'uninstall' => [
            'success' => 'モジュール ":module" 削除完了',
            'roles_deleted' => ':count個 ロール 削除されました',
            'permissions_deleted' => ':count個 権限 削除されました',
            'menus_deleted' => ':count個 メニュー 削除されました',
            'layouts_deleted' => ':count個 レイアウト 削除されました',
            'confirm_prompt' => 'モジュール ":module" を削除しますか?',
            'confirm_details' => [
                'roles' => '- :count個 のロールが削除されます。',
                'permissions' => '- :count個 の権限が削除されます。',
                'menus' => '- :count個 のメニューが削除されます。',
                'layouts' => '- :count個 のレイアウトが削除されます。',
                'data' => '- すべてのモジュールデータが削除されます。',
            ],
            'confirm_question' => '本当に削除しますか?',
            'aborted' => 'モジュール削除がキャンセルされました。',
            'not_installed' => 'モジュール ":module" はインストールされていません。',
        ],
        'cache_clear' => [
            'clearing_all' => 'すべてのモジュールキャッシュを削除します...',
            'clearing_single' => 'モジュール ":module" キャッシュを削除します...',
            'success_all' => 'モジュールキャッシュ削除完了 (:count個 項目)',
            'success_single' => 'モジュール ":module" キャッシュ削除完了 (:count個 項目)',
        ],
        'check_updates' => [
            'not_installed' => 'モジュール ":module" はインストールされていません。',
            'no_installed' => 'インストール済みモジュールがありません。',
            'update_available' => 'アップデート可能',
            'up_to_date' => '最新',
            'headers' => [
                'identifier' => '識別子',
                'current_version' => '現在のバージョン',
                'latest_version' => '最新バージョン',
                'source' => 'ソース',
                'status' => 'ステータス',
            ],
            'summary' => '合計 :total個 確認 (アップデート可能: :updates個)',
            'single_up_to_date' => 'モジュール ":module" は最新バージョンです。(v:version)',
            'single_update_available' => 'モジュール ":module" アップデート可能: v:current → v:latest (:source)',
        ],
        'update' => [
            'success' => 'モジュール ":module" アップデート完了',
            'version_change' => 'v:from → v:to',
            'no_update' => 'モジュール ":module" に利用可能なアップデートはありません。',
            'not_installed' => 'モジュール ":module" はインストールされていません。',
            'current_version' => '現在のバージョン: :version',
            'latest_version' => '最新バージョン: :version',
            'update_source' => 'アップデートソース: :source',
            'confirm_question' => 'アップデートを実行しますか?',
            'aborted' => 'アップデートがキャンセルされました。',
            'backup_restored' => 'バックアップから以前のバージョンが復元されました。',
            'force_mode' => '強制アップデートモード: バージョン比較をスキップして再インストールします。',
        ],
    ],
    'composer_install' => [
        'start' => 'モジュール ":module" の Composer 依存関係をインストールします...',
        'success' => 'モジュール ":module" の Composer 依存関係 インストール完了',
        'no_dependencies' => 'モジュール ":module" にインストールする Composer 依存関係はありません。',
        'failed' => 'モジュール ":module" の Composer 依存関係 インストールに失敗しました。',
        'summary' => '📊 結果: 成功 :success個、スキップ :skip個、失敗 :fail個',
    ],
    'update_success' => 'モジュール ":module" が :version バージョンにアップデートされました。',
    'update_failed' => 'モジュールアップデートに失敗しました: :error',
    'update_hook_failed' => 'モジュール アップデート フック実行に失敗しました。',
    'no_update_available' => 'アップデートする内容がありません。',
    'check_updates_success' => 'アップデート確認が完了しました。',
    'check_updates_failed' => 'アップデート確認に失敗しました。',
    'check_modified_layouts_success' => '修正されたレイアウト確認が完了しました。',
    'check_modified_layouts_failed' => '修正されたレイアウト確認に失敗しました: :error',
    'not_installed' => 'モジュール":module"はインストールされていません。',
    'pending_not_found' => 'インストール待ちリストでモジュール":module"が見つかりません。',
    'already_exists' => 'モジュール":module"は既に存在します。',
    'move_failed' => 'モジュール":module"の移動に失敗しました。',
    'deactivate_warning' => 'このモジュールに依存する有効なテンプレートがあります。',
    'installation_failed' => 'モジュール インストールに失敗しました: :error',
    'activation_failed' => 'モジュール 有効化に失敗しました: :error',
    'deactivation_failed' => 'モジュール 無効化に失敗しました: :error',
    'uninstallation_failed' => 'モジュール 削除に失敗しました: :error',
    'refresh_layouts_failed' => 'レイアウト 更新に失敗しました: :error',
    'warnings' => [
        'has_dependent_templates' => 'このモジュールに依存する有効化されたテンプレートがあります。無効化するには強制オプションを使用してください。',
        'has_dependents' => 'このモジュールに依存する有効化された拡張があります。',
        'deactivation_warning' => '無効化すると次のテンプレートが影響を受けます:',
        'confirm_deactivation' => 'それでも無効化しますか?',
        'missing_dependencies' => 'このモジュールを有効化するには次の依存性が必要です。',
    ],
    'activate_warning' => 'モジュール 有効化に必要な依存性が満たされていません。',
    'deactivate_warning_extended' => 'このモジュールに依存する有効化された拡張(テンプレート、モジュール、プラグイン)があります。',
    'errors' => [
        'force_update_no_source' => ':moduleを強制アップデートするソースが見つかりません。バンドルおよびGitHub URLの両方がありません。',
        'downgrade_blocked' => 'ダウングレードがブロックされました(:from → :to)。意図的なダウングレードは--forceオプションを使用してください。',
        'zip_open_failed' => 'ZIPファイルを開くことができません。',
        'module_json_not_found' => 'module.jsonファイルが見つかりません。',
        'module_json_invalid' => 'module.jsonファイル形式が正しくありません。',
        'identifier_missing' => 'モジュール識別子が不足しています。',
        'already_installed' => '既にインストールされているモジュールです。',
        'install_failed' => 'モジュール インストールに失敗しました。',
        'github_url_invalid' => '無効なGitHub URLの形式です。',
        'github_download_failed' => 'GitHubからのダウンロードに失敗しました。',
        'github_repo_not_found' => 'GitHub リポジトリが見つかりません。',
        'module_not_found' => 'モジュール:nameが見つかりません。',
        'module_not_active' => 'モジュール:nameは有効化されていません。',
        'not_found' => 'モジュール:moduleが見つかりません。',
        'file_not_found' => 'ファイルが見つかりません。',
        'file_type_not_allowed' => '許可されていないファイル形式です。',
        'unknown_error' => '不明なエラーが発生しました。',
        'invalid_permission_structure' => 'モジュール":identifier"の権限構造が正しくありません: :reason',
        'invalid_translation_path' => 'モジュール":identifier"の言語パック ファイルパスが正しくありません。":wrong_path"の代わりに":correct_path"を使用する必要があります。',
        'seo_variable_conflict' => 'モジュール":identifier"のSEO変数名が既存の拡張と競合します: :reason',
        'layout_validation_json_error' => 'レイアウト ファイル:fileのJSON解析に失敗しました: :error',
        'layout_validation_missing_name' => 'レイアウト ファイル:fileにlayout_nameが不足しています。',
        'layout_validation_partial_error' => 'レイアウト ファイル:fileのpartial処理に失敗しました: :error (partial: :partial)',
        'layout_validation_validation_failed' => 'モジュール:identifierのレイアウト バリデーションに失敗しました。:count個のエラーが見つかりました。',
        'operation_in_progress' => 'モジュール":name"は現在:statusの状態です。処理が完了するまでお待ちください。',
        'github_api_failed' => 'GitHub API呼び出しに失敗しました。',
        'invalid_github_url' => '無効なGitHub URLです。',
        'zip_url_not_found' => 'ZIPダウンロード URLが見つかりません。',
        'download_failed' => 'モジュール":module":versionバージョンのダウンロードに失敗しました。',
        'zip_extract_failed' => 'ZIP展開に失敗しました。',
        'extracted_dir_not_found' => '展開されたディレクトリが見つかりません。',
        'reload_failed' => 'モジュール 再ロードに失敗しました。',
        'delete_directory_failed' => 'モジュール ディレクトリの削除に失敗しました。',
        'update_failed' => 'モジュール":module"のアップデートに失敗しました: :error',
        'invalid_layout_strategy' => '無効なレイアウト戦略です。(overwriteまたはkeepのみ許可)',
        'invalid_vendor_mode' => '無効なVendor インストール モードです。(auto、composer、bundledのみ許可)',
    ],
    'validation' => [
        'name_required' => 'モジュール名は必須です。',
        'name_string' => 'モジュール名は文字列である必要があります。',
        'name_max' => 'モジュール名は255字を超えることはできません。',
        'search_max' => '検索語は255字を超えることはできません。',
        'filters_max' => '検索条件は最大10個までのみ指定できます。',
        'filter_field_required' => '検索フィールドは必須です。',
        'filter_field_invalid' => '無効な検索フィールドです。',
        'filter_value_required' => '検索値は必須です。',
        'filter_value_max' => '検索値は255字を超えることはできません。',
        'filter_operator_invalid' => '無効な検索演算子です。',
        'status_invalid' => '無効なステータスです。',
        'per_page_min' => 'ページあたりの項目数は最小1です。',
        'per_page_max' => 'ページあたりの項目数は最大100です。',
        'page_min' => 'ページ番号は最小1です。',
        'file_required' => 'モジュール ファイルは必須です。',
        'file_invalid' => '有効なファイルではありません。',
        'file_must_be_zip' => 'モジュール ファイルはZIP形式である必要があります。',
        'file_max_size' => 'モジュール ファイル サイズは:sizeMBを超えることはできません。',
        'github_url_required' => 'GitHub URLは必須です。',
        'github_url_invalid' => '有効なURL形式ではありません。',
        'github_url_format' => 'GitHub リポジトリURL形式が正しくありません。',
        'with_max' => 'withパラメータは最大10個まで指定できます。',
        'with_invalid' => '無効なwith関係です。',
    ],
];
