<?php

return [
    'not_found' => 'モジュール :module が見つかりません。',
    'dependency_not_active' => '依存関係モジュール :dependency がインストールされていないか、有効化されていません。',
    'fetch_success' => 'モジュールを正常にインポートしました。',
    'fetch_failed' => 'モジュールのインポートに失敗しました。',
    'install_success' => 'モジュールが正常にインストールされました。',
    'install_failed' => 'モジュールのインストールに失敗しました。',
    'preview_success' => 'マニフェストのプレビューが完了しました。',
    'preview_failed' => 'マニフェストのプレビューに失敗しました。',
    'uninstall_success' => 'モジュールが正常に削除されました。',
    'uninstall_failed' => 'モジュールの削除に失敗しました。',
    'activate_success' => 'モジュールが正常に有効化されました。',
    'activate_failed' => 'モジュールの有効化に失敗しました。',
    'deactivate_success' => 'モジュールが正常に無効化されました。',
    'deactivate_failed' => 'モジュールの無効化に失敗しました。',
    'update_success' => 'モジュールが正常にアップデートされました。',
    'update_failed' => 'モジュールのアップデートに失敗しました。',
    'refresh_layouts_success' => 'モジュールレイアウトが正常に更新されました。',
    'refresh_layouts_failed' => 'モジュールレイアウトの更新に失敗しました。',
    'uninstall_info_success' => 'モジュール削除情報を正常に取得しました。',
    'uninstall_info_failed' => 'モジュール削除情報の取得に失敗しました。',
    'license_not_found' => 'モジュールライセンスファイルが見つかりません。',
    'status' => [
        'active' => '有効',
        'inactive' => '無効',
        'installing' => 'インストール中',
        'uninstalling' => '削除中',
    ],
    'errors' => [
        'module_class_not_found' => 'モジュールクラスが見つかりません。',
        'migration_failed' => 'マイグレーション実行に失敗しました。',
        'dependency_check_failed' => '依存関係の確認に失敗しました。',
        'database_error' => 'データベースエラーが発生しました。',
        'module_not_found' => 'モジュール :name が見つかりません。',
        'module_not_active' => 'モジュール :name は有効化されていません。',
    ],
    'dependent_templates_success' => '依存テンプレート情報を正常に取得しました。',
    'dependent_templates_failed' => '依存テンプレート情報の取得に失敗しました: :error',
];
