<?php

return [
    'definition_list_success' => '通知定義リストを取得しました。',
    'definition_list_failed' => '通知定義リストの取得に失敗しました。',
    'definition_show_success' => '通知定義を取得しました。',
    'definition_show_failed' => '通知定義の取得に失敗しました。',
    'definition_updated' => '通知定義が編集されました。',
    'definition_update_failed' => '通知定義の編集に失敗しました。',
    'definition_toggled' => '通知定義の有効状態が変更されました。',
    'definition_toggle_failed' => '通知定義の有効状態変更に失敗しました。',
    'definition_not_found' => '通知定義が見つかりません。',
    'definition_reset' => '通知定義のすべてのテンプレートがデフォルト値に復元されました。',
    'definition_reset_failed' => '通知定義の初期化に失敗しました。',
    'channel_skipped_no_template' => ':channel チャネルに :type タイプのアクティブテンプレートがないため、送信をスキップしました。',
    'channel_disabled_by_extension' => '拡張環境設定でそのチャネルが無効化されているため、送信をスキップしました。',
    'channel_guest_not_allowed' => 'そのチャネルは非会員送信を許可していないため、送信をスキップしました。',
    'template_updated' => '通知テンプレートが編集されました。',
    'template_update_failed' => '通知テンプレートの編集に失敗しました。',
    'template_toggled' => '通知テンプレートの有効状態が変更されました。',
    'template_toggle_failed' => '通知テンプレートの有効状態変更に失敗しました。',
    'template_reset' => '通知テンプレートがデフォルト値に復元されました。',
    'template_reset_failed' => '通知テンプレートのデフォルト値復元に失敗しました。',
    'template_inactive' => '該当チャネルの通知テンプレートは無効状態です。',
    'template_not_found' => '該当チャネルの通知テンプレートが見つかりません。',
    'default_data_not_found' => 'デフォルトテンプレートデータが見つかりません。',
    'preview_success' => 'プレビューを作成しました。',
    'preview_failed' => 'プレビューの作成に失敗しました。',
    'channels_success' => '通知チャネルリストを取得しました。',
    'channels_failed' => '通知チャネルリストの取得に失敗しました。',
    'definition' => '通知定義',
    'subject' => '件名',
    'body' => '本文',
    'readiness' => [
        'mail_from_address_not_configured' => '送信者メールアドレスが設定されていません。',
        'mail_smtp_host_empty' => 'SMTP ホストが設定されていません。',
        'mail_smtp_port_empty' => 'SMTP ポートが設定されていません。',
        'mail_mailgun_domain_empty' => 'Mailgun ドメインが設定されていません。',
        'mail_mailgun_secret_empty' => 'Mailgun シークレットが設定されていません。',
        'mail_ses_key_empty' => 'SES キーが設定されていません。',
        'mail_ses_secret_empty' => 'SES シークレットが設定されていません。',
        'database_table_missing' => '通知テーブルが存在しません。',
        'unknown' => 'チャネル設定が完了していません。',
    ],
    'user' => [
        'list_success' => '通知リストを取得しました。',
        'list_failed' => '通知リストの取得に失敗しました。',
        'unread_count_success' => '未読通知数を取得しました。',
        'unread_count_failed' => '未読通知数の取得に失敗しました。',
        'read_success' => '通知を既読にしました。',
        'read_failed' => '通知の既読処理に失敗しました。',
        'read_all_success' => 'すべての通知を既読にしました。',
        'read_all_failed' => '全件既読処理に失敗しました。',
        'delete_success' => '通知が削除されました。',
        'delete_failed' => '通知の削除に失敗しました。',
        'delete_all_success' => 'すべての通知が削除されました。',
        'delete_all_failed' => '全件通知削除に失敗しました。',
        'not_found' => '通知が見つかりません。',
    ],
    'channels' => [
        'core_default' => 'コアデフォルトチャネル',
        'mail' => [
            'name' => 'メール',
            'description' => 'メールで通知を送信',
        ],
        'database' => [
            'name' => 'サイト内通知',
            'description' => 'サイト内通知センターに表示',
        ],
    ],
];
