<?php

return [
    'definition_list_success' => '通知定義一覧を取得しました。',
    'definition_list_failed' => '通知定義一覧の取得に失敗しました。',
    'definition_show_success' => '通知定義を取得しました。',
    'definition_show_failed' => '通知定義の取得に失敗しました。',
    'definition_updated' => '通知定義が編集されました。',
    'definition_update_failed' => '通知定義の編集に失敗しました。',
    'definition_toggled' => '通知定義のアクティブ状態が変更されました。',
    'definition_toggle_failed' => '通知定義のアクティブ状態の変更に失敗しました。',
    'definition_not_found' => '通知定義が見つかりません。',
    'definition_reset' => '通知定義のすべてのテンプレートがデフォルト値に復元されました。',
    'definition_reset_failed' => '通知定義の初期化に失敗しました。',
    'channel_skipped_no_template' => ':channel チャネルに :type タイプのアクティブなテンプレートがないため、配信をスキップしました。',
    'channel_disabled_by_extension' => '拡張設定でそのチャネルが無効化されているため、配信をスキップしました。',
    'template_updated' => '通知テンプレートが編集されました。',
    'template_update_failed' => '通知テンプレートの編集に失敗しました。',
    'template_toggled' => '通知テンプレートのアクティブ状態が変更されました。',
    'template_toggle_failed' => '通知テンプレートのアクティブ状態の変更に失敗しました。',
    'template_reset' => '通知テンプレートがデフォルト値に復元されました。',
    'template_reset_failed' => '通知テンプレートのデフォルト値復元に失敗しました。',
    'template_inactive' => '該当チャネルの通知テンプレートは無効化状態です。',
    'template_not_found' => '該当チャネルの通知テンプレートが見つかりません。',
    'default_data_not_found' => 'デフォルトテンプレートデータが見つかりません。',
    'preview_success' => 'プレビューを生成しました。',
    'preview_failed' => 'プレビューの生成に失敗しました。',
    'channels_success' => '通知チャネル一覧を取得しました。',
    'channels_failed' => '通知チャネル一覧の取得に失敗しました。',
    'definition' => '通知定義',
    'subject' => '件名',
    'body' => '本文',
    'readiness' => [
        'mail_from_address_not_configured' => '送信者メールアドレスが設定されていません。',
        'mail_smtp_host_empty' => 'SMTPホストが設定されていません。',
        'mail_smtp_port_empty' => 'SMTPポートが設定されていません。',
        'mail_mailgun_domain_empty' => 'Mailgunドメインが設定されていません。',
        'mail_mailgun_secret_empty' => 'Mailgunシークレットが設定されていません。',
        'mail_ses_key_empty' => 'SESキーが設定されていません。',
        'mail_ses_secret_empty' => 'SESシークレットが設定されていません。',
        'database_table_missing' => '通知テーブルが存在しません。',
        'unknown' => 'チャネル設定が完了していません。',
    ],
    'user' => [
        'list_success' => '通知一覧を取得しました。',
        'list_failed' => '通知一覧の取得に失敗しました。',
        'unread_count_success' => '未読通知数を取得しました。',
        'unread_count_failed' => '未読通知数の取得に失敗しました。',
        'read_success' => '通知を既読にしました。',
        'read_failed' => '通知の既読処理に失敗しました。',
        'read_all_success' => 'すべての通知を既読にしました。',
        'read_all_failed' => '全件既読処理に失敗しました。',
        'delete_success' => '通知が削除されました。',
        'delete_failed' => '通知の削除に失敗しました。',
        'delete_all_success' => 'すべての通知が削除されました。',
        'delete_all_failed' => '全件削除に失敗しました。',
        'not_found' => '通知が見つかりません。',
    ],

    // 通知チャネルメタデータ (config/notification.php default_channels が参照)
    'channels' => [
        'core_default' => 'コアの基本チャネル',
        'mail' => [
            'name' => 'メール',
            'description' => 'メールで通知を送信',
        ],
        'database' => [
            'name' => 'サイト内通知',
            'description' => 'サイト内の通知センターに表示',
        ],
    ],
];
