<?php

return [
    'list_success' => 'プラグインリストの取得に成功しました。',
    'list_failed' => 'プラグインリストの取得に失敗しました。',
    'fetch_success' => 'プラグイン情報の取得に成功しました。',
    'fetch_failed' => 'プラグイン情報の取得に失敗しました。',
    'not_found' => 'プラグイン :plugin が見つかりません。',
    'install_success' => 'プラグインが正常にインストールされました。',
    'install_failed' => 'プラグインのインストールに失敗しました。',
    'preview_success' => 'マニフェストプレビューが完了しました。',
    'preview_failed' => 'マニフェストプレビューに失敗しました。',
    'install_validation_failed' => 'プラグインのインストール検証に失敗しました。',
    'install_error' => 'プラグインのインストール中にエラーが発生しました。',
    'uninstall_success' => 'プラグインが正常に削除されました。',
    'uninstall_failed' => 'プラグインの削除に失敗しました。',
    'uninstall_validation_failed' => 'プラグインの削除検証に失敗しました。',
    'uninstall_error' => 'プラグインの削除中にエラーが発生しました。',
    'activate_success' => 'プラグインが正常に有効化されました。',
    'activate_failed' => 'プラグインの有効化に失敗しました。',
    'activate_validation_failed' => 'プラグインの有効化検証に失敗しました。',
    'activate_error' => 'プラグインの有効化中にエラーが発生しました。',
    'deactivate_success' => 'プラグインが正常に無効化されました。',
    'deactivate_failed' => 'プラグインの無効化に失敗しました。',
    'deactivate_validation_failed' => 'プラグインの無効化検証に失敗しました。',
    'deactivate_error' => 'プラグインの無効化中にエラーが発生しました。',
    'refresh_layouts_success' => 'プラグインレイアウトが正常に更新されました。',
    'refresh_layouts_failed' => 'プラグインレイアウトの更新に失敗しました: :error',
    'uninstall_info_success' => 'プラグイン削除情報の閲覧に成功しました。',
    'uninstall_info_failed' => 'プラグイン削除情報の閲覧に失敗しました。',
    'license_not_found' => 'プラグインライセンスファイルが見つかりません。',
    'refresh_layouts_validation_failed' => 'プラグインレイアウト更新検証に失敗しました。',
    'refresh_layouts_error' => 'プラグインレイアウトの更新中にエラーが発生しました。',
    'status' => [
        'active' => '有効',
        'inactive' => '無効',
        'updating' => 'アップデート中',
    ],
    'update_success' => 'プラグイン ":plugin" は :version にアップデートされました。',
    'update_failed' => 'プラグインのアップデートに失敗しました: :error',
    'update_hook_failed' => 'プラグイン更新フックの実行に失敗しました。',
    'no_update_available' => '更新する内容がありません。',
    'check_updates_success' => '更新確認が完了しました。',
    'check_updates_failed' => '更新確認に失敗しました。',
    'check_modified_layouts_success' => '変更されたレイアウト確認が完了しました。',
    'check_modified_layouts_failed' => '変更されたレイアウト確認に失敗しました: :error',
    'not_installed' => 'プラグイン ":plugin" はインストールされていません。',
    'pending_not_found' => 'インストール待機リストにプラグイン ":plugin" が見つかりません。',
    'already_exists' => 'プラグイン ":plugin" は既に存在します。',
    'move_failed' => 'プラグイン ":plugin" の移動に失敗しました。',
    'dependency_not_active' => '依存関係 ":dependency" がインストールされていないか、無効化されています。',
    'installation_failed' => 'プラグインのインストールに失敗しました: :error',
    'activation_failed' => 'プラグインの有効化に失敗しました: :error',
    'deactivation_failed' => 'プラグインの無効化に失敗しました: :error',
    'uninstallation_failed' => 'プラグインの削除に失敗しました: :error',
    'warnings' => [
        'has_dependent_templates' => 'このプラグインに依存する有効なテンプレートがあります。無効化するには強制オプションを使用してください。',
        'has_dependents' => 'このプラグインに依存する有効な拡張があります。',
        'deactivation_warning' => '無効化すると、次のテンプレートが影響を受けます:',
        'confirm_deactivation' => 'それでも無効化しますか?',
        'missing_dependencies' => 'このプラグインを有効化するには、次の依存関係が必要です。',
    ],
    'activate_warning' => 'プラグインの有効化に必要な依存関係が満たされていません。',
    'deactivate_warning' => 'このプラグインに依存する有効な拡張があります。',
    'deactivate_warning_extended' => 'このプラグインに依存する有効な拡張(テンプレート、モジュール、プラグイン)があります。',
    'errors' => [
        'force_update_no_source' => ':plugin を強制アップデートするソースが見つかりません。バンドルとGitHub URLがどちらもありません。',
        'downgrade_blocked' => 'ダウングレードはブロックされています (:from → :to)。意図的なダウングレードの場合は --force オプションを使用してください。',
        'invalid_permission_structure' => 'プラグイン ":identifier" の権限構造が正しくありません: :reason',
        'invalid_translation_path' => 'プラグイン ":identifier" の言語ファイルパスが正しくありません。":wrong_path" の代わりに ":correct_path" を使用する必要があります。',
        'seo_variable_conflict' => 'プラグイン ":identifier" のSEO変数名が既存の拡張と競合しています: :reason',
        'plugin_not_found' => 'プラグイン ":name" が見つかりません。',
        'plugin_not_active' => 'プラグイン ":name" は有効化されていません。',
        'not_found' => 'プラグイン :plugin が見つかりません。',
        'file_not_found' => 'ファイルが見つかりません。',
        'file_type_not_allowed' => '許可されていないファイル形式です。',
        'unknown_error' => '不明なエラーが発生しました。',
        'layout_validation_json_error' => 'レイアウトファイル :file のJSON解析に失敗しました: :error',
        'layout_validation_missing_name' => 'レイアウトファイル :file に layout_name が不足しています。',
        'layout_validation_partial_error' => 'レイアウトファイル :file の部分テンプレート処理に失敗しました: :error (partial: :partial)',
        'layout_validation_validation_failed' => 'プラグイン :identifier のレイアウト検証に失敗しました。:count 個のエラーが見つかりました。',
        'operation_in_progress' => 'プラグイン ":name" は現在 :status 状態です。作業が完了するまで待ってください。',
        'github_api_failed' => 'GitHub API呼び出しに失敗しました。',
        'invalid_github_url' => '無効なGitHub URLです。',
        'zip_url_not_found' => 'ZIPダウンロードURLが見つかりません。',
        'download_failed' => 'プラグイン ":plugin" :version バージョンのダウンロードに失敗しました。',
        'zip_extract_failed' => 'ZIP解凍に失敗しました。',
        'extracted_dir_not_found' => '解凍されたディレクトリが見つかりません。',
        'reload_failed' => 'プラグインの再読み込みに失敗しました。',
        'delete_directory_failed' => 'プラグインディレクトリの削除に失敗しました。',
        'update_failed' => 'プラグイン ":plugin" のアップデートに失敗しました: :error',
        'invalid_layout_strategy' => '無効なレイアウト戦略です。(overwrite または keep のみ許可)',
        'invalid_vendor_mode' => '無効な Vendor インストールモードです。(auto、composer、bundled のみ許可)',
        'github_url_invalid' => '無効な GitHub URL 形式です。',
        'github_download_failed' => 'GitHub からのダウンロードに失敗しました。',
        'github_repo_not_found' => 'GitHub リポジトリが見つかりません。',
        'zip_open_failed' => 'ZIP ファイルを開くことができません。',
        'plugin_json_not_found' => 'plugin.json ファイルが見つかりません。',
        'plugin_json_invalid' => 'plugin.json ファイル形式が正しくありません。',
        'identifier_missing' => 'プラグイン識別子が見つかりません。',
        'already_installed' => 'プラグイン ":plugin" は既にインストールされています。',
        'install_failed' => 'プラグインのインストールに失敗しました。',
    ],
    'validation' => [
        'plugin_name_required' => 'プラグイン名は必須です。',
        'plugin_name_string' => 'プラグイン名は文字列である必要があります。',
        'plugin_name_max' => 'プラグイン名は最大 :max 文字まで入力できます。',
        'name_required' => 'プラグイン名は必須です。',
        'name_string' => 'プラグイン名は文字列である必要があります。',
        'name_max' => 'プラグイン名は最大 255 文字まで入力できます。',
        'search_max' => '検索キーワードは最大 255 文字まで入力できます。',
        'filters_max' => '検索条件は最大 10 個まで設定できます。',
        'filter_field_required' => '検索フィールドは必須です。',
        'filter_field_invalid' => '無効な検索フィールドです。',
        'filter_value_required' => '検索値は必須です。',
        'filter_value_max' => '検索値は最大 255 文字まで入力できます。',
        'filter_operator_invalid' => '無効な検索演算子です。',
        'status_invalid' => '無効なステータス値です。',
        'per_page_min' => 'ページあたりの項目数は最小 1 個以上である必要があります。',
        'per_page_max' => 'ページあたりの項目数は最大 100 個まで設定できます。',
        'page_min' => 'ページ番号は最小 1 以上である必要があります。',
    ],
    'commands' => [
        'list' => [
            'headers' => [
                'identifier' => '識別子',
                'name' => '名前',
                'vendor' => 'ベンダー',
                'version' => 'バージョン',
                'status' => 'ステータス',
            ],
            'status' => [
                'active' => '有効',
                'inactive' => '無効',
                'uninstalled' => '未インストール',
            ],
            'no_plugins' => 'プラグインがありません。',
            'summary' => '合計 :total 個のプラグイン (インストール済み: :installed、有効: :active)',
            'invalid_status' => '無効なステータスです。(installed、uninstalled、active、inactive)',
        ],
        'install' => [
            'success' => 'プラグイン ":plugin" のインストールが完了しました',
            'vendor' => 'ベンダー: :vendor',
            'version' => 'バージョン: :version',
            'roles_created' => ':count 個のロールが作成されました',
            'permissions_created' => ':count 個の権限が作成されました',
            'already_installed' => 'プラグイン ":plugin" は既にインストールされています。',
            'force_reinstall' => 'プラグイン ":plugin" を強制的に再インストールします (有効ディレクトリを上書き)...',
        ],
        'activate' => [
            'success' => 'プラグイン ":plugin" の有効化が完了しました',
            'not_installed' => 'プラグイン ":plugin" はインストールされていません。',
            'already_active' => 'プラグイン ":plugin" は既に有効化されています。',
            'layouts_registered' => ':count 個のレイアウトが登録されました',
        ],
        'deactivate' => [
            'success' => 'プラグイン ":plugin" の無効化が完了しました',
            'not_installed' => 'プラグイン ":plugin" はインストールされていません。',
            'not_active' => 'プラグイン ":plugin" は有効化されていません。',
            'warning' => 'プラグインのルートと機能が無効化されました。',
            'layouts_deleted' => ':count 個のレイアウトが削除されました',
        ],
        'uninstall' => [
            'success' => 'プラグイン ":plugin" の削除が完了しました',
            'roles_deleted' => ':count 個のロールが削除されました',
            'permissions_deleted' => ':count 個の権限が削除されました',
            'layouts_deleted' => ':count 個のレイアウトが削除されました',
            'confirm_prompt' => 'プラグイン ":plugin" を削除しますか?',
            'confirm_details' => [
                'roles' => '- :count 個のロールが削除されます。',
                'permissions' => '- :count 個の権限が削除されます。',
                'layouts' => '- :count 個のレイアウトが削除されます。',
                'data' => '- すべてのプラグインデータが削除されます。',
            ],
            'confirm_question' => '本当に削除してもよろしいですか?',
            'aborted' => 'プラグインの削除がキャンセルされました。',
            'not_installed' => 'プラグイン ":plugin" はインストールされていません。',
        ],
        'cache_clear' => [
            'clearing_all' => 'すべてのプラグインキャッシュを削除します...',
            'clearing_single' => 'プラグイン ":plugin" のキャッシュを削除します...',
            'success_all' => 'プラグインキャッシュの削除が完了しました (:count 個の項目)',
            'success_single' => 'プラグイン ":plugin" のキャッシュ削除が完了しました (:count 個の項目)',
        ],
        'check_updates' => [
            'not_installed' => 'プラグイン ":plugin" はインストールされていません。',
            'no_installed' => 'インストール済みのプラグインがありません。',
            'update_available' => 'アップデート利用可能',
            'up_to_date' => '最新',
            'headers' => [
                'identifier' => '識別子',
                'current_version' => '現在のバージョン',
                'latest_version' => '最新バージョン',
                'source' => 'ソース',
                'status' => 'ステータス',
            ],
            'summary' => '合計 :total個を確認しました（アップデート可能: :updates個）',
            'single_up_to_date' => 'プラグイン":plugin"は最新バージョンです。（v:version）',
            'single_update_available' => 'プラグイン":plugin"がアップデート可能です: v:current → v:latest（:source）',
        ],
        'update' => [
            'success' => 'プラグイン":plugin"のアップデートが完了しました',
            'version_change' => 'v:from → v:to',
            'no_update' => 'プラグイン":plugin"に利用可能なアップデートがありません。',
            'not_installed' => 'プラグイン":plugin"はインストールされていません。',
            'current_version' => '現在のバージョン: :version',
            'latest_version' => '最新バージョン: :version',
            'update_source' => 'アップデートソース: :source',
            'confirm_question' => 'アップデートを実行しますか？',
            'aborted' => 'アップデートがキャンセルされました。',
            'backup_restored' => 'バックアップから前のバージョンが復元されました。',
            'force_mode' => '強制アップデートモード: バージョン比較をスキップして再インストールします。',
        ],
    ],
    'composer_install' => [
        'start' => 'プラグイン":plugin"のComposer依存関係をインストール中です...',
        'success' => 'プラグイン":plugin"のComposer依存関係のインストールが完了しました',
        'no_dependencies' => 'プラグイン":plugin"にインストールするComposer依存関係がありません。',
        'failed' => 'プラグイン":plugin"のComposer依存関係のインストールに失敗しました。',
        'summary' => '📊 結果: 成功 :success個、スキップ :skip個、失敗 :fail個',
    ],
    'settings' => [
        'update_failed' => 'プラグイン設定のアップデートに失敗しました。',
        'updated' => 'プラグイン設定が正常にアップデートされました。',
    ],
    'dependent_templates_success' => '依存テンプレート情報を正常に取得しました。',
    'dependent_templates_failed' => '依存テンプレート情報の取得に失敗しました: :error',
];
