<?php

return [
    'fetch_success' => 'スケジュール一覧を取得しました。',
    'fetch_failed' => 'スケジュール一覧の取得に失敗しました。',
    'create_success' => 'スケジュールが作成されました。',
    'create_failed' => 'スケジュールの作成に失敗しました。',
    'update_success' => 'スケジュールが編集されました。',
    'update_failed' => 'スケジュールの編集に失敗しました。',
    'delete_success' => 'スケジュールが削除されました。',
    'delete_failed' => 'スケジュールの削除に失敗しました。',
    'run_success' => 'スケジュールが実行されました。',
    'run_failed' => 'スケジュールの実行に失敗しました。',
    'duplicate_success' => 'スケジュールが複製されました。',
    'duplicate_failed' => 'スケジュールの複製に失敗しました。',
    'bulk_status_updated' => '選択されたスケジュールのステータスが変更されました。',
    'bulk_update_status_failed' => 'スケジュール一括ステータス変更に失敗しました。',
    'bulk_delete_success' => '選択されたスケジュールが削除されました。',
    'bulk_delete_failed' => 'スケジュール一括削除に失敗しました。',
    'statistics_success' => 'スケジュール統計を取得しました。',
    'statistics_failed' => 'スケジュール統計の取得に失敗しました。',
    'history_fetch_success' => '実行履歴を取得しました。',
    'history_fetch_failed' => '実行履歴の取得に失敗しました。',
    'history_delete_success' => '実行履歴が削除されました。',
    'history_delete_failed' => '実行履歴の削除に失敗しました。',
    'history_not_found' => '実行履歴が見つかりません。',
    'copy' => 'コピー',
    'shell_command_failed' => 'シェルコマンドの実行に失敗しました。',
    'http_request_failed' => 'HTTPリクエスト失敗（ステータス：:status）',
    'type' => [
        'artisan' => 'Artisanコマンド',
        'shell' => 'シェルコマンド',
        'url' => 'URL呼び出し',
    ],
    'frequency' => [
        'everyMinute' => '毎分',
        'hourly' => '毎時間',
        'daily' => '毎日',
        'weekly' => '毎週',
        'monthly' => '毎月',
        'custom' => 'カスタム',
    ],
    'result' => [
        'success' => '成功',
        'failed' => '失敗',
        'running' => '実行中',
        'never' => '未実行',
    ],
    'trigger_type' => [
        'scheduled' => 'スケジュール実行',
        'manual' => '手動実行',
    ],
    'duration' => [
        'seconds' => '秒',
        'minutes' => '分',
    ],
    'validation' => [
        'page_integer' => 'ページ番号は整数である必要があります。',
        'page_min' => 'ページ番号は1以上である必要があります。',
        'per_page_integer' => 'ページあたりの項目数は整数である必要があります。',
        'per_page_min' => 'ページあたりの項目数は1以上である必要があります。',
        'per_page_max' => 'ページあたりの項目数は100以下である必要があります。',
        'type_invalid' => '無効なタスクタイプです。',
        'frequency_invalid' => '無効な実行周期です。',
        'status_invalid' => '無効なステータスです。',
        'last_result_invalid' => '無効な実行結果です。',
        'history_status_invalid' => '無効な履歴ステータスです。',
        'trigger_type_invalid' => '無効なトリガータイプです。',
        'created_from_invalid' => '開始日のフォーマットが正しくありません。',
        'created_to_invalid' => '終了日のフォーマットが正しくありません。',
        'created_to_after_from' => '終了日は開始日以降である必要があります。',
        'started_from_invalid' => '開始日のフォーマットが正しくありません。',
        'started_to_invalid' => '終了日のフォーマットが正しくありません。',
        'started_to_after_from' => '終了日は開始日以降である必要があります。',
        'sort_by_invalid' => '無効なソート基準です。',
        'sort_order_invalid' => '無効なソート順序です。',
        'name_required' => 'タスク名は必須です。',
        'name_max' => 'タスク名は255文字以下である必要があります。',
        'type_required' => 'タスクタイプは必須です。',
        'command_required' => 'コマンドは必須です。',
        'command_max' => 'コマンドは2000文字以下である必要があります。',
        'expression_required' => 'Cron式は必須です。',
        'expression_max' => 'Cron式は100文字以下である必要があります。',
        'frequency_required' => '実行周期は必須です。',
        'timeout_integer' => 'タイムアウト制限は整数である必要があります。',
        'timeout_min' => 'タイムアウト制限は1秒以上である必要があります。',
        'timeout_max' => 'タイムアウト制限は86400秒（24時間）以下である必要があります。',
        'ids_required' => 'IDリストは必須です。',
        'ids_array' => 'IDリストは配列である必要があります。',
        'ids_min' => '最低1つ以上のIDが必要です。',
        'id_integer' => 'IDは整数である必要があります。',
        'id_exists' => '存在しないスケジュールです。',
        'is_active_required' => '有効化は必須です。',
        'is_active_boolean' => '有効化はtrue/falseである必要があります。',
    ],
    'permissions' => [
        'read' => 'スケジュール調査',
        'create' => 'スケジュール作成',
        'update' => 'スケジュール編集',
        'delete' => 'スケジュール削除',
        'run' => 'スケジュール実行',
    ],
];
