<?php

return [
    'fetch_success' => 'スケジュールリストを閲覧しました。',
    'fetch_failed' => 'スケジュールリスト閲覧に失敗しました。',
    'create_success' => 'スケジュールが作成されました。',
    'create_failed' => 'スケジュール作成に失敗しました。',
    'update_success' => 'スケジュールが編集されました。',
    'update_failed' => 'スケジュール編集に失敗しました。',
    'delete_success' => 'スケジュールが削除されました。',
    'delete_failed' => 'スケジュール削除に失敗しました。',
    'run_success' => 'スケジュールが実行されました。',
    'run_failed' => 'スケジュール実行に失敗しました。',
    'duplicate_success' => 'スケジュールが複製されました。',
    'duplicate_failed' => 'スケジュール複製に失敗しました。',
    'bulk_status_updated' => '選択されたスケジュールのステータスが変更されました。',
    'bulk_update_status_failed' => 'スケジュールステータス一括変更に失敗しました。',
    'bulk_delete_success' => '選択されたスケジュールが削除されました。',
    'bulk_delete_failed' => 'スケジュール一括削除に失敗しました。',
    'statistics_success' => 'スケジュール統計を閲覧しました。',
    'statistics_failed' => 'スケジュール統計閲覧に失敗しました。',
    'history_fetch_success' => '実行履歴を閲覧しました。',
    'history_fetch_failed' => '実行履歴閲覧に失敗しました。',
    'history_delete_success' => '実行履歴が削除されました。',
    'history_delete_failed' => '実行履歴削除に失敗しました。',
    'history_not_found' => '実行履歴が見つかりません。',
    'copy' => 'コピー',
    'shell_command_failed' => 'シェルコマンド実行に失敗しました。',
    'http_request_failed' => 'HTTP リクエスト失敗(ステータス::status)',
    'url_not_public' => '内部ネットワークアドレス(プライベート IP·localhost など)は呼び出せません。社内アドレスを呼び出す必要がある場合は、環境設定 > セキュリティで「内部ネットワークアドレス呼び出し許可」をオンにしてください。',
    'shell_not_allowed' => '許可されていないシェルコマンドです。サーバーに登録された実行ファイルのみスケジュール実行できます。',
    'artisan_not_allowed' => 'この Artisan コマンドはセキュリティ上の理由からスケジュール実行できません。',
    'type' => [
        'artisan' => 'Artisan コマンド',
        'shell' => 'シェルコマンド',
        'url' => 'URL 呼び出し',
    ],
    'frequency' => [
        'everyMinute' => '毎分',
        'hourly' => '毎時間',
        'daily' => '毎日',
        'weekly' => '毎週',
        'monthly' => '毎月',
        'custom' => 'カスタム',
    ],
    'result' => [
        'success' => '成功',
        'failed' => '失敗',
        'running' => '実行中',
        'never' => '未実行',
    ],
    'trigger_type' => [
        'scheduled' => '予約実行',
        'manual' => '手動実行',
    ],
    'duration' => [
        'seconds' => '秒',
        'minutes' => '分',
    ],
    'validation' => [
        'page_integer' => 'ページ番号は整数である必要があります。',
        'page_min' => 'ページ番号は 1 以上である必要があります。',
        'per_page_integer' => 'ページあたりの項目数は整数である必要があります。',
        'per_page_min' => 'ページあたりの項目数は 1 以上である必要があります。',
        'per_page_max' => 'ページあたりの項目数は 100 以下である必要があります。',
        'type_invalid' => '無効なタスクタイプです。',
        'frequency_invalid' => '無効な実行周期です。',
        'status_invalid' => '無効なステータスです。',
        'last_result_invalid' => '無効な実行結果です。',
        'history_status_invalid' => '無効な履歴ステータスです。',
        'trigger_type_invalid' => '無効なトリガータイプです。',
        'created_from_invalid' => '開始日の形式が正しくありません。',
        'created_to_invalid' => '終了日の形式が正しくありません。',
        'created_to_after_from' => '終了日は開始日以降である必要があります。',
        'started_from_invalid' => '開始日の形式が正しくありません。',
        'started_to_invalid' => '終了日の形式が正しくありません。',
        'started_to_after_from' => '終了日は開始日以降である必要があります。',
        'sort_by_invalid' => '無効なソート基準です。',
        'sort_order_invalid' => '無効なソート順序です。',
        'name_required' => 'タスク名は必須です。',
        'name_max' => 'タスク名は 255 文字以下である必要があります。',
        'type_required' => 'タスクタイプは必須です。',
        'command_required' => 'コマンドは必須です。',
        'command_max' => 'コマンドは 2000 文字以下である必要があります。',
        'expression_required' => 'Cron 式は必須です。',
        'expression_max' => 'Cron 式は 100 文字以下である必要があります。',
        'frequency_required' => '実行周期は必須です。',
        'timeout_integer' => 'タイムアウトは整数である必要があります。',
        'timeout_min' => 'タイムアウトは 1 秒以上である必要があります。',
        'timeout_max' => 'タイムアウトは 86400 秒(24 時間)以下である必要があります。',
        'ids_required' => 'ID リストは必須です。',
        'ids_array' => 'ID リストは配列である必要があります。',
        'ids_min' => '最小 1 個以上の ID が必要です。',
        'id_integer' => 'ID は整数である必要があります。',
        'id_exists' => 'スケジュールが存在しません。',
        'is_active_required' => '有効化の有無は必須です。',
        'is_active_boolean' => '有効化の有無は真/偽である必要があります。',
    ],
    'permissions' => [
        'read' => 'スケジュール閲覧',
        'create' => 'スケジュール作成',
        'update' => 'スケジュール編集',
        'delete' => 'スケジュール削除',
        'run' => 'スケジュール実行',
    ],
];
