<?php

return [
    'empty_keyword' => '検索語を入力してください。',
    'results_found' => ':count件の検索結果が見つかりました。',
    'no_results' => '検索結果がありません。',
    'view_more' => 'もっと見る',
    'validation' => [
        'q_min' => '検索語は2文字以上で入力してください。',
        'q_max' => '検索語は最大200文字まで入力可能です。',
        'page_integer' => 'ページ番号は数字である必要があります。',
        'page_min' => 'ページ番号は1以上である必要があります。',
        'per_page_integer' => 'ページあたりの項目数は数字である必要があります。',
        'per_page_min' => 'ページあたりの項目数は1以上である必要があります。',
        'per_page_max' => 'ページあたりの項目数は最大100個まで可能です。',
        'page_max' => 'ページ番号は :max 以下である必要があります。検索キーワードをより具体的に入力してください。',
    ],
    'index' => [
        'status' => [
            'healthy' => '正常',
            'degraded' => '部分的',
            'stale' => 'インデックス未反映',
            'skipped' => '判定不可',
        ],
        'no_maintainer' => '現在の検索エンジン(:driver)はインデックス点検を提供していません。エンジン提供元が点検機能を登録すると、この画面で併せて扱えます。',
        'unavailable' => '現在の検索エンジン(:driver)のインデックスを点検できません。',
        'no_targets' => '検索エンジン(:driver)に点検対象のインデックスがありません。',
        'driver_label' => '検索エンジン: :driver',
        'col' => [
            'index' => 'インデックス',
            'status' => '判定',
            'measurement' => '測定',
        ],
        'counts' => '正常 :healthy · 部分的 :degraded · 未反映 :stale · 判定不可 :skipped  (合計 :total)',
        'rebuild_targets' => '再生成対象 :count件',
        'rebuild_cost_warning' => '再生成中は対象インデックスがロックされるか再インデックスされます。稼働中のサイトではメンテナンス時間帯に実行してください。',
        'rebuild_confirm' => '上記のインデックスを再生成しますか?',
        'rebuild_after_bulk_confirm' => '一括アップデート後に検索インデックスを再生成しますか? (既定: いいえ — 稼働中であればメンテナンス時間帯に別途実行してください)',
        'rebuild_skipped' => '再生成をスキップします。',
        'stale_hint' => 'インデックスが未反映のものがあります。`php artisan search:index --repair` で再生成してください。',
        'stale_after_update' => 'インデックスが未反映の検索インデックスが :count 件あり、該当する検索が結果を返しません。',
        'rebuilt_item' => '再生成: :index',
        'rebuild_failed_item' => '再生成失敗: :index — :error',
        'still_stale_item' => '再生成後も未反映: :index',
        'degraded_hint' => '「部分的」はエンジンのトークン処理特性の可能性があるため、自動再生成の対象外です。必要であれば個別に確認してください。',
        'report' => [
            'nothing_to_do' => '点検 :count件 · 再生成対象なし',
            'rebuilt' => '点検 :inspected件 · 再生成 :repaired件 · 失敗 :failed件 · 残存 :remaining件',
        ],
        'fulltext' => [
            'unsupported_driver' => '現在のDBドライバはFULLTEXTをサポートしていません (LIKE検索で動作し、点検対象はありません)。',
            'self_match' => ':found/:probed 行が自分自身を検出',
            'skip' => [
                'no_single_pk' => '単一カラムの主キーがないため、行単位の判定ができません',
                'no_rows' => 'インデックス対象カラムに内容がある行がありません',
                'no_tokens' => 'サンプル行から検索トークンを作成できません (内容が短すぎます)',
            ],
        ],
    ],
    'results_found_at_least' => ':count件以上の検索結果が見つかりました。',
    'result_cap_notice' => '一致する項目が :cap件を超えており、合計件数を正確にカウントしていません。次のページに続行できます。',
    'refine_query_hint' => '検索キーワードをより具体的に入力すると、正確な件数と最後のページを確認できます。',
];
