<?php

return [
    'cache_cleared_all' => 'SEO キャッシュがすべて削除されました。',
    'cache_cleared_layout' => ':layout レイアウトの SEO キャッシュ :count 件が削除されました。',
    'warmup_started' => 'SEO キャッシュ ウォーミングアップを開始します。',
    'warmup_started_layout' => ':layout レイアウトの SEO キャッシュ ウォーミングアップを開始します。',
    'warmup_dispatched' => 'SEO キャッシュ ウォーミングアップが開始されました。',
    'sitemap_regenerated' => 'Sitemap 再生成が完了しました。',
    'sitemap_regenerate_dispatched' => 'Sitemap 再生成を開始しました。完了まで時間がかかる場合があります。',
    'sitemap_regenerate_failed' => 'Sitemap 再生成に失敗しました。',
    'sitemap_disabled' => 'Sitemap 生成が無効化されています。',
    'sitemap_not_ready' => 'Sitemap を準備中です。しばらく後に再度お試しください。',
    'sitemap_generate_failed' => 'Sitemap 生成に失敗しました: :error',
    'stats_period' => '最近 :days 日間の SEO キャッシュ統計',
    'stats_overall' => '全体統計',
    'stats_metric' => '項目',
    'stats_value' => '値',
    'stats_total_entries' => '総キャッシュ項目',
    'stats_hits' => 'キャッシュ ヒット',
    'stats_misses' => 'キャッシュ ミス',
    'stats_hit_rate' => 'ヒット率',
    'stats_avg_response_time' => '平均応答時間',
    'stats_by_layout' => 'レイアウト別統計',
    'stats_layout_name' => 'レイアウト',
    'stats_total' => '合計',
    'stats_by_module' => 'モジュール別統計',
    'stats_module_identifier' => 'モジュール',
];
