<?php

return [
    'fetch_success' => '設定が正常にインポートされました。',
    'fetch_failed' => '設定のインポートに失敗しました。',
    'save_success' => '設定が正常に保存されました。',
    'save_failed' => '設定の保存に失敗しました。',
    'update_success' => '設定が正常に更新されました。',
    'update_failed' => '設定の更新に失敗しました。',
    'delete_success' => '設定が正常に削除されました。',
    'delete_failed' => '設定の削除に失敗しました。',
    'save_error' => '設定の保存中にエラーが発生しました。',
    'update_error' => '設定の更新中にエラーが発生しました。',
    'cache_clear_success' => 'キャッシュが正常にクリアされました。',
    'cache_clear_failed' => 'キャッシュのクリアに失敗しました。',
    'cache_clear_error' => 'キャッシュのクリア中にエラーが発生しました。',
    'optimize_success' => 'システムが正常に最適化されました。',
    'optimize_failed' => 'システムの最適化に失敗しました。',
    'optimize_error' => 'システムの最適化中にエラーが発生しました。',
    'backup_success' => 'データベースバックアップが正常に開始されました。',
    'backup_failed' => 'データベースバックアップに失敗しました。',
    'backup_error' => 'データベースバックアップ中にエラーが発生しました。',
    'save_individual_failed' => '設定の保存に失敗しました：:error',
    'invalid_password' => 'パスワードが一致しません。',
    'password_required' => 'パスワードを入力してください。',
    'app_key_regenerated' => 'アプリケーションキーが正常に再生成されました。',
    'app_key_regenerate_failed' => 'アプリケーションキーの再生成に失敗しました。',
    'app_key_regenerate_warning' => 'キーを変更するとすべてのセッションが無効になります。続行しますか？',
    'seconds' => '秒',
    'drivers' => [
        'storage' => [
            'local' => 'ローカル',
            's3' => 'Amazon S3',
        ],
        'cache' => [
            'file' => 'ファイル',
            'redis' => 'Redis',
        ],
        'session' => [
            'file' => 'ファイル',
            'database' => 'データベース',
            'redis' => 'Redis',
        ],
        'queue' => [
            'sync' => '同期',
            'database' => 'データベース',
            'redis' => 'Redis',
        ],
        'log' => [
            'single' => '単一ファイル',
            'daily' => '日別ファイル',
        ],
        'websocket' => [
            'reverb' => 'Laravel Reverb',
        ],
        'mail' => [
            'smtp' => 'SMTP',
            'mailgun' => 'Mailgun',
            'ses' => 'SES (Amazon)',
        ],
    ],
    'driver_test_success' => 'すべてのドライバー接続テストが成功しました。',
    'driver_test_partial' => '一部のドライバー接続テストが失敗しました。',
    'driver_test_error' => 'ドライバー接続テスト中にエラーが発生しました。',
    'unknown_driver' => '不明なドライバーです。',
    's3_test_success' => 'S3バケットに正常に接続されました。',
    's3_test_failed' => 'S3バケットへの接続に失敗しました。',
    's3_missing_config' => 'S3設定が不足しています。(バケット、リージョン、アクセスキー、シークレットキー)',
    's3_sdk_missing' => 'AWS SDKがインストールされていません。',
    's3_bucket_not_found' => 'S3バケットが見つかりません。',
    's3_access_denied' => 'S3バケットへのアクセスが拒否されました。',
    's3_invalid_credentials' => 'S3認証情報が正しくありません。',
    'redis_test_success' => 'Redisサーバーに正常に接続されました。',
    'redis_test_failed' => 'Redisサーバーへの接続に失敗しました。',
    'redis_extension_missing' => 'Redis PHP拡張がインストールされていません。',
    'redis_connection_failed' => 'Redisサーバーに接続できません。',
    'redis_auth_failed' => 'Redis認証に失敗しました。',
    'redis_ping_failed' => 'Redis PING応答がありません。',
    'memcached_test_success' => 'Memcachedサーバーに正常に接続されました。',
    'memcached_test_failed' => 'Memcachedサーバーへの接続に失敗しました。',
    'memcached_extension_missing' => 'Memcached PHP拡張がインストールされていません。',
    'memcached_connection_failed' => 'Memcachedサーバーに接続できません。',
    'websocket_test_success' => 'Websocketサーバーに正常に接続されました。',
    'websocket_test_failed' => 'Websocketサーバーへの接続に失敗しました。',
    'websocket_connection_refused' => 'Websocketサーバーに接続できません。サーバーが実行されているか確認してください。',
    'invalid_email' => '無効なメールアドレスです。',
    'test_mail_subject' => ':app_name テストメール',
    'test_mail_body' => 'これはグヌボード7から送信されたテストメールです。このメールを受け取った場合、メール設定が正しく構成されています。',
    'test_mail_sent' => 'テストメールが正常に送信されました。',
    'test_mail_failed' => 'テストメールの送信に失敗しました。',
    'test_mail_error' => 'テストメール送信中にエラーが発生しました。',
    'core_update' => [
        'check_success' => 'アップデート確認が完了しました。',
        'check_failed' => 'アップデート確認に失敗しました。',
        'update_available' => '新しいアップデートがあります。',
        'no_update' => '現在は最新バージョンです。',
        'maintenance_mode_active' => 'システム保守中です。しばらく後に再度お試しください。',
        'invalid_github_url' => 'GitHubリポジトリURLが無効です。',
        'download_failed' => ':version バージョンのダウンロードに失敗しました。',
        'zip_extract_failed' => 'ZIPファイルの解凍に失敗しました。',
        'invalid_package' => 'ダウンロードされたパッケージが無効です。',
        'invalid_package_not_g7' => '指定されたディレクトリはグヌボード7プロジェクトではありません。config/app.phpファイルとversionの設定が必要です。',
        'composer_failed' => 'composer installの実行に失敗しました。',
        'pending_path_create_failed' => '_pendingディレクトリ(:path)の作成に失敗しました：:error',
        'pending_path_not_writable' => '_pendingディレクトリ(:path)への書き込み権限がありません。',
        'downloading' => 'アップデートをダウンロード中...',
        'extracting' => '解凍中...',
        'validating' => 'パッケージを検証中...',
        'running_composer' => 'composer installを実行中...',
        'step_check' => 'アップデートを確認中...',
        'step_validate_pending' => '環境を検証中...',
        'step_maintenance' => 'メンテナンスモードを有効化中...',
        'step_download' => 'ダウンロード中...',
        'step_backup' => 'バックアップを作成中...',
        'step_apply' => 'ファイルを適用中...',
        'step_composer' => 'composer installを実行中...',
        'step_migration' => 'マイグレーションを実行中...',
        'step_upgrade' => 'アップグレードステップを実行中...',
        'step_composer_prod' => '運用ディレクトリのcomposer installを実行中...',
        'step_cleanup' => 'クリーンアップ中...',
        'github_url_not_configured' => 'GitHubリポジトリのURLが設定されていません。',
        'github_api_failed' => 'GitHub APIに接続できません。',
        'github_token_required' => 'プライベートリポジトリです。GitHubアクセストークンを設定してください。',
        'github_token_invalid' => 'GitHubアクセストークンが無効であるか、権限が不足しています。(HTTP :status — :message)',
        'github_repo_not_found' => 'GitHubリポジトリが見つかりません。(HTTP :status — :message)',
        'github_repo_not_found_no_token' => 'GitHubリポジトリが見つかりません。プライベートリポジトリの場合はアクセストークンを設定してください。(HTTP :status — :message)',
        'github_api_error' => 'GitHub APIエラーが発生しました。(HTTP :status — :message)',
        'no_releases_found' => 'GitHubリポジトリにリリースがありません。(HTTP :status — :message)',
        'log_api_call_failed' => 'コアアップデート:GitHub APIの呼び出しに失敗しました',
        'log_auth_failed' => 'コアアップデート:GitHub認証に失敗しました',
        'log_not_found' => 'コアアップデート:GitHubリポジトリ/リリースが見つかりません',
        'log_unexpected_status' => 'コアアップデート:予期しないHTTPステータスコード',
        'log_version_check_error' => 'コアアップデート:最新バージョン確認中にエラーが発生しました',
        'unknown_error' => '予期しないエラーが発生しました。',
        'system_requirements_failed' => 'システム要件が満たされていません:',
        'no_extract_method_available' => '利用可能なアーカイブ抽出方法がありません。PHP zip拡張機能(ZipArchive)またはunzipコマンド(Linux)のいずれかが必要です。または--sourceオプションで手動アップデートできます。',
        'manual_update_guide' => '手動アップデート:GitHubからリリースZIPをダウンロードして解凍し、php artisan core:update --source=/解凍パス コマンドを実行してください。',
        'archive_url_not_found' => ':typeアーカイブURLが見つかりません。次の方法を試みます。',
        'extracting_with' => ':method方式で解凍中...',
        'extract_empty' => '解凍されたディレクトリが空です。',
        'extract_fallback' => ':method方式に失敗しました::error — 次の方法を試みます。',
        'all_extract_methods_failed' => 'すべてのアーカイブ抽出方法が失敗しました。--sourceオプションで手動アップデートを試みてください。',
        'unzip_command_failed' => 'unzipコマンド実行に失敗しました(終了コード::code)。:output',
        'zip_file_not_found' => '指定されたZIPファイルが見つかりません::path',
        'source_vendor_missing' => 'ソースディレクトリにvendorがありません。composer installが実行されていない可能性があります。',
        'composer_failed_with_output' => 'composer installの実行に失敗しました。:output',
    ],
];
