<?php

return [
    'accepted' => ':attribute フィールドを承認する必要があります。',
    'accepted_if' => ':other が :value の場合、:attribute フィールドを承認する必要があります。',
    'active_url' => ':attribute フィールドは有効な URL である必要があります。',
    'after' => ':attribute フィールドは :date より後の日付である必要があります。',
    'after_or_equal' => ':attribute フィールドは :date 以降の日付である必要があります。',
    'alpha' => ':attribute フィールドは文字のみを含む必要があります。',
    'alpha_dash' => ':attribute フィールドは文字、数字、ダッシュ、アンダースコアのみを含む必要があります。',
    'alpha_num' => ':attribute フィールドは文字と数字のみを含む必要があります。',
    'array' => ':attribute フィールドは配列である必要があります。',
    'ascii' => ':attribute フィールドはシングルバイト英数字文字と記号のみを含む必要があります。',
    'before' => ':attribute フィールドは :date より前の日付である必要があります。',
    'before_or_equal' => ':attribute フィールドは :date 以前の日付である必要があります。',
    'between' => [
        'array' => ':attribute フィールドは :min ～ :max 個の項目を含む必要があります。',
        'file' => ':attribute フィールドは :min ～ :max KB の間である必要があります。',
        'numeric' => ':attribute フィールドは :min ～ :max の間である必要があります。',
        'string' => ':attribute フィールドは :min ～ :max 文字の間である必要があります。',
    ],
    'boolean' => ':attribute フィールドは true または false である必要があります。',
    'can' => ':attribute フィールドに許可されていない値が含まれています。',
    'confirmed' => ':attribute フィールド確認が一致しません。',
    'contains' => ':attribute フィールドに必須値が不足しています。',
    'current_password' => 'パスワードが正しくありません。',
    'date' => ':attribute フィールドは有効な日付である必要があります。',
    'date_equals' => ':attribute フィールドは :date と同じ日付である必要があります。',
    'date_format' => ':attribute フィールドは :format 形式と一致する必要があります。',
    'decimal' => ':attribute フィールドは :decimal 桁数の小数点である必要があります。',
    'declined' => ':attribute フィールドを却下する必要があります。',
    'declined_if' => ':other が :value の場合、:attribute フィールドを却下する必要があります。',
    'different' => ':attribute フィールドと :other は異なる必要があります。',
    'digits' => ':attribute フィールドは :digits 桁数である必要があります。',
    'digits_between' => ':attribute フィールドは :min ～ :max 桁数の間である必要があります。',
    'dimensions' => ':attribute フィールドの画像サイズが正しくありません。',
    'distinct' => ':attribute フィールドに重複した値があります。',
    'doesnt_end_with' => ':attribute フィールドは :values で終わってはいけません。',
    'doesnt_start_with' => ':attribute フィールドは :values で始まってはいけません。',
    'email' => ':attribute フィールドは有効なメールアドレスである必要があります。',
    'ends_with' => ':attribute フィールドは次のいずれかで終わる必要があります: :values。',
    'enum' => '選択された :attribute が正しくありません。',
    'exists' => '選択された :attribute が正しくありません。',
    'extensions' => ':attribute フィールドは次の拡張子のいずれかである必要があります: :values。',
    'file' => ':attribute フィールドはファイルである必要があります。',
    'filled' => ':attribute フィールドに値が存在する必要があります。',
    'gt' => [
        'array' => ':attribute フィールドは :value 個より多くの項目を含む必要があります。',
        'file' => ':attribute フィールドは :value KB より大きくする必要があります。',
        'numeric' => ':attribute フィールドは :value より大きくする必要があります。',
        'string' => ':attribute フィールドは :value 文字より長くする必要があります。',
    ],
    'gte' => [
        'array' => ':attribute フィールドは :value 個以上の項目を含む必要があります。',
        'file' => ':attribute フィールドは :value KB 以上である必要があります。',
        'numeric' => ':attribute フィールドは :value 以上である必要があります。',
        'string' => ':attribute フィールドは :value 文字以上である必要があります。',
    ],
    'hex_color' => ':attribute フィールドは有効な16進数カラーである必要があります。',
    'image' => ':attribute フィールドは画像である必要があります。',
    'in' => '選択された :attribute が正しくありません。',
    'in_array' => ':attribute フィールドは :other に存在する必要があります。',
    'integer' => ':attribute フィールドは整数である必要があります。',
    'ip' => ':attribute フィールドは有効な IP アドレスである必要があります。',
    'ipv4' => ':attribute フィールドは有効な IPv4 アドレスである必要があります。',
    'ipv6' => ':attribute フィールドは有効な IPv6 アドレスである必要があります。',
    'json' => ':attribute フィールドは有効な JSON 文字列である必要があります。',
    'list' => ':attribute フィールドはリストである必要があります。',
    'lowercase' => ':attribute フィールドは小文字である必要があります。',
    'lt' => [
        'array' => ':attribute フィールドは :value 個より少ない項目を含む必要があります。',
        'file' => ':attribute フィールドは :value KB より小さくする必要があります。',
        'numeric' => ':attribute フィールドは :value より小さくする必要があります。',
        'string' => ':attribute フィールドは :value 文字より短くする必要があります。',
    ],
    'lte' => [
        'array' => ':attribute フィールドは :value 個を超えてはいけません。',
        'file' => ':attribute フィールドは :value KB 以下である必要があります。',
        'numeric' => ':attribute フィールドは :value 以下である必要があります。',
        'string' => ':attribute フィールドは :value 文字以下である必要があります。',
    ],
    'mac_address' => ':attribute フィールドは有効な MAC アドレスである必要があります。',
    'max' => [
        'array' => ':attribute フィールドは :max 個を超えてはいけません。',
        'file' => ':attribute フィールドは :max KB を超えてはいけません。',
        'numeric' => ':attribute フィールドは :max を超えてはいけません。',
        'string' => ':attribute フィールドは :max 文字を超えてはいけません。',
    ],
    'max_digits' => ':attribute フィールドは :max 桁数を超えてはいけません。',
    'mimes' => ':attribute フィールドは次のタイプのファイルである必要があります: :values。',
    'mimetypes' => ':attribute フィールドは次のタイプのファイルである必要があります: :values。',
    'min' => [
        'array' => ':attribute フィールドは最低 :min 個以上である必要があります。',
        'file' => ':attribute フィールドは最低 :min KB 以上である必要があります。',
        'numeric' => ':attribute フィールドは最低 :min 以上である必要があります。',
        'string' => ':attribute フィールドは最低 :min 文字以上である必要があります。',
    ],
    'min_digits' => ':attribute フィールドは最低でも :min 文字以上である必要があります。',
    'missing' => ':attribute フィールドは存在しないようにしてください。',
    'missing_if' => ':other が :value のとき、:attribute フィールドは存在しないようにしてください。',
    'missing_unless' => ':other が :value ではない場合、:attribute フィールドは存在しないようにしてください。',
    'missing_with' => ':values が存在するとき、:attribute フィールドは存在しないようにしてください。',
    'missing_with_all' => ':values がすべて存在するとき、:attribute フィールドは存在しないようにしてください。',
    'multiple_of' => ':attribute フィールドは :value の倍数である必要があります。',
    'not_in' => '選択した :attribute は無効です。',
    'not_regex' => ':attribute フィールドの形式が無効です。',
    'numeric' => ':attribute フィールドは数値である必要があります。',
    'password' => [
        'letters' => ':attribute フィールドは最低でも 1 文字を含む必要があります。',
        'mixed' => ':attribute フィールドは最低でも 1 つの大文字と 1 つの小文字を含む必要があります。',
        'numbers' => ':attribute フィールドは最低でも 1 つの数字を含む必要があります。',
        'symbols' => ':attribute フィールドは最低でも 1 つの記号を含む必要があります。',
        'uncompromised' => '指定された :attribute はデータ流出に表示されています。別の :attribute を選択してください。',
    ],
    'present' => ':attribute フィールドは存在する必要があります。',
    'present_if' => ':other が :value のとき、:attribute フィールドは存在する必要があります。',
    'present_unless' => ':other が :value ではない場合、:attribute フィールドは存在する必要があります。',
    'present_with' => ':values が存在するとき、:attribute フィールドは存在する必要があります。',
    'present_with_all' => ':values がすべて存在するとき、:attribute フィールドは存在する必要があります。',
    'prohibited' => ':attribute フィールドは許可されていません。',
    'prohibited_if' => ':other が :value のとき、:attribute フィールドは許可されていません。',
    'prohibited_unless' => ':other が :values に含まれていない場合、:attribute フィールドは許可されていません。',
    'prohibits' => ':attribute フィールドは :other が存在することを禁止しています。',
    'regex' => ':attribute フィールドの形式が無効です。',
    'required' => ':attribute フィールドは必須です。',
    'required_array_keys' => ':attribute フィールドは以下の項目を含む必要があります: :values。',
    'required_if' => ':other が :value のとき、:attribute フィールドは必須です。',
    'required_if_accepted' => ':other が承認されている場合、:attribute フィールドは必須です。',
    'required_if_declined' => ':other が却下されている場合、:attribute フィールドは必須です。',
    'required_unless' => ':other が :values に含まれていない場合、:attribute フィールドは必須です。',
    'required_with' => ':values が存在するとき、:attribute フィールドは必須です。',
    'required_with_all' => ':values がすべて存在するとき、:attribute フィールドは必須です。',
    'required_without' => ':values が存在しないとき、:attribute フィールドは必須です。',
    'required_without_all' => ':values がすべて存在しないとき、:attribute フィールドは必須です。',
    'same' => ':attribute フィールドと :other が一致する必要があります。',
    'size' => [
        'array' => ':attribute フィールドは :size 個の項目を含む必要があります。',
        'file' => ':attribute フィールドは :size KB である必要があります。',
        'numeric' => ':attribute フィールドは :size である必要があります。',
        'string' => ':attribute フィールドは :size 文字である必要があります。',
    ],
    'starts_with' => ':attribute フィールドは以下のいずれかで始まる必要があります: :values。',
    'string' => ':attribute フィールドは文字列である必要があります。',
    'timezone' => ':attribute フィールドは有効なタイムゾーンである必要があります。',
    'unique' => ':attribute は既に使用されています。',
    'uploaded' => ':attribute のアップロードに失敗しました。',
    'uppercase' => ':attribute フィールドは大文字である必要があります。',
    'url' => ':attribute フィールドは有効な URL である必要があります。',
    'ulid' => ':attribute フィールドは有効な ULID である必要があります。',
    'uuid' => ':attribute フィールドは有効な UUID である必要があります。',
    'layout' => [
        'invalid_json' => '無効な JSON 形式です。',
        'must_be_array' => 'レイアウトデータは配列である必要があります。',
        'required_field_missing' => '必須フィールド \':field\' が見つかりません。',
        'version_must_be_string' => 'version フィールドは文字列である必要があります。',
        'layout_name_must_be_string' => 'layout_name フィールドは文字列である必要があります。',
        'components_must_be_array' => 'components フィールドは配列である必要があります。',
        'components_or_slots_required' => '継承レイアウトには components または slots のいずれかが必要です。',
        'component_must_be_array' => 'components[:index] は配列である必要があります。',
        'max_depth_exceeded' => 'コンポーネントのネストの深さが最大許容深度(:max)を超えています。',
        'component_required_field_missing' => 'components[:index] に必須フィールド \':field\' が見つかりません。',
        'component_field_must_be_string' => 'components[:index].component は文字列である必要があります。',
        'component_name_must_be_string' => 'components[:index].name は文字列である必要があります。',
        'component_type_invalid' => 'components[:index].type は basic、composite、layout のいずれかである必要があります。',
        'props_must_be_object' => 'components[:index].props はオブジェクト(配列)である必要があります。',
        'children_must_be_array' => 'components[:index].children は配列である必要があります。',
        'permissions_must_be_array' => 'components[:index].permissions は配列である必要があります。',
        'permissions_must_be_array_or_object' => 'permissions は配列または構造化オブジェクト(or/and)である必要があります。',
        'permissions_invalid_operator' => 'permissions の構造では、有効な演算子は「or」または「and」のみが許可されます。キーは正確に 1 つである必要があります。',
        'permissions_operator_must_be_array' => 'permissions の ":operator" 演算子の値は配列である必要があります。',
        'permissions_operator_min_items' => 'permissions の ":operator" 演算子には最低でも :min 個の項目が必要です。',
        'permissions_max_depth_exceeded' => 'permissions の構造の最大ネスト深さ(:max)を超えています。',
        'permission_must_be_string' => 'components[:index].permissions[:perm_index] は文字列である必要があります。',
        'permission_must_be_string_or_group' => 'permissions の項目[:index] は文字列(権限 ID)または構造化オブジェクト(or/and)である必要があります。',
        'permission_invalid_format' => 'components[:index].permissions の ":permission" は正しい権限 ID 形式ではありません。',
        'actions_must_be_array' => 'components[:index].actions は配列である必要があります。',
        'action_must_be_array' => 'components[:index].actions[:actionIndex] は配列である必要があります。',
        'action_type_missing' => 'components[:index].actions[:actionIndex] に必須フィールド \'type\' が見つかりません。',
        'action_type_or_event_missing' => 'components[:index].actions[:actionIndex] には \'type\' または \'event\' のいずれかが必要です。',
        'action_type_must_be_string' => 'components[:index].actions[:actionIndex].type は文字列である必要があります。',
        'action_event_must_be_string' => 'components[:index].actions[:actionIndex].event は文字列である必要があります。',
        'content' => [
            'required' => 'レイアウト content が必要です。',
            'array' => 'レイアウト content は配列である必要があります。',
        ],
        'version' => [
            'required' => 'レイアウト バージョンが必要です。',
            'string' => 'レイアウト バージョンは文字列である必要があります。',
        ],
        'layout_name' => [
            'required' => 'レイアウト 名が必要です。',
            'string' => 'レイアウト 名は文字列である必要があります。',
            'max' => 'レイアウト 名は :max 文字を超えることはできません。',
        ],
        'endpoint' => [
            'required' => 'API エンドポイントが必要です。',
            'string' => 'API エンドポイントは文字列である必要があります。',
        ],
        'extends' => [
            'string' => 'extends は文字列である必要があります。',
        ],
        'slots' => [
            'array' => 'slots は配列である必要があります。',
        ],
        'components' => [
            'required' => 'コンポーネント配列が必要です。',
            'array' => 'components フィールドは配列である必要があります。',
        ],
        'data_sources' => [
            'array' => 'data_sources フィールドは配列である必要があります。',
        ],
        'metadata' => [
            'array' => 'metadata フィールドは配列である必要があります。',
        ],
        'meta' => [
            'array' => 'meta フィールドは配列である必要があります。',
            'title' => [
                'string' => 'meta.title は文字列である必要があります。',
            ],
            'description' => [
                'string' => 'meta.description は文字列である必要があります。',
            ],
            'auth_required' => [
                'boolean' => 'meta.auth_required は論理値である必要があります。',
            ],
            'is_base' => [
                'boolean' => 'meta.is_base は論理値である必要があります。',
            ],
        ],
        'modals' => [
            'array' => 'modals フィールドは配列である必要があります。',
        ],
        'state' => [
            'array' => 'state フィールドは配列である必要があります。',
        ],
        'init_actions' => [
            'array' => 'init_actions フィールドは配列である必要があります。',
        ],
        'defines' => [
            'array' => 'defines フィールドは配列である必要があります。',
        ],
        'init_state' => [
            'array' => 'init_state フィールドは配列である必要があります。',
        ],
        'routes' => [
            'array' => 'routes フィールドは配列である必要があります。',
        ],
        'computed' => [
            'array' => 'computed フィールドは配列である必要があります。',
        ],
        'permissions' => [
            'array' => 'permissions フィールドは配列である必要があります。',
            'string' => '各権限識別子は文字列である必要があります。',
            'regex' => '権限識別子形式が正しくありません。(例: module.entity.action)',
        ],
        'globalHeaders' => [
            'array' => 'globalHeaders フィールドは配列である必要があります。',
            'pattern' => [
                'required' => '各 globalHeaders ルールには pattern フィールドが必要です。',
                'string' => 'globalHeaders pattern は文字列である必要があります。',
            ],
            'headers' => [
                'required' => '各 globalHeaders ルールには headers フィールドが必要です。',
                'array' => 'globalHeaders headers は配列である必要があります。',
                'string' => 'ヘッダー値は文字列である必要があります。',
            ],
        ],
        'transition_overlay' => [
            'enabled' => [
                'boolean' => '遷移オーバーレイ有効化は true または false である必要があります。',
            ],
            'style' => [
                'string' => '遷移オーバーレイ スタイルは文字列である必要があります。',
                'in' => '遷移オーバーレイ スタイルは opaque、blur、fade、skeleton のいずれかである必要があります。',
            ],
            'target' => [
                'string' => '遷移オーバーレイ ターゲットは文字列である必要があります。',
                'max' => '遷移オーバーレイ ターゲットは :max 文字を超えることはできません。',
            ],
            'fallback_target' => [
                'string' => '遷移オーバーレイ フォールバック ターゲットは文字列である必要があります。',
                'max' => '遷移オーバーレイ フォールバック ターゲットは :max 文字を超えることはできません。',
            ],
            'skeleton' => [
                'array' => 'スケルトン設定は配列である必要があります。',
                'component' => [
                    'string' => 'スケルトン コンポーネント名は文字列である必要があります。',
                    'max' => 'スケルトン コンポーネント名は :max 文字を超えることはできません。',
                ],
                'animation' => [
                    'string' => 'スケルトン アニメーションは文字列である必要があります。',
                    'in' => 'スケルトン アニメーションは pulse、wave、none のいずれかである必要があります。',
                ],
                'iteration_count' => [
                    'integer' => 'スケルトン 繰り返し回数は整数である必要があります。',
                    'min' => 'スケルトン 繰り返し回数は最小 :min である必要があります。',
                    'max' => 'スケルトン 繰り返し回数は最大 :max を超えることはできません。',
                ],
            ],
            'wait_for' => [
                'background' => 'wait_for には background データソースを指定することはできません (ユーザーをブロックできません): :id',
                'websocket' => 'wait_for には websocket データソースを指定することはできません (フェッチ完了イベントがありません): :id',
            ],
        ],
    ],
    'endpoint' => [
        'must_be_string' => 'API エンドポイントは文字列である必要があります。',
        'external_url_not_allowed' => '外部 URL は許可されていません。',
        'not_whitelisted' => '許可されていない API エンドポイントです。許可されたパターン: :pattern',
        'path_traversal_detected' => 'パストラバーサル攻撃が検出されました。',
    ],
    'external_url' => [
        'detected_in_props' => 'props で外部 URL が検出されました: :url',
        'detected_in_actions' => 'actions で外部 URL が検出されました: :url',
        'http_not_allowed' => 'HTTP プロトコル URL は許可されていません。',
        'https_not_allowed' => 'HTTPS プロトコル URL は許可されていません。',
        'data_uri_not_allowed' => 'Data URI スキームは許可されていません。',
        'javascript_uri_not_allowed' => 'JavaScript URI スキームは許可されていません。',
        'dangerous_scheme_detected' => '危険な URI スキームが検出されました: :scheme',
    ],
    'component' => [
        'template_id_required' => 'コンポーネント検証には template_id が必要です。',
        'manifest_not_found' => 'テンプレート :templateId のコンポーネント マニフェスト(components.json)が見つかりません。',
        'name_empty' => 'components[:index].component 名は空にすることはできません。',
        'not_found' => 'コンポーネント \':component\' はテンプレートに登録されていません。(components[:index])',
    ],
    'request' => [
        'template_id' => [
            'required' => 'テンプレート ID は必須です。',
            'integer' => 'テンプレート ID は整数である必要があります。',
            'exists' => '存在しないテンプレートです。',
        ],
        'layout_name' => [
            'required' => 'レイアウト 名は必須です。',
            'string' => 'レイアウト 名は文字列である必要があります。',
            'max' => 'レイアウト 名は :max 文字を超えることはできません。',
            'unique' => '既に存在するレイアウト 名です。',
        ],
        'content' => [
            'required' => 'レイアウト 内容は必須です。',
            'array' => 'レイアウト 内容は配列(オブジェクト)である必要があります。',
        ],
    ],
    'layout_inheritance' => [
        'parent_not_found' => '親レイアウト ":parent" が見つかりません。',
        'parent_not_in_same_template' => '親レイアウトは同じテンプレート内にある必要があります。',
        'circular_reference' => 'レイアウト 循環参照が検出されました: :trace',
        'max_depth_exceeded' => 'レイアウト 継承の深さが最大許容深さ(:max)を超えました。',
        'extends_must_be_string' => 'extendsフィールドは文字列である必要があります。',
        'slots_must_be_object' => 'slotsフィールドはオブジェクトである必要があります。',
        'slot_name_must_be_string' => 'スロット名は文字列である必要があります。',
        'slot_value_must_be_array' => 'slots[:slotName]は配列である必要があります。',
        'slot_not_defined_in_parent' => 'スロット":slotName"は親レイアウトに定義されていません。',
        'parent_has_no_slots' => '親レイアウトにはスロットが定義されていません。',
        'data_source_id_duplicate' => 'data_sourcesに重複したID":id"があります。',
        'data_sources_must_be_array' => 'data_sourcesは配列である必要があります。',
        'data_source_must_have_id' => 'data_sources[:index]に必須フィールド"id"が不足しています。',
        'data_source_id_must_be_string' => 'data_sources[:index].idは文字列である必要があります。',
    ],
    'translatable' => [
        'must_be_array' => '多言語フィールドは配列である必要があります。',
        'unsupported_language' => 'サポートされていない言語コードです:\':lang\'',
        'must_be_string' => '\':lang\'翻訳は文字列である必要があります。',
        'max_length' => '\':lang\'翻訳は:max文字を超えることができません。',
        'min_length' => '\':lang\'翻訳は最小:min文字以上である必要があります。',
        'at_least_one_required' => '最低1つの言語での翻訳が必要です。',
        'current_locale_required' => ':localeの値は必須です。',
    ],
    'template' => [
        'name' => [
            'max' => 'テンプレート名は:max文字を超えることができません。',
        ],
        'description' => [
            'max' => 'テンプレート説明は:max文字を超えることができません。',
        ],
        'metadata' => [
            'array' => 'metadataは配列である必要があります。',
        ],
        'status' => [
            'in' => 'statusはactiveまたはinactiveである必要があります。',
        ],
    ],
    'menu' => [
        'name' => [
            'required' => 'メニュー名を入力してください。',
        ],
        'slug' => [
            'required' => 'スラッグを入力してください。',
            'unique' => '既に使用されているスラッグです。',
            'max' => 'スラッグは:max文字を超えることができません。',
        ],
        'url' => [
            'required' => 'パス(URL)を入力してください。',
            'max' => 'URLは:max文字を超えることができません。',
        ],
        'icon' => [
            'max' => 'アイコンは:max文字を超えることができません。',
        ],
        'order' => [
            'integer' => '順序は整数である必要があります。',
            'min' => '順序は:min以上である必要があります。',
        ],
        'parent_id' => [
            'exists' => '存在しない親メニューです。',
        ],
        'is_active' => [
            'boolean' => '有効化ステータスはtrueまたはfalseである必要があります。',
        ],
        'extension_type' => [
            'in' => '拡張タイプはcore、module、plugin のいずれかである必要があります。',
        ],
        'extension_identifier' => [
            'max' => '拡張識別子は最大255文字まで入力可能です。',
            'must_be_string' => '拡張識別子は文字列である必要があります。',
            'min_parts' => '拡張識別子はvendor-name形式である必要があります(例:sirsoft-board)。',
            'empty_part' => '拡張識別子に空白部分があります。ハイフンが連続したり両端に来ることはできません。',
            'invalid_characters' => '拡張識別子は英小文字、数字、アンダースコア(_)のみ使用できます。',
            'empty_word' => '拡張識別子でアンダースコアが連続したり両端に来ることはできません。',
            'word_starts_with_digit' => '拡張識別子の各単語は数字で始まることはできません。',
        ],
        'parent_menus' => [
            'required' => '親メニュー順序配列は必須です。',
            'array' => '親メニュー順序は配列である必要があります。',
            'min' => '最低1つ以上の親メニューが必要です。',
            'id' => [
                'required' => '各親メニューIDは必須です。',
                'integer' => '親メニューIDは整数である必要があります。',
                'exists' => '存在しない親メニューIDが含まれています。',
            ],
            'order' => [
                'required' => '各親メニュー順序は必須です。',
                'integer' => '親メニュー順序は整数である必要があります。',
                'min' => 'メニュー順序は1以上である必要があります。',
            ],
        ],
        'child_menus' => [
            'array' => '子メニュー順序は配列である必要があります。',
            'id' => [
                'required' => '各子メニューIDは必須です。',
                'integer' => '子メニューIDは整数である必要があります。',
                'exists' => '存在しない子メニューIDが含まれています。',
            ],
            'order' => [
                'required' => '各子メニュー順序は必須です。',
                'integer' => '子メニュー順序は整数である必要があります。',
                'min' => 'メニュー順序は1以上である必要があります。',
            ],
        ],
        'moved_items' => [
            'array' => '移動項目は配列である必要があります。',
            'id' => [
                'required' => '移動するメニューIDは必須です。',
                'integer' => 'メニューIDは整数である必要があります。',
                'exists' => '存在しないメニューIDが含まれています。',
            ],
            'new_parent_id' => [
                'integer' => '新しい親メニューIDは整数である必要があります。',
                'exists' => '存在しない親メニューIDです。',
            ],
        ],
    ],
    'permission' => [
        'name' => [
            'required' => '権限名を入力してください。',
        ],
        'description' => [
            'max' => '権限説明は:max文字を超えることができません。',
        ],
    ],
    'role' => [
        'name' => [
            'required' => 'ロール名を入力してください。',
        ],
        'description' => [
            'max' => 'ロール説明は:max文字を超えることができません。',
        ],
    ],
    'module' => [
        'status' => [
            'in' => 'statusはactive、inactive、installed、uninstalledのいずれかである必要があります。',
        ],
    ],
    'plugin' => [
        'status' => [
            'in' => 'statusはactive、inactive、installed、uninstalledのいずれかである必要があります。',
        ],
    ],
    'template_path' => [
        'must_be_string' => 'テンプレートパスは文字列である必要があります。',
        'traversal_detected' => 'パストラバーサルパターンが検出されました::pattern',
        'absolute_path_not_allowed' => '絶対パスは許可されていません。',
        'null_byte_detected' => 'NULLバイト攻撃が検出されました。',
        'outside_base_directory' => '基準ディレクトリ外のパスは許可されていません。',
        'file_type_not_allowed' => '許可されていないファイルタイプです。拡張子::extension(許可::allowed)',
    ],
    'module_path' => [
        'must_be_string' => 'パスは文字列である必要があります。',
        'traversal_detected' => 'パストラバーサルが検出されました::pattern',
        'absolute_path_not_allowed' => '絶対パスは許可されていません。',
        'null_byte_detected' => 'NULLバイトが検出されました。',
        'outside_base_directory' => '基準ディレクトリ外へのアクセスは許可されていません。',
    ],
    'plugin_path' => [
        'must_be_string' => 'パスは文字列である必要があります。',
        'traversal_detected' => 'パストラバーサルが検出されました: :pattern',
        'absolute_path_not_allowed' => '絶対パスは許可されていません。',
        'null_byte_detected' => 'NULLバイトが検出されました。',
        'outside_base_directory' => '基本ディレクトリ外へのアクセスは許可されていません。',
    ],
    'auth' => [
        'email' => [
            'required' => 'メールは必須です。',
            'email' => '正しいメール形式ではありません。',
            'exists' => '登録されていないメールです。',
            'unique' => '既に使用中のメールです。',
        ],
        'password' => [
            'required' => 'パスワードは必須です。',
            'min' => 'パスワードは最小:min文字以上である必要があります。',
            'confirmed' => 'パスワード確認が一致しません。',
        ],
        'name' => [
            'required' => '名前は必須です。',
            'min' => '名前は最小:min文字以上である必要があります。',
            'max' => '名前は:max文字を超えることはできません。',
        ],
        'nickname' => [
            'max' => 'ニックネームは:max文字を超えることはできません。',
        ],
        'agree_terms' => [
            'accepted' => '利用規約に同意してください。',
        ],
        'agree_privacy' => [
            'accepted' => 'プライバシーポリシーに同意してください。',
        ],
        'token' => [
            'required' => 'トークンは必須です。',
            'string' => 'トークンは文字列である必要があります。',
        ],
    ],
    'asset' => [
        'identifier' => [
            'required' => '識別子は必須です。',
            'string' => '識別子は文字列である必要があります。',
        ],
        'path' => [
            'required' => 'パスは必須です。',
            'string' => 'パスは文字列である必要があります。',
        ],
    ],
    'setting' => [
        'value' => [
            'required' => '設定値は必須です。',
            'string' => '設定値は文字列である必要があります。',
            'max' => '設定値は:max文字を超えることはできません。',
        ],
    ],
    'exclude_current_user' => '現在ログインしているユーザーは一括変更対象に含めることはできません。',
    'not_self_parent' => '自分自身を親として設定することはできません。',
    'not_circular_parent' => '自分自身のサブメニューに移動することはできません。',
    'settings' => [
        'site_name_required' => 'サイト名を入力してください。',
        'site_name_max' => 'サイト名は100文字を超えることはできません。',
        'site_url_required' => 'サイトURLを入力してください。',
        'site_url_invalid' => '正しいURL形式ではありません。',
        'site_url_max' => 'サイトURLは255文字を超えることはできません。',
        'site_description_max' => 'サイト説明は500文字を超えることはできません。',
        'admin_email_required' => '管理者メールを入力してください。',
        'admin_email_invalid' => '正しいメール形式ではありません。',
        'admin_email_max' => '管理者メールは255文字を超えることはできません。',
        'timezone_required' => 'タイムゾーンを選択してください。',
        'timezone_invalid' => '正しいタイムゾーンを選択してください。',
        'language_required' => 'デフォルト言語を選択してください。',
        'language_invalid' => '正しい言語を選択してください。',
        'currency_max' => '通貨コードは10文字を超えることはできません。',
        'maintenance_mode_boolean' => 'メンテナンスモードはtrueまたはfalse値である必要があります。',
        'mailer_required' => 'メーラーを選択してください。',
        'mailer_invalid' => '正しいメーラーを選択してください。',
        'host_required' => 'SMTPホストを入力してください。',
        'host_max' => 'SMTPホストは255文字を超えることはできません。',
        'port_required' => 'ポートを入力してください。',
        'port_integer' => 'ポートは整数である必要があります。',
        'port_min' => 'ポートは1以上である必要があります。',
        'port_max' => 'ポートは65535を超えることはできません。',
        'username_max' => 'ユーザー名は255文字を超えることはできません。',
        'password_max' => 'パスワードは255文字を超えることはできません。',
        'encryption_invalid' => '正しい暗号化方式を選択してください。',
        'from_address_required' => '送信者メールを入力してください。',
        'from_address_invalid' => '正しいメール形式ではありません。',
        'from_address_max' => '送信者メールは255文字を超えることはできません。',
        'from_name_required' => '送信者名を入力してください。',
        'from_name_max' => '送信者名は255文字を超えることはできません。',
        'max_file_size_required' => '最大ファイルサイズを入力してください。',
        'max_file_size_integer' => '最大ファイルサイズは整数である必要があります。',
        'max_file_size_min' => '最大ファイルサイズは1MB以上である必要があります。',
        'max_file_size_max' => '最大ファイルサイズは1024MBを超えることはできません。',
        'allowed_extensions_required' => '許可されている拡張子を入力してください。',
        'allowed_extensions_max' => '許可されている拡張子は500文字を超えることはできません。',
        'allowed_extensions_invalid_type' => '許可されている拡張子は文字列または配列である必要があります。',
        'image_max_width_integer' => '画像の最大幅は整数である必要があります。',
        'image_max_width_min' => '画像の最大幅は100px以上である必要があります。',
        'image_max_width_max' => '画像の最大幅は10000pxを超えることはできません。',
        'image_max_height_integer' => '画像の最大高さは整数である必要があります。',
        'image_max_height_min' => '画像の最大高さは100px以上である必要があります。',
        'image_max_height_max' => '画像の最大高さは10000pxを超えることはできません。',
        'image_quality_integer' => '画像品質は整数である必要があります。',
        'image_quality_min' => '画像品質は1以上である必要があります。',
        'image_quality_max' => '画像品質は100を超えることはできません。',
        'meta_title_suffix_max' => 'タイトルサフィックスは100文字を超えることはできません。',
        'meta_description_max' => 'メタ説明は160文字を超えることはできません。',
        'meta_keywords_max' => 'メタキーワードは255文字を超えることはできません。',
        'google_analytics_id_max' => 'Google Analytics IDは50文字を超えることはできません。',
        'google_site_verification_max' => 'Google サイト確認コードは100文字を超えることはできません。',
        'naver_site_verification_max' => 'Naver サイト確認コードは100文字を超えることはできません。',
        'bot_user_agents_array' => 'ボット User-Agent リストは配列である必要があります。',
        'bot_user_agents_item_string' => 'ボット User-Agent 項目は文字列である必要があります。',
        'bot_user_agents_item_max' => 'ボット User-Agent 項目は100文字を超えることはできません。',
        'bot_detection_enabled_boolean' => 'ボット検出設定は true または false 値である必要があります。',
        'seo_cache_enabled_boolean' => 'SEO キャッシュは true または false 値である必要があります。',
        'seo_cache_ttl_integer' => 'SEO キャッシュ有効期限は整数である必要があります。',
        'seo_cache_ttl_min' => 'SEO キャッシュ有効期限は最小0秒である必要があります。',
        'seo_cache_ttl_max' => 'SEO キャッシュ有効期限は最大14400秒(4時間)を超えることはできません。',
        'sitemap_enabled_boolean' => 'Sitemap 生成設定は true または false 値である必要があります。',
        'sitemap_cache_ttl_integer' => 'Sitemap キャッシュ TTL は整数である必要があります。',
        'sitemap_cache_ttl_min' => 'Sitemap キャッシュ TTL は最小3600秒(1時間)以上である必要があります。',
        'sitemap_cache_ttl_max' => 'Sitemap キャッシュ TTL は最大604800秒(7日)を超えることはできません。',
        'sitemap_schedule_invalid' => '有効な Sitemap 生成周期を選択してください。',
        'sitemap_schedule_time_invalid' => 'Sitemap 生成時刻は HH:mm 形式である必要があります。',
        'force_https_required' => 'HTTPS 強制適用設定を選択してください。',
        'force_https_boolean' => 'HTTPS 強制適用は true または false 値である必要があります。',
        'login_attempt_enabled_required' => 'ログイン試行制限設定を選択してください。',
        'login_attempt_enabled_boolean' => 'ログイン試行制限は true または false 値である必要があります。',
        'auth_token_lifetime_integer' => '認証トークン保持時間は整数である必要があります。',
        'auth_token_lifetime_min' => '認証トークン保持時間は0以上である必要があります。',
        'auth_token_lifetime_max' => '認証トークン保持時間は最大3600分(60時間)を超えることはできません。',
        'auth_token_lifetime_range' => '認証トークン保持時間は0(無制限)または30～3600分の間である必要があります。',
        'max_login_attempts_integer' => '最大ログイン試行回数は整数である必要があります。',
        'max_login_attempts_min' => '最大ログイン試行回数は0以上である必要があります。',
        'max_login_attempts_max' => '最大ログイン試行回数は100回を超えることはできません。',
        'login_lockout_time_integer' => 'ブロック時間は整数である必要があります。',
        'login_lockout_time_min' => 'ブロック時間は0以上である必要があります。',
        'login_lockout_time_max' => 'ブロック時間は最大1440分(24時間)を超えることはできません。',
        'cache_enabled_required' => '全体 キャッシュ有効化設定を選択してください。',
        'cache_enabled_boolean' => 'キャッシュ有効化は true または false 値である必要があります。',
        'layout_cache_enabled_required' => 'レイアウト キャッシュ設定を選択してください。',
        'layout_cache_enabled_boolean' => 'レイアウト キャッシュは true または false 値である必要があります。',
        'layout_cache_ttl_required' => 'レイアウト キャッシュ有効期限を入力してください。',
        'layout_cache_ttl_integer' => 'レイアウト キャッシュ有効期限は整数である必要があります。',
        'layout_cache_ttl_min' => 'レイアウト キャッシュ有効期限は最小0秒である必要があります。',
        'layout_cache_ttl_max' => 'レイアウト キャッシュ有効期限は最大14400秒(4時間)を超えることはできません。',
        'stats_cache_enabled_required' => '統計 キャッシュ設定を選択してください。',
        'stats_cache_enabled_boolean' => '統計 キャッシュは true または false 値である必要があります。',
        'stats_cache_ttl_required' => '統計 キャッシュ有効期限を入力してください。',
        'stats_cache_ttl_integer' => '統計 キャッシュ有効期限は整数である必要があります。',
        'stats_cache_ttl_min' => '統計 キャッシュ有効期限は最小0秒である必要があります。',
        'stats_cache_ttl_max' => '統計 キャッシュ有効期限は最大14400秒(4時間)を超えることはできません。',
        'seo_cache_enabled_required' => 'SEO キャッシュ設定を選択してください。',
        'seo_cache_ttl_required' => 'SEO キャッシュ有効期限を入力してください。',
        'debug_mode_required' => 'デバッグモード設定を選択してください。',
        'debug_mode_boolean' => 'デバッグモードは true または false 値である必要があります。',
        'sql_query_log_required' => 'SQL クエリログ設定を選択してください。',
        'sql_query_log_boolean' => 'SQL クエリログは true または false 値である必要があります。',
        'core_update_github_url_invalid' => 'GitHub リポジトリ URL 形式が正しくありません。',
        'core_update_github_url_max' => 'GitHub リポジトリ URL は500文字を超えることはできません。',
        'core_update_github_token_max' => 'GitHub アクセストークンは500文字を超えることはできません。',
        'storage_driver_required' => 'ストレージドライバーを選択してください。',
        'storage_driver_invalid' => '正しいストレージドライバーを選択してください。',
        's3_bucket_max' => 'S3 バケット名は255文字を超えることはできません。',
        's3_region_invalid' => '正しい S3 リージョンを選択してください。',
        's3_access_key_max' => 'S3 Access Key は255文字を超えることはできません。',
        's3_secret_key_max' => 'S3 Secret Key は255文字を超えることはできません。',
        's3_url_invalid' => '正しい S3 URL 形式ではありません。',
        's3_url_max' => 'S3 URL は500文字を超えることはできません。',
        'cache_driver_required' => 'キャッシュドライバーを選択してください。',
        'cache_driver_invalid' => '正しいキャッシュドライバーを選択してください。',
        'redis_host_max' => 'Redis ホストは255文字を超えることはできません。',
        'redis_port_integer' => 'Redis ポートは整数である必要があります。',
        'redis_port_min' => 'Redis ポートは1以上である必要があります。',
        'redis_port_max' => 'Redis ポートは65535を超えることはできません。',
        'redis_password_max' => 'Redis パスワードは255文字を超えることはできません。',
        'redis_database_integer' => 'Redis データベースは整数である必要があります。',
        'redis_database_min' => 'Redis データベースは0以上である必要があります。',
        'redis_database_max' => 'Redis データベースは15を超えることはできません。',
        'memcached_host_max' => 'Memcached ホストは255文字を超えることはできません。',
        'memcached_port_integer' => 'Memcached ポートは整数である必要があります。',
        'memcached_port_min' => 'Memcached ポートは1以上である必要があります。',
        'memcached_port_max' => 'Memcached ポートは65535を超えることはできません。',
        'session_driver_required' => 'セッションドライバーを選択してください。',
        'session_driver_invalid' => '正しいセッションドライバーを選択してください。',
        'session_lifetime_integer' => 'セッション有効時間は整数である必要があります。',
        'session_lifetime_min' => 'セッション有効時間は最小1分である必要があります。',
        'session_lifetime_max' => 'セッション有効時間は最大30日(43200分)を超えることはできません。',
        'queue_driver_required' => 'キュードライバーを選択してください。',
        'queue_driver_invalid' => '正しいキュードライバーを選択してください。',
        'websocket_enabled_boolean' => 'WebSocket有効化設定はtrueまたはfalse値である必要があります。',
        'websocket_app_id_required' => 'WebSocket使用時はアプリIDが必須です。',
        'websocket_app_id_max' => 'WebSocketアプリIDは255文字を超えることはできません。',
        'websocket_app_key_required' => 'WebSocket使用時はアプリキーが必須です。',
        'websocket_app_key_max' => 'WebSocketアプリキーは255文字を超えることはできません。',
        'websocket_app_secret_required' => 'WebSocket使用時はアプリシークレットが必須です。',
        'websocket_app_secret_max' => 'WebSocketアプリシークレットは255文字を超えることはできません。',
        'websocket_host_max' => 'WebSocketホストは255文字を超えることはできません。',
        'websocket_port_integer' => 'WebSocketポートは整数である必要があります。',
        'websocket_port_min' => 'WebSocketポートは1以上である必要があります。',
        'websocket_port_max' => 'WebSocketポートは65535を超えることはできません。',
        'websocket_scheme_invalid' => '正しいWebSocketプロトコルを選択してください。',
        'websocket_verify_ssl_boolean' => 'SSL証明書検証設定はtrueまたはfalse値である必要があります。',
        'websocket_server_host_max' => 'WebSocketサーバーホストは255文字を超えることはできません。',
        'websocket_server_port_integer' => 'WebSocketサーバーポートは整数である必要があります。',
        'websocket_server_port_min' => 'WebSocketサーバーポートは1以上である必要があります。',
        'websocket_server_port_max' => 'WebSocketサーバーポートは65535を超えることはできません。',
        'websocket_server_scheme_invalid' => '正しいWebSocketサーバープロトコルを選択してください。',
        'search_engine_driver_invalid' => '正しい検索エンジンドライバーを選択してください。',
        'identity_default_provider_string' => 'デフォルトプロバイダーは文字列である必要があります。',
        'identity_default_provider_max' => 'デフォルトプロバイダー識別子は100文字を超えることはできません。',
        'identity_purpose_providers_array' => '目的別プロバイダーマッピングは配列である必要があります。',
        'identity_purpose_provider_string' => '目的別プロバイダー識別子は文字列である必要があります。',
        'identity_purpose_provider_max' => '目的別プロバイダー識別子は100文字を超えることはできません。',
        'identity_challenge_ttl_required' => 'Challenge有効期限時間を入力してください。',
        'identity_challenge_ttl_integer' => 'Challenge有効期限時間は整数である必要があります。',
        'identity_challenge_ttl_min' => 'Challenge有効期限時間は最小1分以上である必要があります。',
        'identity_challenge_ttl_max' => 'Challenge有効期限時間は最大1440分(24時間)を超えることはできません。',
        'identity_max_attempts_required' => '最大試行回数を入力してください。',
        'identity_max_attempts_integer' => '最大試行回数は整数である必要があります。',
        'identity_max_attempts_min' => '最大試行回数は最小1回以上である必要があります。',
        'identity_max_attempts_max' => '最大試行回数は最大20回を超えることはできません。',
        'bot_detection_library_enabled_boolean' => 'ボット検出ライブラリ設定はtrueまたはfalse値である必要があります。',
        'og_default_site_name_string' => 'OGサイト名デフォルト値は文字列である必要があります。',
        'og_default_site_name_max' => 'OGサイト名デフォルト値は200文字を超えることはできません。',
        'og_image_default_width_integer' => 'OG画像デフォルト横サイズは整数である必要があります。',
        'og_image_default_width_min' => 'OG画像デフォルト横サイズは0以上である必要があります。',
        'og_image_default_width_max' => 'OG画像デフォルト横サイズは8000以下である必要があります。',
        'og_image_default_height_integer' => 'OG画像デフォルト縦サイズは整数である必要があります。',
        'og_image_default_height_min' => 'OG画像デフォルト縦サイズは0以上である必要があります。',
        'og_image_default_height_max' => 'OG画像デフォルト縦サイズは8000以下である必要があります。',
        'twitter_default_card_string' => 'Twitterカードデフォルト値は文字列である必要があります。',
        'twitter_default_card_in' => 'Twitterカードデフォルト値はsummary、summary_large_image、app、playerのいずれかである必要があります。',
        'twitter_default_site_string' => 'Twitterサイトハンドルは文字列である必要があります。',
        'twitter_default_site_max' => 'Twitterサイトハンドルは50文字を超えることはできません。',
        'generator_enabled_boolean' => 'Generator タグ表示設定は true または false 値である必要があります。',
        'generator_content_string' => 'Generator コンテンツは文字列である必要があります。',
        'generator_content_max' => 'Generator コンテンツは200文字を超えることはできません。',
    ],
    'identity_policy' => [
        'key_required' => 'ポリシーキーを入力してください。',
        'key_max' => 'ポリシーキーは120文字を超えることはできません。',
        'key_unique' => '既に使用中のポリシーキーです。',
        'scope_required' => 'スコープを選択してください。',
        'scope_invalid' => 'スコープはroute、hook、customのいずれかである必要があります。',
        'target_required' => 'ターゲット(ルートまたはフック名)を入力してください。',
        'target_max' => 'ターゲットは255文字を超えることはできません。',
        'purpose_required' => '認証目的(Purpose)を選択してください。',
        'purpose_max' => '認証目的は64文字を超えることはできません。',
        'provider_id_max' => 'プロバイダー識別子は64文字を超えることはできません。',
        'grace_minutes_required' => 'Grace時間(分)を入力してください。',
        'grace_minutes_integer' => 'Grace時間は整数である必要があります。',
        'grace_minutes_min' => 'Grace時間は0以上である必要があります。',
        'grace_minutes_max' => 'Grace時間は43200分(30日)を超えることはできません。',
        'enabled_boolean' => '有効化値はtrueまたはfalseである必要があります。',
        'priority_integer' => '優先度は整数である必要があります。',
        'priority_min' => '優先度は0以上である必要があります。',
        'priority_max' => '優先度は65535を超えることはできません。',
        'conditions_array' => '条件(conditions)は配列である必要があります。',
        'applies_to_required' => '適用対象を選択してください。',
        'applies_to_invalid' => '適用対象はself、admin、bothのいずれかである必要があります。',
        'fail_mode_required' => '失敗モードを選択してください。',
        'fail_mode_invalid' => '失敗モードはblockまたはlog_onlyである必要があります。',
    ],
    'identity_message' => [
        'provider_not_registered' => '登録されていないIDVプロバイダーです。',
        'scope_value_not_admin_policy' => '運営者が追加したポリシー(source_type=admin)のキーと一致する必要があります。',
        'definition_already_exists' => '同一(provider、scope_type、scope_value)定義が既に存在します。',
    ],
    'attributes' => [
        'ids' => 'ユーザーID一覧',
        'user_id' => 'ユーザーID',
        'status' => 'ステータス',
        'site_name' => 'サイト名',
        'site_url' => 'サイトURL',
        'site_description' => 'サイト説明',
        'admin_email' => '管理者メール',
        'timezone' => 'タイムゾーン',
        'language' => 'デフォルト言語',
        'identity_default_provider' => 'デフォルトプロバイダー',
        'identity_purpose_providers' => '目的別プロバイダー',
        'identity_challenge_ttl_minutes' => 'Challenge有効期限時間',
        'identity_max_attempts' => '最大試行回数',
        'identity_policy_key' => 'ポリシーキー',
        'identity_policy_scope' => 'Scope',
        'identity_policy_target' => 'Target',
        'identity_policy_purpose' => '認証目的',
        'identity_policy_provider_id' => 'プロバイダー',
        'identity_policy_grace_minutes' => 'Grace時間(分)',
        'identity_policy_enabled' => '有効化',
        'identity_policy_applies_to' => '適用対象',
        'identity_policy_fail_mode' => '失敗モード',
        'mailer' => 'メーラー',
        'host' => 'SMTP ホスト',
        'port' => 'SMTP ポート',
        'username' => 'SMTP ユーザー名',
        'password' => 'SMTP パスワード',
        'encryption' => '暗号化',
        'from_address' => '送信元メール',
        'from_name' => '送信元名',
        'max_file_size' => '最大ファイルサイズ',
        'allowed_extensions' => '許可される拡張子',
        'image_max_width' => '画像最大幅',
        'image_max_height' => '画像最大高さ',
        'image_quality' => '画像品質',
        'meta_title_suffix' => 'メタタイトル接尾辞',
        'meta_description' => 'メタ説明',
        'meta_keywords' => 'メタキーワード',
        'google_analytics_id' => 'Google Analytics ID',
        'google_site_verification' => 'Google サイト確認',
        'naver_site_verification' => 'Naver サイト確認',
        'from_version' => '開始バージョン',
        'to_version' => '終了バージョン',
    ],
];
