<?php

return [
    'accepted' => ':attribute フィールドを承認する必要があります。',
    'accepted_if' => ':other が :value の場合、:attribute フィールドを承認する必要があります。',
    'active_url' => ':attribute フィールドは有効なURLである必要があります。',
    'after' => ':attribute フィールドは :date 以降の日付である必要があります。',
    'after_or_equal' => ':attribute フィールドは :date 以降または同じ日付である必要があります。',
    'alpha' => ':attribute フィールドは文字のみを含む必要があります。',
    'alpha_dash' => ':attribute フィールドは文字、数字、ダッシュ、アンダースコアのみを含む必要があります。',
    'alpha_num' => ':attribute フィールドは文字と数字のみを含む必要があります。',
    'array' => ':attribute フィールドは配列である必要があります。',
    'ascii' => ':attribute フィールドはシングルバイト英数字文字と記号のみを含む必要があります。',
    'before' => ':attribute フィールドは :date 以前の日付である必要があります。',
    'before_or_equal' => ':attribute フィールドは :date 以前または同じ日付である必要があります。',
    'between' => [
        'array' => ':attribute フィールドは :min ～ :max 個の項目を含む必要があります。',
        'file' => ':attribute フィールドは :min ～ :max KB の間である必要があります。',
        'numeric' => ':attribute フィールドは :min ～ :max の間である必要があります。',
        'string' => ':attribute フィールドは :min ～ :max 文字の間である必要があります。',
    ],
    'boolean' => ':attribute フィールドは true または false である必要があります。',
    'can' => ':attribute フィールドに許可されていない値が含まれています。',
    'confirmed' => ':attribute フィールドの確認が一致しません。',
    'contains' => ':attribute フィールドに必須の値が不足しています。',
    'current_password' => 'パスワードが正しくありません。',
    'date' => ':attribute フィールドは有効な日付である必要があります。',
    'date_equals' => ':attribute フィールドは :date と同じ日付である必要があります。',
    'date_format' => ':attribute フィールドは :format 形式と一致する必要があります。',
    'decimal' => ':attribute フィールドは :decimal 桁の小数点である必要があります。',
    'declined' => ':attribute フィールドを拒否する必要があります。',
    'declined_if' => ':other が :value の場合、:attribute フィールドを拒否する必要があります。',
    'different' => ':attribute フィールドと :other は異なる必要があります。',
    'digits' => ':attribute フィールドは :digits 桁である必要があります。',
    'digits_between' => ':attribute フィールドは :min ～ :max 桁の間である必要があります。',
    'dimensions' => ':attribute フィールドの画像サイズが正しくありません。',
    'distinct' => ':attribute フィールドに重複した値があります。',
    'doesnt_end_with' => ':attribute フィールドは次で終わってはいけません: :values。',
    'doesnt_start_with' => ':attribute フィールドは次で始まってはいけません: :values。',
    'email' => ':attribute フィールドは有効なメールアドレスである必要があります。',
    'ends_with' => ':attribute フィールドは次のいずれかで終わる必要があります: :values。',
    'enum' => '選択された :attribute は正しくありません。',
    'exists' => '選択された :attribute は正しくありません。',
    'extensions' => ':attribute フィールドは次の拡張子のいずれかである必要があります: :values。',
    'file' => ':attribute フィールドはファイルである必要があります。',
    'filled' => ':attribute フィールドに値が存在する必要があります。',
    'gt' => [
        'array' => ':attribute フィールドは :value 個を超える項目を含む必要があります。',
        'file' => ':attribute フィールドは :value KB より大きい必要があります。',
        'numeric' => ':attribute フィールドは :value より大きい必要があります。',
        'string' => ':attribute フィールドは :value 文字より長い必要があります。',
    ],
    'gte' => [
        'array' => ':attribute フィールドは :value 個以上の項目を含む必要があります。',
        'file' => ':attribute フィールドは :value KB 以上である必要があります。',
        'numeric' => ':attribute フィールドは :value 以上である必要があります。',
        'string' => ':attribute フィールドは :value 文字以上である必要があります。',
    ],
    'hex_color' => ':attribute フィールドは有効な16進数色である必要があります。',
    'image' => ':attribute フィールドは画像である必要があります。',
    'in' => '選択された :attribute は正しくありません。',
    'in_array' => ':attribute フィールドは :other に存在する必要があります。',
    'integer' => ':attribute フィールドは整数である必要があります。',
    'ip' => ':attribute フィールドは有効なIPアドレスである必要があります。',
    'ipv4' => ':attribute フィールドは有効なIPv4アドレスである必要があります。',
    'ipv6' => ':attribute フィールドは有効なIPv6アドレスである必要があります。',
    'json' => ':attribute フィールドは有効なJSON文字列である必要があります。',
    'list' => ':attribute フィールドはリストである必要があります。',
    'lowercase' => ':attribute フィールドは小文字である必要があります。',
    'lt' => [
        'array' => ':attribute フィールドは :value 個未満の項目を含む必要があります。',
        'file' => ':attribute フィールドは :value KB より小さい必要があります。',
        'numeric' => ':attribute フィールドは :value より小さい必要があります。',
        'string' => ':attribute フィールドは :value 文字より短い必要があります。',
    ],
    'lte' => [
        'array' => ':attribute フィールドは :value 個を超えてはいけません。',
        'file' => ':attribute フィールドは :value KB 以下である必要があります。',
        'numeric' => ':attribute フィールドは :value 以下である必要があります。',
        'string' => ':attribute フィールドは :value 文字以下である必要があります。',
    ],
    'mac_address' => ':attribute フィールドは有効なMACアドレスである必要があります。',
    'max' => [
        'array' => ':attribute フィールドは :max 個を超えてはいけません。',
        'file' => ':attribute フィールドは :max KB を超えてはいけません。',
        'numeric' => ':attribute フィールドは :max を超えてはいけません。',
        'string' => ':attribute フィールドは :max 文字を超えてはいけません。',
    ],
    'max_digits' => ':attribute フィールドは :max 桁を超えてはいけません。',
    'mimes' => ':attribute フィールドは次の種類のファイルである必要があります: :values。',
    'mimetypes' => ':attribute フィールドは次の種類のファイルである必要があります: :values。',
    'min' => [
        'array' => ':attribute フィールドは最低 :min 個以上である必要があります。',
        'file' => ':attribute フィールドは最低 :min KB 以上である必要があります。',
        'numeric' => ':attribute フィールドは最低 :min 以上である必要があります。',
        'string' => ':attribute フィールドは最低 :min 文字以上である必要があります。',
    ],
    'min_digits' => ':attribute フィールドは最小 :min 桁以上である必要があります。',
    'missing' => ':attribute フィールドは存在しないことが必要です。',
    'missing_if' => ':other が :value の場合、:attribute フィールドは存在しないことが必要です。',
    'missing_unless' => ':other が :value でない場合、:attribute フィールドは存在しないことが必要です。',
    'missing_with' => ':values が存在する場合、:attribute フィールドは存在しないことが必要です。',
    'missing_with_all' => ':values がすべて存在する場合、:attribute フィールドは存在しないことが必要です。',
    'multiple_of' => ':attribute フィールドは :value の倍数である必要があります。',
    'not_in' => '選択された :attribute は有効ではありません。',
    'not_regex' => ':attribute フィールド形式が正しくありません。',
    'numeric' => ':attribute フィールドは数値である必要があります。',
    'password' => [
        'letters' => ':attribute フィールドは最低 1 つの文字を含む必要があります。',
        'mixed' => ':attribute フィールドは最低 1 つの大文字と小文字を含む必要があります。',
        'numbers' => ':attribute フィールドは最低 1 つの数字を含む必要があります。',
        'symbols' => ':attribute フィールドは最低 1 つの記号を含む必要があります。',
        'uncompromised' => '指定の :attribute はデータ侵害に公開されています。別の :attribute を選択してください。',
    ],
    'present' => ':attribute フィールドは存在する必要があります。',
    'present_if' => ':other が :value の場合、:attribute フィールドは存在する必要があります。',
    'present_unless' => ':other が :value でない場合、:attribute フィールドは存在する必要があります。',
    'present_with' => ':values が存在する場合、:attribute フィールドは存在する必要があります。',
    'present_with_all' => ':values がすべて存在する場合、:attribute フィールドは存在する必要があります。',
    'prohibited' => ':attribute フィールドは禁止されています。',
    'prohibited_if' => ':other が :value の場合、:attribute フィールドは禁止されています。',
    'prohibited_unless' => ':other が :values にない場合、:attribute フィールドは禁止されています。',
    'prohibits' => ':attribute フィールドは :other が存在することを禁止しています。',
    'regex' => ':attribute フィールド形式が正しくありません。',
    'required' => ':attribute フィールドは必須です。',
    'required_array_keys' => ':attribute フィールドは以下を含む必要があります: :values。',
    'required_if' => ':other が :value の場合、:attribute フィールドは必須です。',
    'required_if_accepted' => ':other が承認されたとき、:attribute フィールドは必須です。',
    'required_if_declined' => ':other が却下されたとき、:attribute フィールドは必須です。',
    'required_unless' => ':other が :values にない場合、:attribute フィールドは必須です。',
    'required_with' => ':values が存在する場合、:attribute フィールドは必須です。',
    'required_with_all' => ':values がすべて存在する場合、:attribute フィールドは必須です。',
    'required_without' => ':values が存在しない場合、:attribute フィールドは必須です。',
    'required_without_all' => ':values がすべて存在しない場合、:attribute フィールドは必須です。',
    'same' => ':attribute フィールドと :other は一致する必要があります。',
    'size' => [
        'array' => ':attribute フィールドは :size 個の項目を含む必要があります。',
        'file' => ':attribute フィールドは :size KB である必要があります。',
        'numeric' => ':attribute フィールドは :size である必要があります。',
        'string' => ':attribute フィールドは :size 文字である必要があります。',
    ],
    'starts_with' => ':attribute フィールドは以下のいずれかで始まる必要があります: :values。',
    'string' => ':attribute フィールドは文字列である必要があります。',
    'timezone' => ':attribute フィールドは有効なタイムゾーンである必要があります。',
    'unique' => ':attribute は既に使用されています。',
    'uploaded' => ':attribute のアップロードに失敗しました。',
    'uppercase' => ':attribute フィールドは大文字である必要があります。',
    'url' => ':attribute フィールドは有効な URL である必要があります。',
    'ulid' => ':attribute フィールドは有効な ULID である必要があります。',
    'uuid' => ':attribute フィールドは有効な UUID である必要があります。',
    'custom_translation' => [
        'layout_name' => [
            'required' => 'レイアウト名は必須です。',
            'string' => 'レイアウト名は文字列である必要があります。',
            'max' => 'レイアウト名は :max 文字を超えることはできません。',
        ],
        'locale' => [
            'required' => 'ロケールは必須です。',
            'string' => 'ロケールは文字列である必要があります。',
        ],
        'value' => [
            'required' => '翻訳値は必須です。',
            'string' => '翻訳値は文字列である必要があります。',
        ],
        'values' => [
            'required' => '翻訳値は必須です。',
            'array' => '翻訳値はロケール別オブジェクトである必要があります。',
        ],
        'status' => [
            'in' => 'ステータスは active または orphaned である必要があります。',
        ],
        'expected_lock_version' => [
            'required' => '保存リクエストに expected_lock_version がありません。',
            'integer' => 'expected_lock_version は整数である必要があります。',
            'min' => 'expected_lock_version は 0 以上である必要があります。',
        ],
        'ids' => [
            'required' => '削除する多言語キーを 1 つ以上選択してください。',
            'array' => '削除対象は ID 配列である必要があります。',
            'min' => '削除する多言語キーを 1 つ以上選択してください。',
            'integer' => '多言語キー ID は整数である必要があります。',
            'exists' => '存在しない多言語キーが含まれています。',
        ],
    ],
    'layout' => [
        'expected_lock_version' => [
            'required' => '保存リクエストに expected_lock_version がありません。',
            'integer' => 'expected_lock_version は整数である必要があります。',
            'min' => 'expected_lock_version は 0 以上である必要があります。',
        ],
        'invalid_json' => '無効な JSON 形式です。',
        'must_be_array' => 'レイアウトデータは配列である必要があります。',
        'dangerous_expression' => '許可されていない式が含まれています: :snippet',
        'external_resource_url' => '外部リソース URL は許可されていません(同一オリジンのパスのみ): :url',
        'required_field_missing' => '必須フィールド \':field\' がありません。',
        'version_must_be_string' => 'version フィールドは文字列である必要があります。',
        'layout_name_must_be_string' => 'layout_name フィールドは文字列である必要があります。',
        'components_must_be_array' => 'components フィールドは配列である必要があります。',
        'components_or_slots_required' => '継承レイアウトは components または slots のいずれかが必要です。',
        'component_must_be_array' => 'components[:index] は配列である必要があります。',
        'max_depth_exceeded' => 'コンポーネントネスト深度が最大許容深度(:max)を超えています。',
        'component_required_field_missing' => 'components[:index] に必須フィールド \':field\' がありません。',
        'component_field_must_be_string' => 'components[:index].componentは文字列である必要があります。',
        'component_name_must_be_string' => 'components[:index].nameは文字列である必要があります。',
        'component_type_invalid' => 'components[:index].typeはbasic、composite、layoutのいずれかである必要があります。',
        'props_must_be_object' => 'components[:index].propsはオブジェクト(配列)である必要があります。',
        'children_must_be_array' => 'components[:index].childrenは配列である必要があります。',
        'permissions_must_be_array' => 'components[:index].permissionsは配列である必要があります。',
        'permissions_must_be_array_or_object' => 'permissionsは配列または構造化オブジェクト(or/and)である必要があります。',
        'permissions_invalid_operator' => 'permissions構造で有効な演算子は「or」または「and」のみです。キーは正確に1個である必要があります。',
        'permissions_operator_must_be_array' => 'permissionsの":operator"演算子の値は配列である必要があります。',
        'permissions_operator_min_items' => 'permissionsの":operator"演算子には最小:min個の項目が必要です。',
        'permissions_max_depth_exceeded' => 'permissions構造の最大ネストの深さ(:max)を超えました。',
        'permission_must_be_string' => 'components[:index].permissions[:perm_index]は文字列である必要があります。',
        'permission_must_be_string_or_group' => 'permissionsの項目[:index]は文字列(権限識別子)または構造化オブジェクト(or/and)である必要があります。',
        'permission_invalid_format' => 'components[:index].permissionsの":permission"は有効な権限識別子形式ではありません。',
        'actions_must_be_array' => 'components[:index].actionsは配列である必要があります。',
        'action_must_be_array' => 'components[:index].actions[:actionIndex]は配列である必要があります。',
        'action_type_missing' => 'components[:index].actions[:actionIndex]に必須フィールド\'type\'が見つかりません。',
        'action_type_or_event_missing' => 'components[:index].actions[:actionIndex]に\'type\'または\'event\'のいずれかが必要です。',
        'action_type_must_be_string' => 'components[:index].actions[:actionIndex].typeは文字列である必要があります。',
        'action_event_must_be_string' => 'components[:index].actions[:actionIndex].eventは文字列である必要があります。',
        'content' => [
            'required' => 'レイアウトcontentが必要です。',
            'array' => 'レイアウトcontentは配列である必要があります。',
        ],
        'version' => [
            'required' => 'レイアウトバージョンが必要です。',
            'string' => 'レイアウトバージョンは文字列である必要があります。',
        ],
        'layout_name' => [
            'required' => 'レイアウト名が必要です。',
            'string' => 'レイアウト名は文字列である必要があります。',
            'max' => 'レイアウト名は:max文字を超えることはできません。',
        ],
        'endpoint' => [
            'required' => 'APIエンドポイントが必要です。',
            'string' => 'APIエンドポイントは文字列である必要があります。',
        ],
        'extends' => [
            'string' => 'extendsは文字列である必要があります。',
        ],
        'slots' => [
            'array' => 'slotsは配列である必要があります。',
        ],
        'components' => [
            'required' => 'コンポーネント配列が必要です。',
            'array' => 'componentsフィールドは配列である必要があります。',
        ],
        'data_sources' => [
            'array' => 'data_sourcesフィールドは配列である必要があります。',
        ],
        'metadata' => [
            'array' => 'metadataフィールドは配列である必要があります。',
        ],
        'meta' => [
            'array' => 'metaフィールドは配列である必要があります。',
            'title' => [
                'string' => 'meta.titleは文字列である必要があります。',
            ],
            'description' => [
                'string' => 'meta.descriptionは文字列である必要があります。',
            ],
            'keywords' => [
                'string' => 'meta.keywordsは文字列である必要があります。',
            ],
            'auth_required' => [
                'boolean' => 'meta.auth_requiredはブール値である必要があります。',
            ],
            'is_base' => [
                'boolean' => 'meta.is_baseはブール値である必要があります。',
            ],
            'guest_only' => [
                'boolean' => 'meta.guest_onlyはブール値である必要があります。',
            ],
            'is_error_layout' => [
                'boolean' => 'meta.is_error_layoutはブール値である必要があります。',
            ],
            'error_code' => [
                'integer' => 'meta.error_codeは整数である必要があります。',
            ],
            'seo' => [
                'array' => 'meta.seoは配列である必要があります。',
                'enabled' => [
                    'boolean' => 'meta.seo.enabledはブール値である必要があります。',
                ],
                'data_sources' => [
                    'array' => 'meta.seo.data_sourcesは配列である必要があります。',
                    'string' => 'meta.seo.data_sourcesの各項目は文字列である必要があります。',
                ],
                'priority' => [
                    'numeric' => 'meta.seo.priorityは数値である必要があります。',
                    'min' => 'meta.seo.priorityは0以上である必要があります。',
                    'max' => 'meta.seo.priorityは1以下である必要があります。',
                ],
                'changefreq' => [
                    'string' => 'meta.seo.changefreqは文字列である必要があります。',
                    'in' => 'meta.seo.changefreqはalways、hourly、daily、weekly、monthly、yearly、neverのいずれかである必要があります。',
                ],
                'og' => [
                    'array' => 'meta.seo.ogは配列である必要があります。',
                ],
                'structured_data' => [
                    'array' => 'meta.seo.structured_dataは配列である必要があります。',
                ],
                'page_type' => [
                    'string' => 'meta.seo.page_typeは文字列である必要があります。',
                ],
                'toggle_setting' => [
                    'string' => 'meta.seo.toggle_settingは文字列である必要があります。',
                ],
                'vars' => [
                    'array' => 'meta.seo.varsは配列である必要があります。',
                ],
                'extensions' => [
                    'array' => 'meta.seo.extensionsは配列である必要があります。',
                ],
            ],
        ],
        'modals' => [
            'array' => 'modalsフィールドは配列である必要があります。',
        ],
        'state' => [
            'array' => 'stateフィールドは配列である必要があります。',
        ],
        'init_actions' => [
            'array' => 'init_actionsフィールドは配列である必要があります。',
        ],
        'defines' => [
            'array' => 'definesフィールドは配列である必要があります。',
        ],
        'init_state' => [
            'array' => 'init_stateフィールドは配列である必要があります。',
        ],
        'initLocal' => [
            'array' => 'initLocalフィールドは配列である必要があります。',
        ],
        'initGlobal' => [
            'array' => 'initGlobalフィールドは配列である必要があります。',
        ],
        'global_state' => [
            'array' => 'global_stateフィールドは配列である必要があります。',
        ],
        'errorHandling' => [
            'array' => 'errorHandlingフィールドは配列である必要があります。',
        ],
        'actions' => [
            'array' => 'actionsフィールドは配列である必要があります。',
        ],
        'pageConfig' => [
            'array' => 'pageConfigフィールドは配列である必要があります。',
        ],
        'schema' => [
            'array' => 'schemaフィールドは配列である必要があります。',
        ],
        'routes' => [
            'array' => 'routesフィールドは配列である必要があります。',
        ],
        'computed' => [
            'array' => 'computedフィールドは配列である必要があります。',
        ],
        'permissions' => [
            'array' => 'permissionsフィールドは配列である必要があります。',
            'string' => '各権限識別子は文字列である必要があります。',
            'regex' => '権限識別子形式が正しくありません。(例:module.entity.action)',
        ],
        'globalHeaders' => [
            'array' => 'globalHeadersフィールドは配列である必要があります。',
            'pattern' => [
                'required' => '各globalHeadersルールにはpatternフィールドが必要です。',
                'string' => 'globalHeaderspatternは文字列である必要があります。',
            ],
            'headers' => [
                'required' => '各globalHeadersルールにはheadersフィールドが必要です。',
                'array' => 'globalHeaders headers は配列である必要があります。',
                'string' => 'ヘッダー値は文字列である必要があります。',
            ],
        ],
        'transition_overlay' => [
            'enabled' => [
                'boolean' => 'トランジション オーバーレイ有効化は true または false 値である必要があります。',
            ],
            'style' => [
                'string' => 'トランジション オーバーレイ スタイルは文字列である必要があります。',
                'in' => 'トランジション オーバーレイ スタイルは opaque、blur、fade、skeleton のいずれかである必要があります。',
            ],
            'target' => [
                'string' => 'トランジション オーバーレイ ターゲットは文字列である必要があります。',
                'max' => 'トランジション オーバーレイ ターゲットは :max 文字を超えることはできません。',
            ],
            'fallback_target' => [
                'string' => 'トランジション オーバーレイ代替ターゲットは文字列である必要があります。',
                'max' => 'トランジション オーバーレイ代替ターゲットは :max 文字を超えることはできません。',
            ],
            'skeleton' => [
                'array' => 'スケルトン設定は配列である必要があります。',
                'component' => [
                    'string' => 'スケルトン コンポーネント名は文字列である必要があります。',
                    'max' => 'スケルトン コンポーネント名は :max 文字を超えることはできません。',
                ],
                'animation' => [
                    'string' => 'スケルトン アニメーションは文字列である必要があります。',
                    'in' => 'スケルトン アニメーションは pulse、wave、none のいずれかである必要があります。',
                ],
                'iteration_count' => [
                    'integer' => 'スケルトン 反復回数は整数である必要があります。',
                    'min' => 'スケルトン 反復回数は最小 :min である必要があります。',
                    'max' => 'スケルトン 反復回数は最大 :max を超えることはできません。',
                ],
            ],
            'wait_for' => [
                'background' => 'wait_for には background データソースを指定することはできません (ユーザーをブロックできません)：:id',
                'websocket' => 'wait_for には websocket データソースを指定することはできません (フェッチ完了イベントなし)：:id',
            ],
        ],
    ],
    'layout_extension' => [
        'expected_lock_version' => [
            'required' => '保存リクエストに expected_lock_version が不足しています。',
            'integer' => 'expected_lock_version は整数である必要があります。',
            'min' => 'expected_lock_version は 0 以上である必要があります。',
        ],
        'invalid_json' => '無効な JSON 形式です。',
        'must_be_array' => 'レイアウト拡張データは配列である必要があります。',
        'target_required' => '拡張定義には \'extension_point\' または \'target_layout\' のいずれかが必要です。',
        'target_exclusive' => '\'extension_point\' と \'target_layout\' は同時に指定することはできません。',
        'extension_point_invalid' => 'extension_point フィールドは空でない文字列である必要があります。',
        'target_layout_invalid' => 'target_layout フィールドは空でない文字列である必要があります。',
        'components_must_be_array' => 'components フィールドは配列である必要があります。',
        'injections_required' => 'overlay 拡張は injections フィールドが必要です。',
        'injections_must_be_array' => 'injections フィールドは配列である必要があります。',
        'injection_must_be_array' => 'injections[:index] は配列である必要があります。',
        'injection_target_id_required' => 'injections[:index] に target_id フィールドが必要です。',
        'injection_position_invalid' => 'injections[:index].position 値が無効です。',
        'injection_components_must_be_array' => 'injections[:index].components は配列である必要があります。',
        'injection_props_must_be_array' => 'injections[:index].props は配列である必要があります。',
        'section_must_be_array' => ':section フィールドは配列である必要があります。',
        'max_depth_exceeded' => 'コンポーネントのネスト深度が最大許容深度（:max）を超えています。',
        'component_must_be_array' => 'components[:index] は配列である必要があります。',
        'component_required_field_missing' => 'components[:index] に必須フィールド \':field\' が不足しています。',
        'component_name_must_be_string' => 'components[:index].name は文字列である必要があります。',
        'component_type_invalid' => 'components[:index].type は basic、composite、layout のいずれかである必要があります。',
        'props_must_be_object' => 'components[:index].props はオブジェクト（配列）である必要があります。',
        'children_must_be_array' => 'components[:index].children は配列である必要があります。',
        'content' => [
            'required' => '拡張コンテンツは必須です。',
            'array' => '拡張コンテンツは配列である必要があります。',
        ],
        'priority' => [
            'integer' => 'priority は整数である必要があります。',
            'min' => 'priority は 0 以上である必要があります。',
            'max' => 'priority は 9999 以下である必要があります。',
        ],
        'data_sources' => [
            'array' => 'data_sources は配列である必要があります。',
        ],
        'preview_layout' => [
            'string' => 'プレビュー レイアウト名は文字列である必要があります。',
            'max' => 'プレビュー レイアウト名は 255 文字を超えることはできません。',
            'required' => '拡張ポイント プレビューには代表レイアウト選択が必要です。',
        ],
    ],
    'endpoint' => [
        'must_be_string' => 'API エンドポイントは文字列である必要があります。',
        'external_url_not_allowed' => '外部 URL は許可されていません。',
        'not_whitelisted' => '許可されていない API エンドポイントです。許可されたパターン：:pattern',
        'path_traversal_detected' => 'パストトラバーサル攻撃が検出されました。',
    ],
    'external_url' => [
        'detected_in_props' => 'props で外部 URL が検出されました：:url',
        'detected_in_actions' => 'actions で外部 URL が検出されました：:url',
        'http_not_allowed' => 'HTTP プロトコル URL は許可されていません。',
        'https_not_allowed' => 'HTTPS プロトコル URL は許可されていません。',
        'data_uri_not_allowed' => 'Data URI スキームは許可されていません。',
        'javascript_uri_not_allowed' => 'JavaScript URI スキームは許可されていません。',
        'dangerous_scheme_detected' => '危険な URI スキームが検出されました：:scheme',
    ],
    'outbound_url' => [
        'invalid' => '正しい形式の URL ではありません。http または https で始まるアドレスを入力してください。',
        'internal_not_allowed' => '内部ネットワークアドレス（プライベート IP·localhost など）は使用できません。外部からアクセス可能なアドレスを入力してください。',
    ],
    'schedule_command' => [
        'shell_not_allowed' => '許可されていないシェルコマンドです。サーバーに登録された実行ファイルのみ使用でき、パイプ（|）·セミコロン（;）などの特殊文字は使用できません。',
        'shell_interpreter_denied' => 'インタープリタでインラインコマンド/コードを実行したり、安全でないパスを指定したりすることはできません。インタープリタの後には絶対パスのスクリプトファイルのみを指定してください。',
        'artisan_denied' => 'この Artisan コマンドはセキュリティ上の理由からスケジュール実行できません。',
        'artisan_not_allowlisted' => 'スケジュール実行が許可された Artisan コマンドではありません。キャッシュ削除·キュー処理などのメンテナンスコマンドのみ登録できます。',
        'artisan_malformed' => 'Artisan コマンドの形式が正しくありません。引用符·バックスラッシュ·短縮オプション（-v）は使用できず、"コマンド名 --オプション[=値]" の形式のみ登録できます。',
        'artisan_option_denied' => 'この Artisan コマンドに許可されていないオプションが含まれています。',
        'artisan_argument_denied' => 'この Artisan コマンドには追加の引数を付けることができません。',
    ],
    'component' => [
        'template_id_required' => 'コンポーネント検証には template_id が必要です。',
        'manifest_not_found' => 'テンプレート :templateId のコンポーネント マニフェスト（components.json）が見つかりません。',
        'name_empty' => 'components[:index].component 名は空にすることはできません。',
        'not_found' => 'コンポーネント \':component\' はテンプレートに登録されていません。（components[:index]）',
    ],
    'request' => [
        'template_id' => [
            'required' => 'テンプレート ID は必須です。',
            'integer' => 'テンプレート ID は整数である必要があります。',
            'exists' => '存在しないテンプレートです。',
        ],
        'layout_name' => [
            'required' => 'レイアウト名は必須です。',
            'string' => 'レイアウト名は文字列である必要があります。',
            'max' => 'レイアウト名は :max 文字を超えることはできません。',
            'unique' => '既に存在するレイアウト名です。',
        ],
        'content' => [
            'required' => 'レイアウト内容は必須です。',
            'array' => 'レイアウトコンテンツは配列(オブジェクト)である必要があります。',
        ],
    ],
    'layout_inheritance' => [
        'parent_not_found' => '親レイアウト ":parent" が見つかりません。',
        'parent_not_in_same_template' => '親レイアウトは同じテンプレート内に存在する必要があります。',
        'circular_reference' => 'レイアウト循環参照が検出されました: :trace',
        'max_depth_exceeded' => 'レイアウト継承の深さが最大許容深度(:max)を超えています。',
        'extends_must_be_string' => 'extends フィールドは文字列である必要があります。',
        'slots_must_be_object' => 'slots フィールドはオブジェクトである必要があります。',
        'slot_name_must_be_string' => 'スロット名は文字列である必要があります。',
        'slot_value_must_be_array' => 'slots[:slotName]は配列である必要があります。',
        'slot_not_defined_in_parent' => 'スロット ":slotName" は親レイアウトで定義されていません。',
        'parent_has_no_slots' => '親レイアウトにはスロットが定義されていません。',
        'data_source_id_duplicate' => 'data_sources に重複するID ":id" があります。',
        'data_sources_must_be_array' => 'data_sources は配列である必要があります。',
        'data_source_must_have_id' => 'data_sources[:index]に必須フィールド "id" が見つかりません。',
        'data_source_id_must_be_string' => 'data_sources[:index].id は文字列である必要があります。',
    ],
    'notification_channel' => [
        'invalid' => '通知チャネル識別子が正しくありません。',
        'unavailable' => '利用できない通知チャネルです: \':value\'',
    ],
    'translatable' => [
        'must_be_array' => '多言語フィールドは配列である必要があります。',
        'unsupported_language' => 'サポートされていない言語コード: \':lang\'',
        'must_be_string' => '\':lang\' 翻訳は文字列である必要があります。',
        'max_length' => '\':lang\' 翻訳は :max文字を超えることはできません。',
        'min_length' => '\':lang\' 翻訳は最低 :min文字以上である必要があります。',
        'at_least_one_required' => '最低1つの言語での翻訳が必要です。',
        'current_locale_required' => ':locale 言語の値は必須です。',
    ],
    'template' => [
        'name' => [
            'max' => 'テンプレート名は :max文字を超えることはできません。',
        ],
        'description' => [
            'max' => 'テンプレートの説明は :max文字を超えることはできません。',
        ],
        'metadata' => [
            'array' => 'metadata は配列である必要があります。',
        ],
        'status' => [
            'in' => 'status は active または inactive である必要があります。',
        ],
    ],
    'menu' => [
        'roles' => [
            'array' => 'ロール一覧は配列である必要があります。',
            'integer' => 'ロールIDは数値である必要があります。',
            'exists' => '選択したロールが見つかりません。',
        ],
        'name' => [
            'required' => 'メニュー名を入力してください。',
        ],
        'slug' => [
            'required' => 'スラッグを入力してください。',
            'unique' => '既に使用されているスラッグです。',
            'max' => 'スラッグは :max文字を超えることはできません。',
        ],
        'url' => [
            'required' => 'パス(URL)を入力してください。',
            'max' => 'URL は :max文字を超えることはできません。',
        ],
        'icon' => [
            'max' => 'アイコンは :max文字を超えることはできません。',
        ],
        'order' => [
            'integer' => '順序は整数である必要があります。',
            'min' => '順序は :min 以上である必要があります。',
        ],
        'parent_id' => [
            'exists' => '存在しない親メニューです。',
        ],
        'is_active' => [
            'boolean' => '有効化状態は true または false である必要があります。',
        ],
        'extension_type' => [
            'in' => '拡張タイプは core、module、plugin のいずれかである必要があります。',
        ],
        'extension_identifier' => [
            'max' => '拡張識別子は最大255文字まで入力できます。',
            'must_be_string' => '拡張識別子は文字列である必要があります。',
            'min_parts' => '拡張識別子は vendor-name 形式である必要があります (例: sirsoft-board)。',
            'empty_part' => '拡張識別子に空の部分があります。ハイフンが連続するか、両端にくることはできません。',
            'invalid_characters' => '拡張識別子は英文小文字、数字、アンダースコア(_)のみ使用できます。',
            'empty_word' => '拡張識別子でアンダースコアが連続するか、両端にくることはできません。',
            'word_starts_with_digit' => '拡張識別子の各単語は数字で始めることはできません。',
        ],
        'parent_menus' => [
            'required' => '親メニュー順序配列は必須です。',
            'array' => '親メニュー順序は配列である必要があります。',
            'min' => '最低1つ以上の親メニューが必要です。',
            'id' => [
                'required' => '各親メニューID は必須です。',
                'integer' => '親メニューID は整数である必要があります。',
                'exists' => '存在しない親メニューID が含まれています。',
            ],
            'order' => [
                'required' => '各親メニュー順序は必須です。',
                'integer' => '親メニュー順序は整数である必要があります。',
                'min' => 'メニュー順序は1以上である必要があります。',
            ],
        ],
        'child_menus' => [
            'array' => '子メニュー順序は配列である必要があります。',
            'id' => [
                'required' => '各子メニューID は必須です。',
                'integer' => '子メニューID は整数である必要があります。',
                'exists' => '存在しない子メニューID が含まれています。',
            ],
            'order' => [
                'required' => '各子メニュー順序は必須です。',
                'integer' => '子メニュー順序は整数である必要があります。',
                'min' => 'メニュー順序は1以上である必要があります。',
            ],
        ],
        'moved_items' => [
            'array' => '移動項目は配列である必要があります。',
            'id' => [
                'required' => '移動するメニューID は必須です。',
                'integer' => 'メニューID は整数である必要があります。',
                'exists' => '存在しないメニューID が含まれています。',
            ],
            'new_parent_id' => [
                'integer' => '新しい親メニューID は整数である必要があります。',
                'exists' => '存在しない親メニューID です。',
            ],
        ],
    ],
    'permission' => [
        'name' => [
            'required' => '権限名を入力してください。',
        ],
        'description' => [
            'max' => '権限説明は :max文字を超えることはできません。',
        ],
    ],
    'role' => [
        'name' => [
            'required' => 'ロール名を入力してください。',
        ],
        'description' => [
            'max' => 'ロール説明は :max文字を超えることはできません。',
        ],
    ],
    'module' => [
        'status' => [
            'in' => 'status は active、inactive、installed、uninstalled のいずれかである必要があります。',
        ],
    ],
    'plugin' => [
        'status' => [
            'in' => 'status は active、inactive、installed、uninstalled のいずれかである必要があります。',
        ],
    ],
    'template_path' => [
        'must_be_string' => 'テンプレートパスは文字列である必要があります。',
        'traversal_detected' => 'パストラバーサルパターンが検出されました: :pattern',
        'absolute_path_not_allowed' => '絶対パスは許可されていません。',
        'null_byte_detected' => 'NULL バイト攻撃が検出されました。',
        'outside_base_directory' => '基本ディレクトリ外のパスは許可されていません。',
        'file_type_not_allowed' => '許可されていないファイルタイプです。拡張子: :extension (許可: :allowed)',
    ],
    'extension_identifier' => [
        'max' => '拡張識別子は最大255文字まで入力できます。',
        'must_be_string' => '拡張識別子は文字列である必要があります。',
        'min_parts' => '拡張識別子は vendor-name 形式である必要があります（例: sirsoft-board）。',
        'empty_part' => '拡張識別子に空の部分があります。ハイフンを連続させたり両端に置くことはできません。',
        'invalid_characters' => '拡張識別子は英小文字・数字・アンダースコア（_）のみ使用できます。',
        'empty_word' => '拡張識別子でアンダースコアを連続させたり両端に置くことはできません。',
        'word_starts_with_digit' => '拡張識別子の各単語は数字で始めることはできません。',
    ],
    'module_path' => [
        'file_type_not_allowed' => '許可されていないファイルタイプです。拡張子: :extension（許可: :allowed）',
        'must_be_string' => 'パスは文字列である必要があります。',
        'traversal_detected' => 'パストトラバーサルが検出されました: :pattern',
        'absolute_path_not_allowed' => '絶対パスは許可されません。',
        'null_byte_detected' => 'NULL バイトが検出されました。',
        'outside_base_directory' => '基準ディレクトリ外へのアクセスは許可されません。',
    ],
    'plugin_path' => [
        'file_type_not_allowed' => '許可されていないファイルタイプです。拡張子: :extension（許可: :allowed）',
        'must_be_string' => 'パスは文字列である必要があります。',
        'traversal_detected' => 'パストトラバーサルが検出されました: :pattern',
        'absolute_path_not_allowed' => '絶対パスは許可されません。',
        'null_byte_detected' => 'NULL バイトが検出されました。',
        'outside_base_directory' => '基準ディレクトリ外へのアクセスは許可されません。',
    ],
    'auth' => [
        'two_factor' => [
            'challenge_required' => '認証リクエスト情報がありません。最初からログインし直してください。',
            'challenge_invalid' => '認証リクエスト情報が正しくありません。',
            'code_required' => '認証番号を入力してください。',
        ],
        'email' => [
            'required' => 'メールアドレスは必須です。',
            'email' => '正しいメールアドレス形式ではありません。',
            'exists' => '登録されていないメールアドレスです。',
            'unique' => 'すでに使用中のメールアドレスです。',
        ],
        'password' => [
            'required' => 'パスワードは必須です。',
            'min' => 'パスワードは最小 :min 文字以上である必要があります。',
            'confirmed' => 'パスワードの確認が一致しません。',
        ],
        'name' => [
            'required' => '名前は必須です。',
            'min' => '名前は最小 :min 文字以上である必要があります。',
            'max' => '名前は :max 文字を超えることはできません。',
        ],
        'nickname' => [
            'max' => 'ニックネームは :max 文字を超えることはできません。',
        ],
        'agree_terms' => [
            'accepted' => '利用規約に同意してください。',
        ],
        'agree_privacy' => [
            'accepted' => 'プライバシーポリシーに同意してください。',
        ],
        'token' => [
            'required' => 'トークンは必須です。',
            'string' => 'トークンは文字列である必要があります。',
        ],
        'mobile' => [
            'max' => '携帯電話番号は :max文字を超えることはできません。',
            'regex' => '携帯電話番号は数字と -, +, (), スペースのみ入力できます。',
        ],
        'phone' => [
            'max' => '電話番号は :max文字を超えることはできません。',
            'regex' => '電話番号は数字と -, +, (), スペースのみ入力できます。',
        ],
    ],
    'asset' => [
        'identifier' => [
            'required' => '識別子は必須です。',
            'string' => '識別子は文字列である必要があります。',
        ],
        'path' => [
            'required' => 'パスは必須です。',
            'string' => 'パスは文字列である必要があります。',
        ],
    ],
    'setting' => [
        'value' => [
            'present' => 'リクエストに設定値(value)項目が含まれている必要があります。',
            'boolean' => 'この設定には有効/無効の値のみ保存できます。',
            'integer' => 'この設定には整数のみ保存できます。',
            'numeric' => 'この設定には数値のみ保存できます。',
            'type' => '保存できない形式の設定値です。',
            'max' => '設定値は :max 文字を超えることはできません。',
            'array_max' => '設定値のサイズは :max 文字を超えることはできません。',
        ],
    ],
    'exclude_current_user' => '現在ログインしているユーザーは一括変更の対象に含めることはできません。',
    'not_self_parent' => '自分自身を親として設定することはできません。',
    'not_circular_parent' => '自分自身のサブメニューに移動することはできません。',
    'settings' => [
        'site_name_required' => 'サイト名を入力してください。',
        'site_name_max' => 'サイト名は 100 文字を超えることはできません。',
        'site_url_required' => 'サイト URL を入力してください。',
        'site_url_invalid' => '正しい URL 形式ではありません。',
        'site_url_max' => 'サイト URL は 255 文字を超えることはできません。',
        'site_description_max' => 'サイト説明は 500 文字を超えることはできません。',
        'admin_email_required' => '管理者メールアドレスを入力してください。',
        'admin_email_invalid' => '正しいメールアドレス形式ではありません。',
        'admin_email_max' => '管理者メールアドレスは 255 文字を超えることはできません。',
        'timezone_required' => 'タイムゾーンを選択してください。',
        'timezone_invalid' => '正しいタイムゾーンを選択してください。',
        'language_required' => 'デフォルト言語を選択してください。',
        'language_invalid' => '正しい言語を選択してください。',
        'currency_max' => '通貨コードは 10 文字を超えることはできません。',
        'maintenance_mode_boolean' => 'メンテナンスモードは true または false である必要があります。',
        'mailer_required' => 'メーラーを選択してください。',
        'mailer_invalid' => '正しいメーラーを選択してください。',
        'host_required' => 'SMTP ホストを入力してください。',
        'host_max' => 'SMTP ホストは 255 文字を超えることはできません。',
        'port_required' => 'ポートを入力してください。',
        'port_integer' => 'ポートは整数である必要があります。',
        'port_min' => 'ポートは 1 以上である必要があります。',
        'port_max' => 'ポートは 65535 を超えることはできません。',
        'username_max' => 'ユーザー名は 255 文字を超えることはできません。',
        'password_max' => 'パスワードは 255 文字を超えることはできません。',
        'encryption_invalid' => '正しい暗号化方式を選択してください。',
        'from_address_required' => '送信者メールアドレスを入力してください。',
        'from_address_invalid' => '正しいメールアドレス形式ではありません。',
        'from_address_max' => '送信者メールアドレスは 255 文字を超えることはできません。',
        'from_name_required' => '送信者名を入力してください。',
        'from_name_max' => '送信者名は 255 文字を超えることはできません。',
        'max_file_size_required' => '最大ファイルサイズを入力してください。',
        'max_file_size_integer' => '最大ファイルサイズは整数である必要があります。',
        'max_file_size_min' => '最大ファイルサイズは 1MB 以上である必要があります。',
        'max_file_size_max' => '最大ファイルサイズは 1024MB を超えることはできません。',
        'allowed_extensions_required' => '許可する拡張子を入力してください。',
        'allowed_extensions_max' => '許可する拡張子は 500 文字を超えることはできません。',
        'allowed_extensions_invalid_type' => '許可する拡張子は文字列または配列である必要があります。',
        'image_max_width_integer' => '画像の最大幅は整数である必要があります。',
        'image_max_width_min' => '画像の最大幅は 100px 以上である必要があります。',
        'image_max_width_max' => '画像の最大幅は 10000px を超えることはできません。',
        'image_max_height_integer' => '画像の最大高さは整数である必要があります。',
        'image_max_height_min' => '画像の最大高さは 100px 以上である必要があります。',
        'image_max_height_max' => '画像の最大高さは 10000px を超えることはできません。',
        'image_quality_integer' => '画像品質は整数である必要があります。',
        'image_quality_min' => '画像品質は 1 以上である必要があります。',
        'image_quality_max' => '画像品質は100を超えることはできません。',
        'meta_title_suffix_max' => 'タイトルサフィックスは100文字を超えることはできません。',
        'meta_description_max' => 'メタ説明は160文字を超えることはできません。',
        'meta_keywords_max' => 'メタキーワードは255文字を超えることはできません。',
        'google_analytics_id_max' => 'Google Analytics IDは50文字を超えることはできません。',
        'google_site_verification_max' => 'Google サイト確認コードは100文字を超えることはできません。',
        'naver_site_verification_max' => 'Naver サイト確認コードは100文字を超えることはできません。',
        'generator_enabled_boolean' => 'Generator タグ表示設定はtrue又はfalse値である必要があります。',
        'generator_content_string' => 'Generator コンテンツは文字列である必要があります。',
        'generator_content_max' => 'Generator コンテンツは200文字を超えることはできません。',
        'bot_user_agents_array' => 'ボット User-Agent リストは配列である必要があります。',
        'bot_user_agents_item_string' => 'ボット User-Agent アイテムは文字列である必要があります。',
        'bot_user_agents_item_max' => 'ボット User-Agent アイテムは100文字を超えることはできません。',
        'bot_detection_enabled_boolean' => 'ボット検出設定はtrue又はfalse値である必要があります。',
        'bot_detection_library_enabled_boolean' => 'ボット検出ライブラリ設定はtrue又はfalse値である必要があります。',
        'og_default_site_name_string' => 'OG サイト名デフォルト値は文字列である必要があります。',
        'og_default_site_name_max' => 'OG サイト名デフォルト値は200文字を超えることはできません。',
        'og_image_default_width_integer' => 'OG 画像デフォルト幅は整数である必要があります。',
        'og_image_default_width_min' => 'OG 画像デフォルト幅は0以上である必要があります。',
        'og_image_default_width_max' => 'OG 画像デフォルト幅は8000以下である必要があります。',
        'og_image_default_height_integer' => 'OG 画像デフォルト高さは整数である必要があります。',
        'og_image_default_height_min' => 'OG 画像デフォルト高さは0以上である必要があります。',
        'og_image_default_height_max' => 'OG 画像デフォルト高さは8000以下である必要があります。',
        'twitter_default_card_string' => 'Twitter カードデフォルト値は文字列である必要があります。',
        'twitter_default_card_in' => 'Twitter カードデフォルト値はsummary、summary_large_image、app、playerのいずれかである必要があります。',
        'twitter_default_site_string' => 'Twitter サイトハンドルは文字列である必要があります。',
        'twitter_default_site_max' => 'Twitter サイトハンドルは50文字を超えることはできません。',
        'seo_cache_enabled_boolean' => 'SEO キャッシュ設定はtrue又はfalse値である必要があります。',
        'seo_cache_ttl_integer' => 'SEO キャッシュ TTLは整数である必要があります。',
        'seo_cache_ttl_min' => 'SEO キャッシュ TTLは最小60秒以上である必要があります。',
        'seo_cache_ttl_max' => 'SEO キャッシュ TTLは最大86400秒(24時間)を超えることはできません。',
        'sitemap_enabled_boolean' => 'Sitemap 生成設定はtrue又はfalse値である必要があります。',
        'sitemap_cache_ttl_integer' => 'Sitemap キャッシュ TTLは整数である必要があります。',
        'sitemap_cache_ttl_min' => 'Sitemap キャッシュ TTLは最小3600秒(1時間)以上である必要があります。',
        'sitemap_cache_ttl_max' => 'Sitemap キャッシュ TTLは最大604800秒(7日)を超えることはできません。',
        'sitemap_urls_per_file_integer' => 'Sitemap ファイルあたりURL数は整数である必要があります。',
        'sitemap_urls_per_file_min' => 'Sitemap ファイルあたりURL数は最小1000件以上である必要があります。',
        'sitemap_urls_per_file_max' => 'Sitemap ファイルあたりURL数は最大50000件を超えることはできません。',
        'sitemap_gzip_boolean' => 'Sitemap 圧縮設定はtrue又はfalse値である必要があります。',
        'sitemap_serve_stale_on_miss_boolean' => '前Sitemap 提供設定はtrue又はfalse値である必要があります。',
        'sitemap_max_urls_per_contributor_integer' => 'クローラーあたり最大URL数は整数である必要があります。',
        'sitemap_max_urls_per_contributor_min' => 'クローラーあたり最大URL数は0以上である必要があります。',
        'sitemap_schedule_invalid' => '有効なSitemap生成周期を選択してください。',
        'sitemap_schedule_time_invalid' => 'Sitemap生成時刻はHH:mm形式である必要があります。',
        'force_https_required' => 'HTTPS強制適用設定を選択してください。',
        'force_https_boolean' => 'HTTPS強制適用はtrue又はfalse値である必要があります。',
        'allow_internal_outbound_urls_boolean' => '内部ネットワークアドレス呼び出し許可はtrue又はfalse値である必要があります。',
        'login_attempt_enabled_required' => 'ログイン試行制限設定を選択してください。',
        'login_attempt_enabled_boolean' => 'ログイン試行制限はtrue又はfalse値である必要があります。',
        'auth_token_lifetime_integer' => '認証トークン保持時間は整数である必要があります。',
        'auth_token_lifetime_min' => '認証トークン保持時間は0以上である必要があります。',
        'auth_token_lifetime_max' => '認証トークン保持時間は最大3600分(60時間)を超えることはできません。',
        'auth_token_lifetime_range' => '認証トークン保持時間は0(無限)又は30～3600分の間である必要があります。',
        'max_login_attempts_integer' => '最大ログイン試行回数は整数である必要があります。',
        'max_login_attempts_min' => '最大ログイン試行回数は0以上である必要があります。',
        'max_login_attempts_max' => '最大ログイン試行回数は100回を超えることはできません。',
        'login_lockout_time_integer' => 'ブロック時間は整数である必要があります。',
        'login_lockout_time_min' => 'ブロック時間は0以上である必要があります。',
        'login_lockout_time_max' => 'ブロック時間は最大1440分(24時間)を超えることはできません。',
        'cache_enabled_required' => '全体キャッシュ有効化設定を選択してください。',
        'cache_enabled_boolean' => 'キャッシュ有効化はtrue又はfalse値である必要があります。',
        'layout_cache_enabled_required' => 'レイアウトキャッシュ設定を選択してください。',
        'layout_cache_enabled_boolean' => 'レイアウトキャッシュはtrue又はfalse値である必要があります。',
        'layout_cache_ttl_required' => 'レイアウトキャッシュ有効期限を入力してください。',
        'layout_cache_ttl_integer' => 'レイアウトキャッシュ有効期限は整数である必要があります。',
        'layout_cache_ttl_min' => 'レイアウトキャッシュ有効期限は最小0秒である必要があります。',
        'layout_cache_ttl_max' => 'レイアウトキャッシュ有効期限は最大14400秒(4時間)を超えることはできません。',
        'stats_cache_enabled_required' => '統計キャッシュ設定を選択してください。',
        'stats_cache_enabled_boolean' => '統計キャッシュはtrue又はfalse値である必要があります。',
        'stats_cache_ttl_required' => '統計キャッシュ有効期限を入力してください。',
        'stats_cache_ttl_integer' => '統計キャッシュ有効期限は整数である必要があります。',
        'stats_cache_ttl_min' => '統計キャッシュ有効期限は最小0秒である必要があります。',
        'stats_cache_ttl_max' => '統計キャッシュ有効期限は最大14400秒(4時間)を超えることはできません。',
        'advanced_seo_cache_enabled_required' => 'SEO キャッシュ設定を選択してください。',
        'advanced_seo_cache_enabled_boolean' => 'SEO キャッシュはtrue又はfalse値である必要があります。',
        'advanced_seo_cache_ttl_required' => 'SEO キャッシュ有効期限を入力してください。',
        'advanced_seo_cache_ttl_integer' => 'SEO キャッシュ有効期限は整数である必要があります。',
        'advanced_seo_cache_ttl_min' => 'SEO キャッシュ有効期限は最小0秒である必要があります。',
        'advanced_seo_cache_ttl_max' => 'SEO キャッシュ有効期限は最大14400秒(4時間)を超えることはできません。',
        'seo_sitemap_cache_ttl_integer' => 'Sitemap キャッシュ有効期限は整数である必要があります。',
        'seo_sitemap_cache_ttl_min' => 'Sitemapキャッシュの有効期限は最小3600秒(1時間)以上である必要があります。',
        'seo_sitemap_cache_ttl_max' => 'Sitemapキャッシュの有効期限は最大604800秒(7日)を超えることはできません。',
        'debug_mode_required' => 'デバッグモード設定を選択してください。',
        'debug_mode_boolean' => 'デバッグモードはtrueまたはfalse値である必要があります。',
        'sql_query_log_required' => 'SQLクエリログ設定を選択してください。',
        'sql_query_log_boolean' => 'SQLクエリログはtrueまたはfalse値である必要があります。',

        // アウトバウンド HTTP プロキシ
        'outbound_proxy_required' => 'アウトバウンドプロキシアドレスを入力してください。',
        'outbound_proxy_string' => 'アウトバウンドプロキシアドレスは文字列である必要があります。',
        'outbound_proxy_max' => 'アウトバウンドプロキシアドレスは:max文字を超えることはできません。',
        'outbound_proxy_invalid' => 'アウトバウンドプロキシアドレスの形式が正しくありません。使用可能な形式: :schemes (例: socks5h://127.0.0.1:1080)',
        'outbound_proxy_bypass_array' => 'プロキシ除外リストは配列である必要があります。',
        'outbound_proxy_bypass_item_string' => 'プロキシ除外項目は文字列である必要があります。',
        'outbound_proxy_bypass_item_max' => 'プロキシ除外項目は:max文字を超えることはできません。',
        'core_update_github_url_invalid' => 'GitHubリポジトリURLの形式が正しくありません。',
        'core_update_github_url_max' => 'GitHubリポジトリURLは500字を超えることはできません。',
        'core_update_github_token_max' => 'GitHubアクセストークンは500字を超えることはできません。',
        'storage_driver_required' => 'ストレージドライバーを選択してください。',
        'storage_driver_invalid' => '正しいストレージドライバーを選択してください。',
        's3_bucket_max' => 'S3バケット名は255字を超えることはできません。',
        's3_region_invalid' => 'S3リージョンには小文字の英数字とハイフンのみ使用できます。(例: ap-northeast-2、Cloudflare R2 は auto)',
        's3_region_max' => 'S3リージョンは64字を超えることはできません。',
        's3_access_key_max' => 'S3 Access Keyは255字を超えることはできません。',
        's3_secret_key_max' => 'S3 Secret Keyは255字を超えることはできません。',
        's3_url_invalid' => '正しいS3 URL形式ではありません。',
        's3_url_max' => 'S3 URLは500字を超えることはできません。',
        's3_endpoint_invalid' => '正しいS3エンドポイントURL形式ではありません。',
        's3_endpoint_max' => 'S3エンドポイントURLは500字を超えることはできません。',
        's3_use_path_style_boolean' => 'Path-styleアドレス使用の設定はtrueまたはfalseである必要があります。',
        'driver_unusable' => '\':driver\' ドライバーはこのサーバーでは使用できません。:reason',
        'cache_driver_required' => 'キャッシュドライバーを選択してください。',
        'cache_driver_invalid' => '正しいキャッシュドライバーを選択してください。',
        'redis_host_max' => 'Redisホストは255字を超えることはできません。',
        'redis_port_integer' => 'Redisポートは整数である必要があります。',
        'redis_port_min' => 'Redisポートは1以上である必要があります。',
        'redis_port_max' => 'Redisポートは65535を超えることはできません。',
        'redis_password_max' => 'Redisパスワードは255字を超えることはできません。',
        'redis_database_integer' => 'Redisデータベースは整数である必要があります。',
        'redis_database_min' => 'Redisデータベースは0以上である必要があります。',
        'redis_database_max' => 'Redisデータベースは15を超えることはできません。',
        'memcached_host_max' => 'Memcachedホストは255字を超えることはできません。',
        'memcached_port_integer' => 'Memcachedポートは整数である必要があります。',
        'memcached_port_min' => 'Memcachedポートは1以上である必要があります。',
        'memcached_port_max' => 'Memcachedポートは65535を超えることはできません。',
        'session_driver_required' => 'セッションドライバーを選択してください。',
        'session_driver_invalid' => '正しいセッションドライバーを選択してください。',
        'session_lifetime_integer' => 'セッション有効時間は整数である必要があります。',
        'session_lifetime_min' => 'セッション有効時間は最小1分である必要があります。',
        'session_lifetime_max' => 'セッション有効時間は最大30日(43200分)を超えることはできません。',
        'queue_driver_required' => 'キュードライバーを選択してください。',
        'queue_driver_invalid' => '正しいキュードライバーを選択してください。',
        'websocket_enabled_boolean' => 'WebSocket使用設定はtrueまたはfalse値である必要があります。',
        'websocket_app_id_required' => 'WebSocket使用時はアプリIDが必須です。',
        'websocket_app_id_max' => 'WebSocketアプリIDは255字を超えることはできません。',
        'websocket_app_key_required' => 'WebSocket使用時はアプリキーが必須です。',
        'websocket_app_key_max' => 'WebSocketアプリキーは255字を超えることはできません。',
        'websocket_app_secret_required' => 'WebSocket使用時はアプリシークレットが必須です。',
        'websocket_app_secret_max' => 'WebSocketアプリシークレットは255字を超えることはできません。',
        'websocket_host_max' => 'WebSocketホストは255字を超えることはできません。',
        'websocket_port_integer' => 'WebSocketポートは整数である必要があります。',
        'websocket_port_min' => 'WebSocketポートは1以上である必要があります。',
        'websocket_port_max' => 'WebSocketポートは65535を超えることはできません。',
        'websocket_scheme_invalid' => '正しいWebSocketプロトコルを選択してください。',
        'websocket_verify_ssl_boolean' => 'SSL証明書検証設定はtrueまたはfalse値である必要があります。',
        'websocket_server_host_max' => 'WebSocketサーバーホストは255字を超えることはできません。',
        'websocket_server_port_integer' => 'WebSocketサーバーポートは整数である必要があります。',
        'websocket_server_port_min' => 'WebSocketサーバーポートは1以上である必要があります。',
        'websocket_server_port_max' => 'WebSocketサーバーポートは65535を超えることはできません。',
        'websocket_server_scheme_invalid' => '正しいWebSocketサーバープロトコルを選択してください。',
        'search_engine_driver_invalid' => '正しい検索エンジンドライバーを選択してください。',
        'log_driver_required' => 'ログドライバーを選択してください。',
        'log_driver_invalid' => '正しいログドライバーを選択してください。',
        'log_level_required' => 'ログレベルを選択してください。',
        'log_level_invalid' => '正しいログレベルを選択してください。',
        'log_days_integer' => 'ログ保持日数は整数である必要があります。',
        'log_days_min' => 'ログ保持日数は1以上である必要があります。',
        'log_days_max' => 'ログ保持日数は365を超えることはできません。',
        'public_asset_disk_invalid' => '正しい公開アセットディスクを選択してください。',
        's3_bucket_required' => 'S3バケット名は必須です。',
        's3_access_key_required' => 'S3 Access Keyは必須です。',
        's3_secret_key_required' => 'S3 Secret Keyは必須です。',
        's3_url_url' => 'S3 URLは有効なURLである必要があります。',
        'redis_host_required' => 'Redisホストは必須です。',
        'redis_port_required' => 'Redisポートは必須です。',
        'redis_database_required' => 'Redisデータベース番号は必須です。',
        'memcached_host_required' => 'Memcachedホストは必須です。',
        'memcached_port_required' => 'Memcachedポートは必須です。',
        'session_lifetime_required' => 'セッション有効時間は必須です。',
        'websocket_host_required' => 'WebSocketホストは必須です。',
        'websocket_port_required' => 'WebSocketポートは必須です。',
        'websocket_scheme_required' => 'WebSocketプロトコルを選択してください。',
        'identity_default_provider_string' => 'デフォルトプロバイダーは文字列である必要があります。',
        'identity_default_provider_max' => 'デフォルトプロバイダー識別子は100字を超えることはできません。',
        'identity_purpose_providers_array' => '目的別プロバイダーマッピングは配列である必要があります。',
        'identity_purpose_provider_string' => '目的別プロバイダー識別子は文字列である必要があります。',
        'identity_purpose_provider_max' => '目的別プロバイダー識別子は100文字を超えることはできません。',
        'identity_challenge_ttl_required' => 'Challenge有効期限を入力してください。',
        'identity_challenge_ttl_integer' => 'Challenge有効期限は整数である必要があります。',
        'identity_challenge_ttl_min' => 'Challenge有効期限は最小1分以上である必要があります。',
        'identity_challenge_ttl_max' => 'Challenge有効期限は最大1440分(24時間)を超えることはできません。',
        'identity_max_attempts_required' => '最大試行回数を入力してください。',
        'identity_max_attempts_integer' => '最大試行回数は整数である必要があります。',
        'identity_max_attempts_min' => '最大試行回数は最小1回以上である必要があります。',
        'identity_max_attempts_max' => '最大試行回数は最大20回を超えることはできません。',
        'sitemap_hreflang_enabled_boolean' => 'Sitemap 多言語代替リンク(hreflang) 設定は true または false 値である必要があります。',
        'pagination_result_cap_integer' => '総件数集計上限は数値である必要があります。',
        'pagination_result_cap_min' => '総件数集計上限は:min以上である必要があります。(0 = 無制限)',
        'pagination_result_cap_max' => '総件数集計上限は:maxを超えることはできません。',
        'pagination_max_page_integer' => 'ページ番号上限は数値である必要があります。',
        'pagination_max_page_min' => 'ページ番号上限は:min以上である必要があります。(0 = 無制限)',
        'pagination_max_page_max' => 'ページ番号上限は:maxを超えることはできません。',
        'orphan_cleanup_enabled_boolean' => '孤立した添付ファイルの自動クリーンアップは有効化または無効化のいずれかである必要があります。',
        'orphan_retention_days_integer' => '孤立した添付ファイルの保持期間は整数である必要があります。',
        'orphan_retention_days_min' => '孤立した添付ファイルの保持期間は1日以上である必要があります。',
        'orphan_retention_days_max' => '孤立した添付ファイルの保持期間は3650日を超えることはできません。',
    ],
    'identity_policy' => [
        'key_required' => 'ポリシーキーを入力してください。',
        'key_max' => 'ポリシーキーは120文字を超えることはできません。',
        'key_unique' => '既に使用されているポリシーキーです。',
        'scope_required' => 'スコープを選択してください。',
        'scope_invalid' => 'スコープはroute、hook、customのいずれかである必要があります。',
        'target_required' => 'ターゲット(ルート名またはフック名)を入力してください。',
        'target_max' => 'ターゲットは255文字を超えることはできません。',
        'purpose_required' => '認証目的(Purpose)を選択してください。',
        'purpose_max' => '認証目的は64文字を超えることはできません。',
        'provider_id_max' => 'プロバイダー識別子は64文字を超えることはできません。',
        'grace_minutes_required' => 'Grace時間(分)を入力してください。',
        'grace_minutes_integer' => 'Grace時間は整数である必要があります。',
        'grace_minutes_min' => 'Grace時間は0以上である必要があります。',
        'grace_minutes_max' => 'Grace時間は43200分(30日)を超えることはできません。',
        'enabled_boolean' => '有効化値はtrueまたはfalseである必要があります。',
        'priority_integer' => '優先度は整数である必要があります。',
        'priority_min' => '優先度は0以上である必要があります。',
        'priority_max' => '優先度は65535を超えることはできません。',
        'priority_duplicate' => '同じ適用位置(:target)に優先度:priorityの有効なポリシーが既に存在します。どちらのポリシーを先に適用するか決まらないため、優先度を変更するか既存のポリシーを無効化してください。',
        'conditions_array' => '条件(conditions)は配列である必要があります。',
        'applies_to_required' => '適用対象を選択してください。',
        'applies_to_invalid' => '適用対象はself、admin、bothのいずれかである必要があります。',
        'fail_mode_required' => '失敗モードを選択してください。',
        'fail_mode_invalid' => '失敗モードはblockまたはlog_onlyである必要があります。',
    ],
    'identity_message' => [
        'provider_not_registered' => '登録されていないIDVプロバイダーです。',
        'scope_value_not_admin_policy' => '運営者が追加したポリシー(source_type=admin)のキーと一致する必要があります。',
        'definition_already_exists' => '同一の(provider、scope_type、scope_value)定義が既に存在します。',
    ],
    'attributes' => [
        'layout' => 'レイアウト',
        'module' => 'モジュール',
        'token' => 'トークン',
        'mailgun_domain' => 'Mailgun ドメイン',
        'mailgun_secret' => 'Mailgun シークレット',
        'ses_key' => 'SES アクセスキー',
        'ses_secret' => 'SES シークレットキー',
        'ses_region' => 'SES リージョン',
        'ids' => 'ID一覧',
        'user_ids' => 'ユーザーID一覧',
        'user_id' => 'ユーザーID',
        'status' => 'ステータス',
        'site_name' => 'サイト名',
        'site_url' => 'サイトURL',
        'site_description' => 'サイト説明',
        'admin_email' => '管理者メール',
        'timezone' => 'タイムゾーン',
        'language' => '言語',
        'default_language' => 'デフォルト言語',
        'identity_default_provider' => 'デフォルトプロバイダー',
        'identity_purpose_providers' => '目的別プロバイダー',
        'identity_challenge_ttl_minutes' => 'Challenge有効期限',
        'identity_max_attempts' => '最大試行回数',
        'identity_policy_key' => 'ポリシーキー',
        'identity_policy_scope' => 'Scope',
        'identity_policy_target' => 'Target',
        'identity_policy_purpose' => '認証目的',
        'identity_policy_provider_id' => 'プロバイダー',
        'identity_policy_grace_minutes' => 'Grace時間(分)',
        'identity_policy_enabled' => '有効化',
        'identity_policy_applies_to' => '適用対象',
        'identity_policy_fail_mode' => '失敗モード',
        'mailer' => 'メーラー',
        'host' => 'ホスト',
        'port' => 'ポート',
        'username' => 'ユーザー名',
        'password' => 'パスワード',
        'smtp_host' => 'SMTPホスト',
        'smtp_port' => 'SMTPポート',
        'smtp_username' => 'SMTPユーザー名',
        'smtp_password' => 'SMTPパスワード',
        'encryption' => '暗号化',
        'from_address' => '送信元メールアドレス',
        'from_name' => '送信元名',
        'max_file_size' => '最大ファイルサイズ',
        'allowed_extensions' => '許可拡張子',
        'image_max_width' => '画像最大幅',
        'image_max_height' => '画像最大高さ',
        'image_quality' => '画像品質',
        'meta_title_suffix' => 'メタタイトルサフィックス',
        'meta_description' => 'メタディスクリプション',
        'meta_keywords' => 'メタキーワード',
        'google_analytics_id' => 'Google Analytics ID',
        'google_site_verification' => 'Google サイト確認',
        'naver_site_verification' => 'Naver サイト確認',
        'from_version' => '開始バージョン',
        'to_version' => '終了バージョン',
        'storage_driver' => 'ストレージドライバー',
        's3_bucket' => 'S3バケット',
        's3_region' => 'S3 リージョン',
        's3_access_key' => 'S3 Access Key',
        's3_secret_key' => 'S3 Secret Key',
        's3_url' => 'S3 URL',
        's3_endpoint' => 'S3 エンドポイントURL',
        's3_use_path_style' => 'Path-styleアドレス使用',
        'cache_driver' => 'キャッシュ ドライバー',
        'redis_host' => 'Redis ホスト',
        'redis_port' => 'Redis ポート',
        'redis_password' => 'Redis パスワード',
        'redis_database' => 'Redis データベース',
        'memcached_host' => 'Memcached ホスト',
        'memcached_port' => 'Memcached ポート',
        'session_driver' => 'セッション ドライバー',
        'session_lifetime' => 'セッション 有効期限',
        'queue_driver' => 'キュー ドライバー',
        'websocket_enabled' => 'WebSocket 使用',
        'websocket_app_key' => 'WebSocket アプリ キー',
        'websocket_host' => 'WebSocket ホスト',
        'websocket_port' => 'WebSocket ポート',
        'websocket_scheme' => 'WebSocket プロトコル',
        'mailgun_endpoint' => 'Mailgun エンドポイント',
        'channels' => 'チャンネル',
        'notification_channels' => '通知チャンネル',
        'currency' => '通貨',
        'default_currency' => 'デフォルト通貨',
        'maintenance_mode' => 'メンテナンスモード',
        'asset_url_mode' => 'アセットURL方式',
        'site_logo' => 'サイトロゴ',
        'og_image_default' => '既定の共有画像',
        'bot_user_agents' => 'ボット User-Agent 一覧',
        'bot_detection_enabled' => 'ボット検出の使用',
        'bot_detection_library_enabled' => 'ボット検出ライブラリの使用',
        'og_default_site_name' => 'OG デフォルトサイト名',
        'og_image_default_width' => 'OG 画像デフォルト幅',
        'og_image_default_height' => 'OG 画像デフォルト高さ',
        'twitter_default_card' => 'Twitter デフォルトカード種類',
        'twitter_default_site' => 'Twitter デフォルトアカウント',
        'seo_page_cache_enabled' => 'SEO ページキャッシュの使用',
        'cache_ttl' => 'キャッシュ保持時間',
        'seo_page_cache_ttl' => 'SEO ページキャッシュ保持時間',
        'sitemap_enabled' => 'サイトマップの使用',
        'sitemap_cache_ttl' => 'サイトマップキャッシュ保持時間',
        'sitemap_urls_per_file' => 'サイトマップ1ファイルあたりのURL数',
        'sitemap_gzip' => 'サイトマップ圧縮',
        'sitemap_serve_stale_on_miss' => '未生成時に既存サイトマップを提供',
        'sitemap_max_urls_per_contributor' => '項目別サイトマップ最大URL数',
        'sitemap_hreflang_enabled' => 'サイトマップ代替言語リンクの使用',
        'sitemap_schedule' => 'サイトマップ自動生成の周期',
        'sitemap_schedule_time' => 'サイトマップ自動生成の時刻',
        'generator_enabled' => 'SEO ページジェネレーターの使用',
        'generator_content' => 'SEO ページジェネレーターのコンテンツ',
        'force_https' => 'HTTPS 強制適用',
        'login_attempt_enabled' => 'ログイン試行制限',
        'auth_token_lifetime' => '認証トークン有効期限',
        'max_login_attempts' => '最大ログイン試行回数',
        'login_lockout_time' => 'ログインブロック時間',
        'password_min_length' => 'パスワード最小長',
        'require_password_special_char' => 'パスワード特殊文字必須',
        'two_factor_auth' => '2段階認証',
        'allow_internal_outbound_urls' => '内部ネットワークアドレス呼び出しの許可',
        'advanced_cache_enabled' => 'キャッシュの使用',
        'layout_cache_enabled' => 'レイアウトキャッシュの使用',
        'layout_cache_ttl' => 'レイアウトキャッシュ保持時間',
        'stats_cache_enabled' => '統計キャッシュの使用',
        'stats_cache_ttl' => '統計キャッシュ保持時間',
        'seo_cache_enabled' => 'SEO キャッシュの使用',
        'seo_cache_ttl' => 'SEO キャッシュ保持時間',
        'seo_sitemap_cache_ttl' => 'SEO サイトマップキャッシュ保持時間',
        'debug_mode' => 'デバッグモード',
        'sql_query_log' => 'SQL クエリログ',
        'outbound_proxy' => 'アウトバウンドプロキシアドレス',
        'outbound_proxy_bypass' => 'プロキシ除外リスト',
        'core_update_github_url' => 'コア更新 GitHub アドレス',
        'core_update_github_token' => 'コア更新 GitHub トークン',
        'geoip_enabled' => 'GeoIP の使用',
        'geoip_license_key' => 'GeoIP ライセンスキー',
        'geoip_auto_update_enabled' => 'GeoIP 自動更新',
        'pagination_result_cap' => '総件数集計上限',
        'pagination_max_page' => 'ページ番号上限',
        'websocket_app_id' => 'WebSocket アプリ ID',
        'websocket_app_secret' => 'WebSocket アプリ シークレット',
        'websocket_verify_ssl' => 'WebSocket SSL 証明書の検証',
        'websocket_server_host' => 'WebSocket サーバー ホスト',
        'websocket_server_port' => 'WebSocket サーバー ポート',
        'websocket_server_scheme' => 'WebSocket サーバー プロトコル',
        'search_engine_driver' => '検索エンジン ドライバー',
        'log_driver' => 'ログ ドライバー',
        'log_level' => 'ログレベル',
        'log_days' => 'ログ保持日数',
        'public_asset_disk' => '公開アセットディスク',
        'orphan_cleanup_enabled' => '孤立した添付ファイルの自動クリーンアップ',
        'orphan_retention_days' => '孤立した添付ファイルの保持期間',
    ],
    'layout_version' => [
        'limit' => [
            'integer' => '閲覧数は数字である必要があります。',
            'min' => '閲覧数は1以上である必要があります。',
            'max' => '閲覧数は最大:max件です。',
        ],
    ],
];
