<?php

return [
    // アクションラベル (最後のセグメント基準)
    // ActivityLog::getActionLabelAttribute がモジュール origin のラベルをモジュール lang から優先解決
    'action' => [
        'add_to_menu' => 'メニュー追加',
        'blind' => 'ブラインド',
        'blind_content' => 'コンテンツブラインド',
        'bulk_apply' => '一括適用',
        'bulk_update_status' => '一括ステータス変更',
        'create' => '作成',
        'delete' => '削除',
        'delete_content' => 'コンテンツ削除',
        'restore' => '復元',
        'restore_content' => 'コンテンツ復元',
        'update' => '編集',
        'update_status' => 'ステータス変更',
        'upload' => 'アップロード',
    ],

    'description' => [
        'board_index' => '掲示板リスト閲覧',
        'board_show' => '掲示板詳細閲覧 (:board_name)',
        'board_create' => '掲示板作成 (:board_name)',
        'board_update' => '掲示板編集 (:board_name)',
        'board_delete' => '掲示板削除 (:board_name)',
        'board_copy' => '掲示板コピー (:board_name)',
        'board_add_to_menu' => '掲示板メニュー追加 (:board_name)',
        'board_type_index' => '掲示板タイプリスト閲覧',
        'board_type_create' => '掲示板タイプ作成 (:type_name)',
        'board_type_update' => '掲示板タイプ編集 (:type_name)',
        'board_type_delete' => '掲示板タイプ削除 (:type_name)',
        'post_create' => '投稿作成 (掲示板: :board_name, タイトル: :title)',
        'post_update' => '投稿編集 (掲示板: :board_name, タイトル: :title)',
        'post_delete' => '投稿削除 (掲示板: :board_name, ID: :post_id)',
        'post_blind' => '投稿ブラインド (掲示板: :board_name, ID: :post_id)',
        'post_restore' => '投稿復元 (掲示板: :board_name, ID: :post_id)',
        'comment_create' => 'コメント作成 (掲示板: :board_name, 投稿: :post_id)',
        'comment_update' => 'コメント編集 (ID: :comment_id)',
        'comment_delete' => 'コメント削除 (ID: :comment_id)',
        'comment_blind' => 'コメントブラインド (ID: :comment_id)',
        'comment_restore' => 'コメント復元 (ID: :comment_id)',
        'board_attachment_upload' => '添付ファイルアップロード (投稿: :post_id)',
        'board_attachment_delete' => '添付ファイル削除 (投稿: :post_id)',
        'board_attachment_reorder' => '添付ファイル順序変更 (投稿: :post_id)',
        'report_create' => '通報受け付け (ID: :report_id)',
        'report_update_status' => '通報ステータス変更 (ID: :report_id)',
        'report_bulk_update_status' => '通報一括ステータス変更 (:count件)',
        'report_delete' => '通報削除 (ID: :report_id)',
        'report_restore_content' => '通報コンテンツ復元 (ID: :report_id)',
        'report_blind_content' => '通報コンテンツブラインド (ID: :report_id)',
        'report_delete_content' => '通報コンテンツ削除 (ID: :report_id)',
        'board_settings_index' => '掲示板設定閲覧',
        'board_settings_bulk_apply' => '掲示板設定一括適用',
        'board_type_show' => '掲示板タイプ詳細閲覧 (:type_name)',
    ],
    'fields' => [
        'is_active' => '有効化',
        'per_page' => 'ページあたりの投稿数',
        'per_page_mobile' => 'モバイルページあたりの投稿数',
        'order_by' => '並べ替え基準',
        'order_direction' => '並べ替え方向',
        'type' => '掲示板タイプ',
        'show_view_count' => '閲覧数表示',
        'secret_mode' => '非公開投稿モード',
        'use_comment' => 'コメント使用',
        'use_reply' => '返信使用',
        'max_reply_depth' => '最大返信深さ',
        'use_report' => '通報使用',
        'use_file_upload' => 'ファイルアップロード使用',
        'max_file_size' => '最大ファイルサイズ',
        'max_file_count' => '最大ファイル数',
        'slug' => 'スラッグ',
        'category' => 'カテゴリ',
        'title' => 'タイトル',
        'content_mode' => 'コンテンツモード',
        'is_notice' => 'お知らせ',
        'is_secret' => '非公開投稿',
        'status' => 'ステータス',
        'content' => '内容',
    ],
];
